---
permalink: audit/accessing-audit-log-file.html 
sidebar: sidebar 
keywords: storagegrid, audit, log, log file, access, accessing 
summary: 'Le partage d"audit contient le fichier audit.log actif et tous les fichiers journaux d"audit compressés. Vous pouvez accéder aux fichiers journaux d"audit directement à partir de la ligne de commande du nœud d"administration.' 
---
= Accéder au fichier journal d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le partage d'audit contient le fichier actif `audit.log` et tous les fichiers journaux d'audit compressés. Vous pouvez accéder aux fichiers journaux d'audit directement à partir de la ligne de commande du nœud d'administration.

Le `audit.log` le fichier reste vide sauf si vous configurez StorageGRID pour *Nœuds d'administration/nœuds locaux* ou *Nœud d'administration et serveur syslog externe*. Pour plus d'informations, reportez-vous à link:../monitor/configure-log-management.html#select-log-location["Sélectionnez l'emplacement du journal"] .

.Avant de commencer
* Vous avez link:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"].
* Vous devez avoir le `Passwords.txt` fichier.
* Vous devez connaître l'adresse IP d'un nœud d'administration.


.Étapes
. Connectez-vous à un nœud d'administration :
+
.. Entrez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour basculer en root : `su -`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Accédez au répertoire contenant les fichiers journaux d'audit :
+
`cd  /var/local/audit/export/`

. Afficher le fichier journal d'audit actuel ou enregistré, selon les besoins.

