---
permalink: audit/audit-messages-main.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message 
summary: 'Les descriptions détaillées des messages d"audit renvoyés par le système sont répertoriées dans les sections suivantes. Chaque message d"audit est d"abord répertorié dans un tableau qui regroupe les messages associés en fonction de la classe d"activité que le message représente. Ces regroupements sont utiles à la fois pour comprendre les types d"activités auditées et pour sélectionner le type souhaité de filtrage des messages d"audit.' 
---
= Descriptions des messages d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les descriptions détaillées des messages d'audit renvoyés par le système sont répertoriées dans les sections suivantes. Chaque message d'audit est d'abord répertorié dans un tableau qui regroupe les messages associés en fonction de la classe d'activité que le message représente. Ces regroupements sont utiles à la fois pour comprendre les types d'activités auditées et pour sélectionner le type souhaité de filtrage des messages d'audit.

Les messages d'audit sont également répertoriés par ordre alphabétique par leur code à quatre caractères. Cette liste alphabétique vous permet de trouver des informations sur des messages spécifiques.

Les codes à quatre caractères utilisés tout au long de ce chapitre sont les valeurs ATYP trouvées dans les messages d'audit, comme indiqué dans l'exemple de message suivant :

[listing, subs="specialcharacters,quotes"]
----
2014-07-17T03:50:47.484627
\[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][*ATYP\(FC32\):SYSU*][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Pour plus d'informations sur la définition des niveaux de messages d'audit, la modification des destinations des journaux et l'utilisation d'un serveur syslog externe pour vos informations d'audit, consultezlink:../monitor/configure-log-management.html["Configurer la gestion des journaux et le serveur syslog externe"]
