---
permalink: audit/audit-log-file-rotation.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file, audit.log, audit.log file, rotation, save, autosave, auto save, auto-save 
summary: 'Les fichiers journaux d"audit sont enregistrés dans le répertoire /var/local/audit/export/ d"un nœud d"administration.  Les fichiers journaux d’audit actifs sont nommés audit.log.' 
---
= Rotation du fichier journal d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si StorageGRID est configuré pour *Nœuds d'administration/nœuds locaux* ou *Nœud d'administration et serveur syslog externe*, les fichiers journaux d'audit sont enregistrés sur le nœud d'administration. `/var/local/audit/export/` annuaire.  Les fichiers journaux d'audit actifs sont nommés `audit.log` .


NOTE: En option, vous pouvez modifier la destination des journaux d’audit et envoyer les informations d’audit à un serveur syslog externe.  Les journaux locaux des enregistrements d'audit continuent d'être générés et stockés lorsqu'un serveur syslog externe est configuré. link:../monitor/configure-audit-messages.html["Configurer les messages d'audit et le serveur syslog externe"] .

Une fois par jour, le fichier actif `audit.log` est enregistré et un nouveau `audit.log` fichier démarre. Le nom du fichier enregistré indique quand il a été enregistré, au format `_yyyy-mm-dd.txt_`. Si plusieurs journaux d'audit sont créés en une seule journée, les noms de fichier utilisent la date à laquelle le fichier a été enregistré, ajoutée par un nombre, au format `_yyyy-mm-dd.txt.n_`. Par exemple, `2018-04-15.txt` et `2018-04-15.txt.1` sont les premier et deuxième fichiers journaux créés et enregistrés le 15 avril 2018.

Après une journée, le fichier enregistré est compressé et renommé, au format `_yyyy-mm-dd.txt.gz_` , qui préserve la date originale.  Au fil du temps, le stockage du nœud d’administration alloué aux journaux d’audit est consommé.  Un script surveille la consommation d'espace du journal d'audit et supprime les fichiers journaux si nécessaire pour libérer de l'espace dans le `/var/local/audit/export/` annuaire.  Les journaux d’audit sont supprimés en fonction de la date de leur création.  Les journaux les plus anciens sont supprimés en premier.  Vous pouvez surveiller les actions du script dans le fichier suivant : `/var/local/log/manage-audit.log` .

Cet exemple montre le fichier actif `audit.log`, le fichier du jour précédent (`2018-04-15.txt`) et le fichier compressé du jour précédent (`2018-04-14.txt.gz`.

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----