---
permalink: audit/client-read-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, messages, client read, S3SL, SGET, SHEA, WGET, WHEA, S3, swift 
summary: 'Les messages d"audit de lecture du client sont consignés lorsqu"une application client S3 demande la récupération d"un objet.' 
---
= Messages d'audit de lecture du client
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les messages d'audit de lecture du client sont consignés lorsqu'une application client S3 demande la récupération d'un objet.

[cols="1a,3a,1a,1a"]
|===
| Code | Description | Utilisé par | Voir 


 a| 
S3SL
 a| 
Demande S3 Select : enregistre une fin d'étude après le renvoi d'une demande S3 Select au client. Le message S3SL peut inclure des détails de message d'erreur et de code d'erreur. La demande n'a peut-être pas abouti.
 a| 
Client S3
 a| 
link:s3-select-request.html["S3SL: Demande S3 Select"]



 a| 
SGET
 a| 
S3 GET : log une transaction réussie pour récupérer un objet ou répertorier les objets dans un compartiment.

*Remarque :* si la transaction fonctionne sur une sous-ressource, le message d'audit inclura le champ S3SR.
 a| 
Client S3
 a| 
link:sget-s3-get.html["SGET : OBTENEZ S3"]



 a| 
SHEA
 a| 
TÊTE S3 : consigne une transaction réussie pour vérifier l'existence d'un objet ou d'un compartiment.
 a| 
Client S3
 a| 
link:shea-s3-head.html["SHEA : TÊTE S3"]



 a| 
C'EST PARTI
 a| 
SWIFT GET : log une transaction réussie pour récupérer un objet ou répertorier les objets dans un conteneur.
 a| 
Client Swift
 a| 
link:wget-swift-get.html["WGET: SWIFT GET"]



 a| 
WHEA
 a| 
SWIFT HEAD : consigne une transaction réussie afin de vérifier l'existence d'un objet ou d'un conteneur.
 a| 
Client Swift
 a| 
link:whea-swift-head.html["WHEA: TÊTE SWIFT"]

|===