---
permalink: audit/gtst-grid-task-started.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTST, Grid Task Started 
summary: 'Ce message d"audit indique que le service CMN a commencé à traiter la tâche de grille spécifiée. Le message d"audit suit immédiatement le message de la tâche de grille soumise pour les tâches de grille initiées par le service interne Grid Task Submission et sélectionnées pour l"activation automatique. Pour les tâches de grille soumises dans la table en attente, ce message est généré lorsque l"utilisateur démarre la tâche de grille.' 
---
= GTST : tâche de grille démarrée
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce message d'audit indique que le service CMN a commencé à traiter la tâche de grille spécifiée. Le message d'audit suit immédiatement le message de la tâche de grille soumise pour les tâches de grille initiées par le service interne Grid Task Submission et sélectionnées pour l'activation automatique. Pour les tâches de grille soumises dans la table en attente, ce message est généré lorsque l'utilisateur démarre la tâche de grille.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
2
 a| 
ID de tâche
 a| 
Ce champ identifie de manière unique une tâche de grille générée et permet de gérer la tâche tout au long de son cycle de vie.

*Remarque :* l'ID de tâche est attribué au moment où une tâche de grille est générée, et non au moment où elle est soumise. Une tâche de grille donnée peut être soumise plusieurs fois. Dans ce cas, le champ ID tâche n'est pas suffisant pour lier de manière unique les messages d'audit soumis, lancés et terminés.



 a| 
RSLT
 a| 
Résultat
 a| 
Résultat. Ce champ n'a qu'une seule valeur :

* SUC : la tâche de grille a été démarrée avec succès.


|===