---
permalink: audit/gtsu-grid-task-submitted.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTSU, Grid Task Submitted 
summary: 'Ce message d"audit indique qu"une tâche de grille a été envoyée au service CMN.' 
---
= GTSU : tâche de grille soumise
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce message d'audit indique qu'une tâche de grille a été envoyée au service CMN.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
2
 a| 
ID de tâche
 a| 
Identifie de manière unique une tâche de grille générée et permet de gérer la tâche tout au long de son cycle de vie.

*Remarque :* l'ID de tâche est attribué au moment où une tâche de grille est générée, et non au moment où elle est soumise. Une tâche de grille donnée peut être soumise plusieurs fois. Dans ce cas, le champ ID tâche n'est pas suffisant pour lier de manière unique les messages d'audit soumis, lancés et terminés.



 a| 
TTYP
 a| 
Type de tâche
 a| 
Type de tâche de grille.



 a| 
VER
 a| 
Version de la tâche
 a| 
Numéro indiquant la version de la tâche de grille.



 a| 
TDSC
 a| 
Description de la tâche
 a| 
Description lisible par l'homme de la tâche de grille.



 a| 
CUVES
 a| 
Valide après horodatage
 a| 
La première fois (UINT64 microsecondes à partir du 1er janvier 1970 - heure UNIX) à laquelle la tâche de grille est valide.



 a| 
VBTS
 a| 
Valide avant horodatage
 a| 
Dernière heure (UINT64 microsecondes à partir du 1er janvier 1970 - heure UNIX) à laquelle la tâche de grille est valide.



 a| 
TSRC
 a| 
Source
 a| 
Source de la tâche :

* TXTB : la tâche de grille a été soumise via le système StorageGRID sous forme de bloc de texte signé.
* GRILLE : la tâche de grille a été soumise via le service de soumission de tâches Grid interne.




 a| 
ACTV
 a| 
Type d'activation
 a| 
Type d'activation :

* AUTO : la tâche de grille a été soumise pour l'activation automatique.
* PEND : la tâche de grille a été envoyée dans la table en attente. C'est la seule possibilité pour la source TXTB.




 a| 
RSLT
 a| 
Résultat
 a| 
Résultat de la soumission :

* SUC : la tâche de grille a été envoyée avec succès.
* ECHEC : la tâche a été déplacée directement vers la table historique.


|===