---
permalink: audit/sade-security-audit-enable.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SADE, Security Audit Enable 
summary: 'Ce message indique que le service d"origine \(ID de nœud\) a restauré la journalisation des messages d"audit ; les messages d"audit sont à nouveau collectés et livrés.' 
---
= SADE : activation de l'audit de sécurité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ce message indique que le service d'origine (ID de nœud) a restauré la journalisation des messages d'audit ; les messages d'audit sont de nouveau collectés et livrés.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
AETM
 a| 
Activer la méthode
 a| 
Méthode utilisée pour activer l'audit.



 a| 
AEUN
 a| 
Nom d'utilisateur
 a| 
Nom d'utilisateur qui a exécuté la commande pour activer la journalisation d'audit.



 a| 
RSLT
 a| 
Résultat
 a| 
Ce champ a la valeur AUCUNE. RSLT est un champ de message obligatoire, mais n'est pas pertinent pour ce message. AUCUN n'est utilisé plutôt que LES CMC pour que ce message ne soit pas filtré.

|===
Ce message implique que la consignation a été précédemment désactivée (SADD), mais qu'elle a maintenant été restaurée. Ces éléments sont généralement utilisés uniquement lors de l'ingestion en bloc afin d'améliorer les performances du système. Suite à l'activité groupée, l'audit est restauré et la fonctionnalité de désactivation de l'audit est bloquée définitivement.
