---
permalink: audit/sdel-s3-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SDEL, S3 DELETE 
summary: 'Lorsqu"un client S3 émet une transaction DE SUPPRESSION, une requête est formulée pour supprimer l"objet ou le compartiment spécifié. Ce message est émis par le serveur si la transaction a réussi.' 
---
= SDEL : SUPPRESSION S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsqu'un client S3 émet une transaction DE SUPPRESSION, une demande de suppression de l'objet ou du compartiment spécifié ou de suppression d'une sous-ressource de compartiment/objet est formulée. Ce message est émis par le serveur si la transaction a réussi.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
CBID
 a| 
Identificateur du bloc de contenu
 a| 
Identifiant unique du bloc de contenu demandé. Si le CBID est inconnu, ce champ est défini sur 0. Les opérations sur les compartiments n'incluent pas ce champ.



 a| 
CNCH
 a| 
En-tête de contrôle de cohérence
 a| 
Valeur de l'en-tête de la requête HTTP de contrôle de cohérence, s'il est présent dans la demande.



 a| 
CNID
 a| 
Identificateur de connexion
 a| 
Identifiant système unique pour la connexion TCP/IP.



 a| 
CSIZ
 a| 
Taille du contenu
 a| 
Taille de l'objet supprimé en octets. Les opérations sur les compartiments n'incluent pas ce champ.



 a| 
DMRM
 a| 
Supprimer l'ID de version de marqueur
 a| 
ID de version du marqueur de suppression créé lors de la suppression d'un objet d'un compartiment multiversion. Les opérations sur les compartiments n'incluent pas ce champ.



 a| 
GFID
 a| 
ID de connexion de fédération de grille
 a| 
ID de connexion de la connexion de fédération de grille associée à une demande de suppression de réplication de grille croisée. Inclus uniquement dans les journaux d'audit sur la grille de destination.



 a| 
GFSA
 a| 
ID de compte source de fédération de grille
 a| 
ID de compte du locataire sur la grille source pour une demande de suppression de réplication multigrille. Inclus uniquement dans les journaux d'audit sur la grille de destination.



 a| 
HTRH
 a| 
En-tête de requête HTTP
 a| 
Liste des noms et valeurs d'en-tête de requête HTTP consignés sélectionnés lors de la configuration.

 `X-Forwarded-For` Est automatiquement inclus s'il est présent dans la demande et si la `X-Forwarded-For` valeur est différente de l'adresse IP de l'expéditeur de la demande (champ d'audit SAIP).

`x-amz-bypass-governance-retention` est automatiquement inclus s'il est présent dans la demande.



 a| 
MTME
 a| 
Heure de la dernière modification
 a| 
Horodatage Unix, en microsecondes, indiquant quand l'objet a été modifié pour la dernière fois.



 a| 
RSLT
 a| 
Code de résultat
 a| 
Résultat de la transaction DE SUPPRESSION. Le résultat est toujours :

CMC : réussi



 a| 
S3AI
 a| 
ID de compte de locataire S3 (expéditeur de la demande)
 a| 
ID de compte de locataire de l'utilisateur qui a envoyé la demande. Une valeur vide indique un accès anonyme.



 a| 
S3AK
 a| 
ID de clé d'accès S3 (expéditeur de la demande)
 a| 
ID de clé d'accès S3 écrasé pour l'utilisateur qui a envoyé la demande. Une valeur vide indique un accès anonyme.



 a| 
S3BK
 a| 
Compartiment S3
 a| 
Nom du compartiment S3.



 a| 
S3KY
 a| 
Clé S3
 a| 
Le nom de la clé S3 n'inclut pas le nom du compartiment. Les opérations sur les compartiments n'incluent pas ce champ.



 a| 
S3SR
 a| 
Sous-ressource S3
 a| 
Le godet ou la sous-ressource d'objet utilisé, le cas échéant.



 a| 
CCUA
 a| 
Nom du compte de locataire S3 (expéditeur de la demande)
 a| 
Nom du compte de tenant pour l'utilisateur qui a envoyé la demande. Vide pour les demandes anonymes.



 a| 
SAIP
 a| 
Adresse IP (expéditeur de la demande)
 a| 
Adresse IP de l'application client qui a fait la demande.



 a| 
SBAC
 a| 
Nom de compte de locataire S3 (propriétaire du compartiment)
 a| 
Nom du compte du locataire pour le propriétaire du compartiment. Permet d'identifier les accès inter-comptes ou anonymes.



 a| 
SBAI
 a| 
ID de compte de locataire S3 (propriétaire du compartiment)
 a| 
ID du compte du locataire du propriétaire du compartiment cible. Permet d'identifier les accès inter-comptes ou anonymes.



 a| 
SGRP
 a| 
Site (groupe)
 a| 
S'il est présent, l'objet a été supprimé sur le site spécifié, ce qui n'est pas le site où l'objet a été ingéré.



 a| 
SUSR
 a| 
URN de l'utilisateur S3 (expéditeur de la demande)
 a| 
L'ID du compte de locataire et le nom d'utilisateur de l'utilisateur qui fait la demande. L'utilisateur peut être un utilisateur local ou LDAP. Par exemple : `urn:sgws:identity::03393893651506583485:root`

Vide pour les demandes anonymes.



 a| 
TEMPS
 a| 
Heure
 a| 
Temps de traitement total de la demande en microsecondes.



 a| 
TIP
 a| 
Adresse IP de l'équilibreur de charge approuvée
 a| 
Si la demande a été routée par un équilibreur de charge de couche 7 approuvé, l'adresse IP de l'équilibreur de charge.



 a| 
UDM
 a| 
Identificateur unique universel pour un marqueur de suppression
 a| 
Identifiant d'un marqueur de suppression. Les messages du journal d'audit indiquent UUDM ou UUID : UUDM indique un marqueur de suppression créé à la suite d'une demande de suppression d'objet et UUID indique un objet.



 a| 
UUID
 a| 
Identifiant unique universel
 a| 
Identifiant de l'objet dans le système StorageGRID.



 a| 
VSID
 a| 
ID de version
 a| 
ID de version de la version spécifique d'un objet qui a été supprimé. Les opérations sur les compartiments et les objets dans les compartiments non versionnés n'incluent pas ce champ.

|===