---
permalink: audit/svru-object-store-verify-unknown.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SVRU, Object Store Verify Unknown 
summary: 'Le composant de stockage du service LDR analyse en continu toutes les copies des données d"objet répliquées dans le magasin d"objets. Ce message est émis lorsqu"une copie inconnue ou inattendue des données d"objet répliqué est détectée dans le magasin d"objets et déplacée vers le répertoire de quarantaine.' 
---
= SVRU : Vérification du magasin d'objets inconnue
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le composant de stockage du service LDR analyse en continu toutes les copies des données objet répliquées dans le magasin d'objets. Ce message est émis lorsqu'une copie inconnue ou inattendue des données d'objet répliqué est détectée dans le magasin d'objets et déplacée vers le répertoire de quarantaine.

[cols="1a,1a,4a"]
|===
| Code | Champ | Description 


 a| 
FPTH
 a| 
Chemin du fichier
 a| 
Chemin du fichier de la copie d'objet inattendue.



 a| 
RSLT
 a| 
Résultat
 a| 
Ce champ a la valeur 'NONE'. RSLT est un champ de message obligatoire, mais n'est pas pertinent pour ce message. 'AUCUN' est utilisé plutôt que 'UCS' pour que ce message ne soit pas filtré.

|===

NOTE: Le message d'audit SVRU: Object Store Verify Unknown doit être suivi de près. Cela signifie que des copies inattendues de données objet ont été détectées dans le magasin d'objets. Cette situation doit être examinée immédiatement pour déterminer comment ces copies ont été créées, car elle peut indiquer des défaillances matérielles imminentes.
