---
permalink: audit/using-audit-explain-tool.html 
sidebar: sidebar 
keywords: storagegrid, audit, tool, audit-explain, audit explain, translate audit messages, translate messages, translate audit message, translate message 
summary: 'Vous pouvez utiliser l"outil audit-explication pour traduire les messages d"audit dans le journal d"audit dans un format facile à lire.' 
---
= Utiliser l'outil d'explication d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `audit-explain` l'outil pour traduire les messages d'audit dans le journal d'audit dans un format facile à lire.

.Avant de commencer
* Vous avez link:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"].
* Vous devez avoir le `Passwords.txt` fichier.
* Vous devez connaître l'adresse IP du nœud d'administration principal.


.Description de la tâche
L' `audit-explain`outil, disponible sur le nœud d'administration principal, fournit des résumés simplifiés des messages d'audit dans un journal d'audit.


NOTE: Cet `audit-explain` outil est principalement destiné au support technique lors des opérations de dépannage. Le traitement des `audit-explain` requêtes peut consommer une grande quantité de puissance CPU, ce qui peut avoir un impact sur les opérations StorageGRID.

Cet exemple montre les résultats typiques de l' `audit-explain`outil. Ces quatre link:sput-s3-put.html["SPUT"]messages d'audit ont été générés lorsque le locataire S3 associé à l'ID de compte 92484777680322627870 a utilisé des demandes PUT S3 pour créer un compartiment nommé « bucket1 » et ajouter trois objets à ce compartiment.

[listing]
----
SPUT S3 PUT bucket bucket1 account:92484777680322627870 usec:124673
SPUT S3 PUT object bucket1/part1.txt tenant:92484777680322627870  cbid:9DCB157394F99FE5 usec:101485
SPUT S3 PUT object bucket1/part2.txt tenant:92484777680322627870  cbid:3CFBB07AB3D32CA9 usec:102804
SPUT S3 PUT object bucket1/part3.txt tenant:92484777680322627870  cbid:5373D73831ECC743 usec:93874
----
L' `audit-explain`outil peut effectuer les opérations suivantes :

* Traiter les journaux d'audit bruts ou compressés. Par exemple :
+
`audit-explain audit.log`

+
`audit-explain 2019-08-12.txt.gz`

* Traitez plusieurs fichiers simultanément. Par exemple :
+
`audit-explain audit.log 2019-08-12.txt.gz 2019-08-13.txt.gz`

+
`audit-explain /var/local/log/*`

* Acceptez l'entrée d'un canal, qui vous permet de filtrer et de prétraiter l'entrée à l'aide de la `grep` commande ou d'autres moyens. Par exemple :
+
`grep SPUT audit.log | audit-explain`

+
`grep bucket-name audit.log | audit-explain`



Comme les journaux d'audit peuvent être très volumineux et lents à analyser, vous gagnez du temps en filtrant les parties que vous souhaitez consulter et exécuter `audit-explain` sur les pièces, au lieu du fichier entier.

[NOTE]
====
 `audit-explain`L'outil n'accepte pas les fichiers compressés en tant qu'entrée de tuyauterie. Pour traiter des fichiers compressés, indiquez leurs noms de fichiers en tant qu'arguments de ligne de commande ou utilisez l' `zcat`outil pour décompresser d'abord les fichiers. Par exemple :

`zcat audit.log.gz | audit-explain`

====
Utilisez l' `help (-h)`option pour voir les options disponibles. Par exemple :

`$ audit-explain -h`

.Étapes
. Connectez-vous au nœud d'administration principal :
+
.. Entrez la commande suivante : `ssh admin@_primary_Admin_Node_IP_`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour basculer en root : `su -`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Entrez la commande suivante, où `/var/local/log/audit.log` représente le nom et l'emplacement du ou des fichiers à analyser :
+
`$ audit-explain /var/local/log/audit.log`

+
L' `audit-explain`outil imprime des interprétations lisibles de tous les messages du ou des fichiers spécifiés.

+

NOTE: Pour réduire la longueur des lignes et faciliter la lisibilité, les horodatages ne sont pas affichés par défaut. Si vous voulez voir les horodatages, utilisez l'(`-t`option horodatage ).


