---
permalink: swnodes/automating-installation-linux.html 
sidebar: sidebar 
keywords: how to automate linux installation 
summary: Vous pouvez automatiser l’installation Linux du service hôte StorageGRID et la configuration des nœuds de grille. 
---
= Automatiser l'installation (Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez automatiser l'installation du service hôte StorageGRID et la configuration des nœuds grid.

.Description de la tâche

NOTE: « Linux » fait référence à un déploiement RHEL, Ubuntu ou Debian.  Pour une liste des versions prises en charge, consultez le https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp (IMT)"^] .

L'automatisation du déploiement peut être utile dans les cas suivants :

* Vous utilisez déjà un framework d'orchestration standard, comme Ansible, Puppet ou Chef, pour déployer et configurer des hôtes physiques ou virtuels.
* Vous prévoyez de déployer plusieurs instances StorageGRID.
* Vous déployez une instance StorageGRID vaste et complexe.


Le service hôte StorageGRID est installé par un package et piloté par des fichiers de configuration. Vous pouvez créer les fichiers de configuration à l'aide de l'une des méthodes suivantes :

* link:creating-node-configuration-files.html["Créez les fichiers de configuration"] interactivement pendant une installation manuelle.
* Préparez les fichiers de configuration à l'avance (ou par programmation) pour permettre une installation automatisée à l'aide des frameworks d'orchestration standard, comme le décrit dans cet article.
+
StorageGRID propose des scripts Python en option pour l'automatisation de la configuration des appliances StorageGRID et de l'ensemble du système StorageGRID (la « grille »). Vous pouvez utiliser ces scripts directement ou les examiner pour apprendre à utiliser les outils de déploiement et de configuration du link:overview-of-installation-rest-api.html["API REST d'installation de StorageGRID"]grid que vous développez vous-même.





== Automatisez l'installation et la configuration du service d'hôte StorageGRID

Vous pouvez automatiser l'installation du service hôte StorageGRID à l'aide des frameworks d'orchestration standard tels qu'Ansible, Puppet, Chef, Fabric ou SaltStack.

Le service hôte StorageGRID est conditionné dans un DEB (Ubuntu ou Debian) ou un RPM (RHEL) et est piloté par des fichiers de configuration que vous pouvez préparer à l'avance (ou par programmation) pour permettre une installation automatisée.  Si vous utilisez déjà un framework d’orchestration standard pour installer et configurer votre déploiement Linux, l’ajout de StorageGRID à vos playbooks ou recettes devrait être simple.

Vous pouvez automatiser toutes les étapes pour préparer les hôtes et déployer des nœuds de grille virtuels.



=== Exemple de rôle et de PlayBook Ansible

Un exemple de rôle Ansible et de PlayBook sont fournis avec l'archive d'installation dans le `/extras` dossier. Ce PlayBook explique comment le `storagegrid` rôle prépare les hôtes et installe StorageGRID sur les serveurs cibles. Vous pouvez personnaliser le rôle ou le PlayBook selon vos besoins.


NOTE: Le PlayBook exemple n'inclut pas les étapes requises pour créer des périphériques réseau avant de démarrer le service hôte StorageGRID. Ajoutez ces étapes avant de finaliser et d'utiliser le PlayBook.

[role="tabbed-block"]
====
.RHEL
--
Pour RHEL, les tâches d'installation fournies `storagegrid` exemple de rôle utiliser le `ansible.builtin.dnf` module pour effectuer l'installation à partir des fichiers RPM locaux ou d'un référentiel Yum distant.  Si le module n'est pas disponible ou n'est pas pris en charge, vous devrez peut-être modifier les tâches Ansible appropriées dans les fichiers suivants pour utiliser le `yum` ou `ansible.builtin.yum` module:

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`


--
.Ubuntu ou Debian
--
Pour Ubuntu ou Debian, les tâches d'installation fournies `storagegrid` exemple de rôle utiliser le `ansible.builtin.apt` module pour effectuer l'installation à partir des fichiers DEB locaux ou d'un référentiel apt distant.  Si le module n'est pas disponible ou n'est pas pris en charge, vous devrez peut-être modifier les tâches Ansible appropriées dans les fichiers suivants pour utiliser le `ansible.builtin.apt` module:

* `roles/storagegrid/tasks/deb_install_from_repo.yml`
* `roles/storagegrid/tasks/deb_install_from_local.yml`


--
====


== Automatiser la configuration de StorageGRID

Une fois les nœuds grid déployés, vous pouvez automatiser la configuration du système StorageGRID.

.Avant de commencer
* Vous connaissez l'emplacement des fichiers suivants à partir de l'archive d'installation.
+
[cols="1a,1a"]
|===
| Nom du fichier | Description 


| configure-storagegrid.py  a| 
Script Python utilisé pour automatiser la configuration



| configurez-storagegrid.sample.json  a| 
Exemple de fichier de configuration à utiliser avec le script



| configurez-storagegrid.blank.json  a| 
Fichier de configuration vierge à utiliser avec le script

|===
* Vous avez créé un `configure-storagegrid.json` fichier de configuration. Pour créer ce fichier, vous pouvez modifier l'exemple de fichier de configuration (`configure-storagegrid.sample.json`) ou le fichier de configuration vide (`configure-storagegrid.blank.json`).



CAUTION: Stockez le mot de passe de gestion et la phrase secrète de provisionnement à partir de la section des mots de passe du fichier modifié. `configure-storagegrid.json` fichier de configuration dans un emplacement sécurisé. Ces mots de passe sont requis pour les procédures d’installation, d’extension et de maintenance. Vous devez également sauvegarder les fichiers modifiés. `configure-storagegrid.json` fichier de configuration et stockez-le dans un endroit sûr.

.Description de la tâche
Vous pouvez utiliser `configure-storagegrid.py` le script Python et le `configure-storagegrid.json` fichier de configuration pour automatiser la configuration de votre système StorageGRID.


NOTE: Vous pouvez également configurer le système à l'aide de Grid Manager ou de l'API d'installation.

.Étapes
. Connectez-vous à la machine Linux que vous utilisez pour exécuter le script Python.
. Accédez au répertoire dans lequel vous avez extrait l'archive d'installation.
+
Par exemple :

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
où `platform` est `debs`, , `rpms` ou `vsphere`.

. Exécutez le script Python et utilisez le fichier de configuration que vous avez créé.
+
Par exemple :

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Résultat
Un fichier de module de récupération `.zip` est généré pendant le processus de configuration et est téléchargé dans le répertoire où vous exécutez le processus d'installation et de configuration. Vous devez sauvegarder le fichier de package de restauration afin de pouvoir restaurer le système StorageGRID en cas de défaillance d'un ou plusieurs nœuds de la grille. Par exemple, copiez-le dans un emplacement sécurisé, sauvegardé sur le réseau et dans un emplacement de stockage cloud sécurisé.


CAUTION: Le fichier du progiciel de récupération doit être sécurisé car il contient des clés de cryptage et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID.

Si vous avez indiqué que des mots de passe aléatoires doivent être générés, ouvrez le `Passwords.txt` fichier et recherchez les mots de passe requis pour accéder à votre système StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Votre système StorageGRID est installé et configuré lorsqu'un message de confirmation s'affiche.

[listing]
----
StorageGRID has been configured and installed.
----