---
permalink: swnodes/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot ubuntu or debian installation 
summary: 'En cas de problème lors de l"installation de votre système StorageGRID, vous pouvez accéder aux fichiers journaux d"installation. Le support technique peut également avoir besoin d"utiliser les fichiers journaux d"installation pour résoudre les problèmes.' 
---
= Résoudre les problèmes d'installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En cas de problème lors de l'installation de votre système StorageGRID, vous pouvez accéder aux fichiers journaux d'installation. Le support technique peut également avoir besoin d'utiliser les fichiers journaux d'installation pour résoudre les problèmes.


NOTE: « Linux » fait référence à un déploiement RHEL, Ubuntu ou Debian.  Pour une liste des versions prises en charge, consultez le https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp (IMT)"^] .

[role="tabbed-block"]
====
.Linux
--
Les fichiers journaux d'installation suivants sont disponibles à partir du conteneur qui exécute chaque nœud :

* `/var/local/log/install.log` (disponible sur tous les nœuds grid)
* `/var/local/log/gdu-server.log` (Disponible sur le nœud d'administration principal)


Les fichiers journaux d'installation suivants sont disponibles auprès de l'hôte :

* `/var/log/storagegrid/daemon.log`
* `/var/log/storagegrid/nodes/node-name.log`


Pour savoir comment accéder aux fichiers journaux, reportez-vous à link:../monitor/collecting-log-files-and-system-data.html["Collecte de fichiers journaux et de données système"]la section .

--
.VMware
--
Voici les principaux fichiers journaux d'installation dont le support technique peut avoir besoin pour résoudre les problèmes.

* `/var/local/log/install.log` (disponible sur tous les nœuds grid)
* `/var/local/log/gdu-server.log` (Disponible sur le nœud d'administration principal)


*La réservation des ressources de la machine virtuelle nécessite un ajustement*

Les fichiers OVF incluent une réservation de ressources conçue pour garantir que chaque nœud de grille dispose de suffisamment de RAM et de CPU pour fonctionner efficacement. Si vous créez des machines virtuelles en déployant ces fichiers OVF sur VMware et que le nombre prédéfini de ressources n'est pas disponible, les machines virtuelles ne démarrent pas.

.Description de la tâche
Si vous êtes certain que l'hôte VM dispose de ressources suffisantes pour chaque nœud de la grille, ajustez manuellement les ressources allouées à chaque machine virtuelle, puis essayez de démarrer les machines virtuelles.

.Étapes
. Dans l'arborescence du client VMware vSphere Hypervisor, sélectionnez la machine virtuelle qui n'a pas démarré.
. Cliquez avec le bouton droit de la souris sur la machine virtuelle et sélectionnez *Modifier les paramètres*.
. Dans la fenêtre Propriétés des machines virtuelles, sélectionnez l'onglet *Ressources*.
. Ajustez les ressources allouées à la machine virtuelle :
+
.. Sélectionnez *CPU*, puis utilisez le curseur réservation pour régler la fréquence réservée à cette machine virtuelle.
.. Sélectionnez *mémoire*, puis utilisez le curseur réservation pour régler le Mo réservé pour cette machine virtuelle.


. Cliquez sur *OK*.
. Répétez cette procédure si nécessaire pour les autres machines virtuelles hébergées sur le même hôte VM.


*Le mot de passe d'installation temporaire a été désactivé*

Lorsque vous déployez un nœud VMware, vous pouvez éventuellement spécifier un mot de passe d'installation temporaire. Vous devez disposer de ce mot de passe pour accéder à la console de la machine virtuelle ou utiliser SSH avant que le nouveau nœud ne rejoint la grille.

Si vous avez voulu désactiver le mot de passe d'installation temporaire, vous devez effectuer des étapes supplémentaires pour déboguer les problèmes d'installation.

Vous pouvez effectuer l'une des opérations suivantes :

* Redéployez la machine virtuelle, mais spécifiez un mot de passe d'installation temporaire pour pouvoir accéder à la console ou utiliser SSH pour déboguer les problèmes d'installation.
* Utilisez vCenter pour définir le mot de passe :
+
.. Mettez la machine virtuelle hors tension.
.. Accédez à *VM*, sélectionnez l'onglet *configurer* et sélectionnez *vApp Options*.
.. Spécifiez le type de mot de passe d'installation temporaire à définir :
+
*** Sélectionnez *CUSTOM_TEMPORAIRES_PASSWORD* pour définir un mot de passe temporaire personnalisé.
*** Sélectionnez *TEMPORAIRE_PASSWORD_TYPE* pour utiliser le nom du noeud comme mot de passe temporaire.


.. Sélectionnez *définir la valeur*.
.. Définissez le mot de passe temporaire :
+
*** Remplacez *CUSTOM_TEMPORAIRES_PASSWORD* par une valeur de mot de passe personnalisée.
*** Mettez à jour *TEMPORAIRES_PASSWORD_TYPE* avec la valeur *use node name*.


.. Redémarrez la machine virtuelle pour appliquer le nouveau mot de passe.




--
====
.Informations associées
* Pour savoir comment accéder aux fichiers journaux, reportez-vous à link:../monitor/logs-files-reference.html["Référence des fichiers journaux"]la section .
* link:../troubleshoot/index.html["Dépanner un système StorageGRID"]
* Si vous avez besoin d'aide supplémentaire, contactez https://mysupport.netapp.com/site/global/dashboard["Support NetApp"^].

