---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 12.0 utilise la version 4 de l"API de gestion du grid. La version 4 déchiffre la version 3 ; cependant, les versions 1, 2 et 3 sont toujours prises en charge.' 
---
= Modifications apportées à l'API de gestion du grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 utilise la version 4 de l'API de gestion du grid. La version 4 déchiffre la version 3 ; cependant, les versions 1, 2 et 3 sont toujours prises en charge.


NOTE: Vous pouvez continuer à utiliser des versions obsolètes de l'API de gestion avec StorageGRID 12.0. Cependant, la prise en charge de ces versions de l'API sera supprimée dans une future version de StorageGRID. Après la mise à niveau vers StorageGRID 12.0, vous pouvez désactiver les API obsolètes à l'aide de `PUT /grid/config/management` l'API.

Pour en savoir plus, rendez-vous sur link:../admin/using-grid-management-api.html["Utilisez l'API de gestion du grid"].



== Nouveaux terminaux privés pour Move ADC

Les terminaux privés suivants ont été ajoutés pour vous permettre de link:../maintain/move-adc-service.html["Déplacer le service ADC"]passer d'un nœud de stockage à un autre sur le même site :

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`
