---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 12.0 utilise la version 4 de l"API de gestion des locataires.  La version 4 rend obsolète la version 3 ; cependant, les versions 1, 2 et 3 sont toujours prises en charge.' 
---
= Modifications apportées à l'API de gestion des locataires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 utilise la version 4 de l'API de gestion des locataires.  La version 4 rend obsolète la version 3 ; cependant, les versions 1, 2 et 3 sont toujours prises en charge.


NOTE: Vous pouvez continuer à utiliser les versions obsolètes de l'API de gestion des locataires avec StorageGRID 12.0 ; toutefois, la prise en charge de ces versions de l'API sera supprimée dans une future version de StorageGRID.  Après la mise à niveau vers StorageGRID 12.0, vous pouvez désactiver les API obsolètes à l'aide de l' `PUT /grid/config/management` API.

Pour en savoir plus, rendez-vous sur link:../tenant/understanding-tenant-management-api.html["Découvrez l'API de gestion des locataires"].



== Nouvelle API pour la réplication d'objets

Vous pouvez utiliser le `/org/cross-grid-replication/{versionId}/replicate` API pour répliquer manuellement des objets sur un bucket existant dont la réplication inter-grille est nouvellement configurée.
