---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 12.0 utilise la version 4 de l"API Grid Management.  La version 4 rend obsolète la version 3 ; cependant, les versions 1, 2 et 3 sont toujours prises en charge.' 
---
= Modifications apportées à l'API de gestion du grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 utilise la version 4 de l'API Grid Management.  La version 4 rend obsolète la version 3 ; cependant, les versions 1, 2 et 3 sont toujours prises en charge.


NOTE: Vous pouvez continuer à utiliser les versions obsolètes de l'API de gestion avec StorageGRID 12.0 ; toutefois, la prise en charge de ces versions de l'API sera supprimée dans une future version de StorageGRID.  Après la mise à niveau vers StorageGRID 12.0, vous pouvez désactiver les API obsolètes à l'aide de l' `PUT /grid/config/management` API.

Pour en savoir plus, rendez-vous sur link:../admin/using-grid-management-api.html["Utilisez l'API de gestion du grid"].



== Nouveaux points de terminaison pour les buckets de branche

Les points de terminaison suivants ont été ajoutés pour vous permettre delink:../tenant/what-is-branch-bucket.html["gérer les compartiments de branches"] :

`GET /org/containers/{branchBucketName}/branch`

`PUT /org/containers/{branchBucketName}/branch`



== Nouveaux points de terminaison privés pour Move ADC

Les points de terminaison privés suivants ont été ajoutés pour vous permettre delink:../maintain/move-adc-service.html["déplacer le service ADC"] d'un nœud de stockage à un autre sur le même site :

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`



== Nouveaux points de terminaison privés pour la conversion en nœud de données uniquement

Les points de terminaison privés suivants ont été ajoutés pour vous permettre delink:../maintain/convert-to-data-only-node.html["convertir un ou plusieurs nœuds de stockage combinés"] qui ne contiennent pas le service ADC dans des nœuds de données uniquement.

`/private/convert-to-data-only-node`

`/private/convert-to-data-only-node/start`

`/private/convert-to-data-only-node/retry`
