---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Avant de mettre à niveau un système StorageGRID, vérifiez que le système est prêt pour la mise à niveau. Vérifiez que le système fonctionne normalement et que tous les nœuds de grid sont opérationnels. 
---
= Vérifier l'état du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau un système StorageGRID, vérifiez que le système est prêt pour la mise à niveau. Vérifiez que le système fonctionne normalement et que tous les nœuds de grid sont opérationnels.

.Étapes
. Connectez-vous au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
. Recherchez et résolvez les alertes actives.
. Confirmez qu'aucune tâche de grille en conflit n'est active ou en attente.
+
.. Sélectionnez *SUPPORT* > *Outils* > *topologie de grille*.
.. Sélectionnez *_site_* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
Les tâches d'évaluation de la gestion du cycle de vie des informations (IDME) sont les seules tâches de grille pouvant être exécutées simultanément avec la mise à niveau logicielle.

.. Si d'autres tâches de grille sont actives ou en attente, attendez qu'elles aient terminé ou lâchés leur verrouillage.
+

NOTE: Contactez le support technique si une tâche ne se termine pas ou ne relâche pas son verrouillage.



. Reportez-vous aux sections link:../network/internal-grid-node-communications.html["Communications internes sur les nœuds de la grille"] et link:../network/external-communications.html["Communications externes"] pour vous assurer que tous les ports requis pour StorageGRID 11.9 sont ouverts avant la mise à niveau.
+

NOTE: Aucun port supplémentaire n'est requis lors de la mise à niveau vers StorageGRID 12.0.


