---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Avant de mettre à niveau un système StorageGRID, vérifiez que le système est prêt pour la mise à niveau. Vérifiez que le système fonctionne normalement et que tous les nœuds de grid sont opérationnels. 
---
= Vérifier l'état du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau un système StorageGRID, vérifiez que le système est prêt pour la mise à niveau. Vérifiez que le système fonctionne normalement et que tous les nœuds de grid sont opérationnels.

.Étapes
. Connectez-vous au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
. Recherchez et résolvez les alertes actives.
. Se référer àlink:../network/internal-grid-node-communications.html["Communications internes sur les nœuds de la grille"] etlink:../network/external-communications.html["Communications externes"] pour vous assurer que tous les ports requis pour StorageGRID 12.0 sont ouverts avant la mise à niveau.
+

NOTE: Aucun port supplémentaire n'est requis lors de la mise à niveau vers StorageGRID 12.0.


