---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Découvrez les conséquences sur votre système StorageGRID lors de la mise à niveau. 
---
= Quel est l'impact de votre système pendant la mise à niveau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les conséquences sur votre système StorageGRID lors de la mise à niveau.



== L'accès SSH externe est autorisé jusqu'à la fin de la mise à niveau

L'accès SSH externe est autorisé pendant la mise à niveau.  Une fois la mise à niveau terminée, l’accès SSH externe est bloqué par défaut.  Après la mise à niveau, vous pouvez utiliser l'onglet *Bloquer SSH* disponible sur la page *Gestionnaire de grille* > *Paramètres de sécurité* pourlink:../admin/manage-external-ssh-access.html["gérer l'accès SSH externe"] .  L'accès SSH entre les nœuds de la grille n'est pas affecté.



== Les mises à niveau de StorageGRID ne générant pas de perturbation

Le système StorageGRID peut ingérer et récupérer les données depuis les applications client tout au long du processus de mise à niveau. Si vous approuvez la mise à niveau de tous les nœuds du même type (par exemple, nœuds de stockage), les nœuds sont arrêtés un par un. Ainsi, il n'y a pas de temps lorsque tous les nœuds de grid ou tous les nœuds de grid d'un certain type sont indisponibles.

Pour assurer une disponibilité continue, vérifiez que votre règle ILM contient des règles qui spécifient le stockage de plusieurs copies de chaque objet. Vous devez également vous assurer que tous les clients S3 externes sont configurés pour envoyer des demandes à l'un des éléments suivants :

* Adresse IP virtuelle d'un groupe haute disponibilité (HA)
* Équilibreur de charge tiers haute disponibilité
* Plusieurs nœuds de passerelle pour chaque client
* Plusieurs nœuds de stockage pour chaque client




== Les applications client peuvent subir des interruptions à court terme

Le système StorageGRID peut ingérer et récupérer des données provenant des applications client tout au long du processus de mise à niveau. Toutefois, les connexions client vers des nœuds de passerelle ou de stockage individuels peuvent être interrompues temporairement si la mise à niveau doit redémarrer des services sur ces nœuds. La connectivité sera restaurée une fois le processus de mise à niveau terminé et les services reprendront sur les nœuds individuels.

Vous devrez peut-être planifier un temps d'indisponibilité pour effectuer une mise à niveau si une perte de connectivité pendant une courte période n'est pas acceptable. Vous pouvez utiliser l'approbation sélective pour planifier la mise à jour de certains nœuds.


NOTE: Vous pouvez utiliser plusieurs passerelles et groupes haute disponibilité pour assurer le basculement automatique lors du processus de mise à niveau. Voir les instructions pour link:../admin/configure-high-availability-group.html["configuration des groupes haute disponibilité"].



== Les réparations en arrière-plan ne s'exécuteront pas sur les grilles avec des nœuds de versions mixtes

Les réparations en arrière-plan ne s'exécutent pas pendant la mise à niveau lorsque la grille contient des nœuds de versions mixtes.  Les incohérences qui surviennent lors d’une panne de site ne seront pas réparées tant que la mise à niveau n’est pas terminée.



== Le micrologiciel de l'appliance est mis à niveau

Pendant la mise à niveau vers StorageGRID 12.0 :

* Tous les nœuds d'appliance StorageGRID sont automatiquement mis à niveau vers la version 12.0 du micrologiciel du programme d'installation de l'appliance StorageGRID .
* Les appareils SG6060 et SGF6024 sont automatiquement mis à niveau vers la version 3B08.EX du micrologiciel du BIOS et la version 4.01.07 du micrologiciel BMC .
* Les appareils SG100 et SG1000 sont automatiquement mis à niveau vers la version 3B13.EC du micrologiciel du BIOS et la version 4.75.07 du micrologiciel BMC .
* Les appareils SGF6112, SG6160, SG110 et SG1100 sont automatiquement mis à niveau vers la version 3A14.QD du micrologiciel BIOS et la version 3.19.07 du micrologiciel BMC .




== Les règles ILM sont gérées différemment en fonction de leur état

* La stratégie active reste la même après la mise à niveau.
* Seules les 10 dernières règles historiques sont conservées lors de la mise à niveau.
* Si une stratégie est proposée, elle sera supprimée lors de la mise à niveau.




== Il est possible que des alertes soient déclenchées

Des alertes peuvent être déclenchées lorsque les services démarrent et s'arrêtent, et lorsque le système StorageGRID fonctionne comme un environnement de version mixte (certains nœuds de grid exécutant une version antérieure, alors que d'autres ont été mis à niveau vers une version plus récente). D'autres alertes peuvent être déclenchées une fois la mise à niveau terminée.

Par exemple, vous pouvez voir l'alerte *Impossible de communiquer avec le nœud* lorsque les services sont arrêtés, ou vous pouvez voir l'alerte *Erreur de communication Cassandra* lorsque certains nœuds ont été mis à niveau vers StorageGRID 12.0 mais que d'autres nœuds exécutent toujours StorageGRID 11.9.  En général, ces alertes disparaissent une fois la mise à niveau terminée.

L'alerte *Placement ILM impossible* peut être déclenchée lorsque les nœuds de stockage sont arrêtés pendant la mise à niveau vers StorageGRID 12.0.  Cette alerte peut persister pendant 1 jour après la fin de la mise à niveau.

Une fois la mise à niveau terminée, vous pouvez consulter toutes les alertes liées à la mise à niveau en sélectionnant *alertes récemment résolues* ou *alertes actuelles* dans le tableau de bord de Grid Manager.



== Les modifications de configuration sont restreintes


NOTE: Cette liste s'applique spécifiquement aux mises à niveau de StorageGRID 11.9 vers StorageGRID 12.0.  Si vous effectuez une mise à niveau vers une autre version de StorageGRID , reportez-vous à la liste des modifications restreintes dans les instructions de mise à niveau de cette version.

Jusqu'à la fin de la tâche *Activer la nouvelle fonction* :

* N'apportez aucune modification à la configuration de la grille.
* N'activez ou ne désactivez aucune nouvelle fonctionnalité.
* Ne mettez pas à jour la configuration ILM. Sinon, vous risquez d'avoir un comportement ILM incohérent et inattendu.
* N'appliquez pas de correctif ou ne restaurez pas de nœud de grille.
+

NOTE: Contactez le support technique si vous avez besoin de restaurer un nœud pendant la mise à niveau.

* Vous ne devez pas gérer les groupes HA, les interfaces VLAN ou les points de terminaison d'équilibrage de charge pendant la mise à niveau vers StorageGRID 12.0.
* Ne supprimez aucun groupe HA tant que la mise à niveau vers StorageGRID 12.0 n'est pas terminée.  Les adresses IP virtuelles dans d’autres groupes HA peuvent devenir inaccessibles.


Jusqu'à la fin de la tâche *étapes de mise à niveau finale* :

* N'effectuez pas de procédure d'extension.
* N'effectuez pas de procédure de mise hors service.

