---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: storagegrid software upgrade 
summary: Suivez ces instructions pour mettre à niveau un système StorageGRID vers une nouvelle version. 
---
= Mettez à niveau le logiciel StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces instructions pour mettre à niveau un système StorageGRID vers une nouvelle version.

Lorsque vous effectuez la mise à niveau, tous les nœuds de votre système StorageGRID sont mis à niveau.


CAUTION: Ne démarrez pas la mise à niveau si vous avez un besoin urgent d’étendre votre stockage pour augmenter la capacité (si votre stockage est presque plein).  Terminez la procédure de mise à niveau en temps opportun.  Si une récupération est nécessaire, contactez le support technique.



[[before-you-upgrade]]
== Avant de procéder à la mise à niveau

Consultez ces rubriques pour découvrir les nouvelles fonctionnalités et améliorations de StorageGRID 12.1, déterminer si certaines fonctionnalités ont été dépréciées ou supprimées et vous renseigner sur les modifications apportées aux API StorageGRID.

* link:how-your-system-is-affected-during-upgrade.html["Quel est l'impact de votre système pendant la mise à niveau"]
* link:../release-notes/whats-new.html["Nouveautés de StorageGRID 12.1"]
* link:../release-notes/removed-or-deprecated-features.html["Fonctions supprimées ou obsolètes"]
* link:../release-notes/changes-to-grid-management-api.html["Modifications apportées à l'API de gestion du grid"]
* link:../release-notes/changes-to-tenant-management-api.html["Modifications apportées à l'API de gestion des locataires"]

