---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Avant de démarrer la mise à niveau, vérifiez que la version précédente de StorageGRID est actuellement installée avec le dernier correctif disponible appliqué. 
---
= Vérifier la version installée de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de démarrer la mise à niveau, vérifiez que la version précédente de StorageGRID est actuellement installée avec le dernier correctif disponible appliqué.

.Description de la tâche
Avant de procéder à la mise à niveau vers StorageGRID 12.0, votre grille doit avoir StorageGRID 11.9.0.8 ou une version ultérieure installée.  Si vous utilisez actuellement une version antérieure de StorageGRID, vous devez installer tous les fichiers de mise à niveau précédents ainsi que leurs derniers correctifs (fortement recommandé) jusqu'à ce que la version actuelle de votre grille soit au moins StorageGRID 11.9.0.8.

Un chemin de mise à niveau possible est indiqué dans le <<example-upgrade-path,exemple>>.


CAUTION: NetApp vous recommande fortement d'appliquer le dernier correctif pour chaque version de StorageGRID avant de procéder à la mise à niveau vers la version suivante et d'appliquer également le dernier correctif pour chaque nouvelle version que vous installez.  Dans certains cas, vous devez appliquer un correctif pour éviter le risque de perte de données.  Se référer à https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Téléchargement NetApp : StorageGRID"^] et les notes de publication de chaque correctif pour en savoir plus.



== Vérifier la version installée

.Étapes
. Connectez-vous au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
. Dans le haut du Gestionnaire de grille, sélectionnez *aide* > *About*.
. Vérifiez que la *Version* est 11.9.0.8 ou une version ultérieure.
. Si la *Version* n'est pas 11.9.0.8 ou une version ultérieure, accédez à https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Téléchargement NetApp : StorageGRID"^] pour télécharger les fichiers de mise à niveau et de correctifs dont vous avez besoin.
. link:../upgrade/index.html["Suivez les instructions de mise à niveau"]pour chaque version que vous avez téléchargée. link:../maintain/storagegrid-hotfix-procedure.html["Appliquer le dernier correctif"] pour chaque version (fortement recommandé).


Reportez-vous à l’exemple de mise à niveau suivant.



== [[example-upgrade-path]]Exemple : Mise à niveau vers StorageGRID 12.0 à partir de la version 11.8

L'exemple suivant montre les étapes de mise à niveau de StorageGRID version 11.8 vers la version 11.9 en préparation d'une mise à niveau vers StorageGRID 12.0.

Téléchargez et installez le logiciel dans l'ordre suivant pour préparer votre système à la mise à niveau :

. Mise à niveau vers la version majeure de StorageGRID 11.8.0.
. Appliquez le dernier correctif StorageGRID 11.8.0._y_.
. Mise à niveau vers la version majeure de StorageGRID 11.9.0.
. Appliquez le correctif StorageGRID 11.9.0.8 ou version ultérieure.

