---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: Cette version de StorageGRID présente les fonctionnalités et modifications fonctionnelles suivantes. 
---
= Nouveautés d'StorageGRID 12.0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette version de StorageGRID présente les fonctionnalités et modifications fonctionnelles suivantes.



== Réplication entre les grid avec S3 Object Lock

Vous pouvez configurer la réplication entre les compartiments avec S3 Object Lock activé. Reportez-vous à la link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["Réplication entre les grid avec S3 Object Lock"].

NetApp recommande d'utiliser cette fonctionnalité uniquement entre les compartiments source et de destination StorageGRID 12.0. Cependant, cette fonctionnalité est prise en charge entre les compartiments source StorageGRID 11.9 avec verrouillage d'objet S3 désactivé et les compartiments de destination StorageGRID 12.0 avec verrouillage d'objet S3 activé.



== Sécurité



=== Amélioration de la sécurité des mots de passe cryptés sur disque

Amélioration de la sécurité des mots de passe, y compris un nombre de hachage très élevé pour les hachages de mots de passe SHA512.



== Compartiments S3



=== Compartiments de dérivation

Vous pouvez maintenant link:../tenant/manage-branch-bucket-html["créer des compartiments de branchement"] accéder à un compartiment S3. Un compartiment de succursale permet d'accéder aux objets du compartiment S3 tels qu'ils existaient à un moment donné. Un compartiment de succursale n'est pas identique à une sauvegarde.



== Interface utilisateur



=== Thème sombre

Les paramètres de thème sombre et de thème système sont disponibles dans le menu utilisateur du Gestionnaire de grille et du Gestionnaire de locataires.



== Améliorations de Grid Manager



=== Configurer l'amélioration des régions

La page régions du Gestionnaire de grille comprend désormais un onglet *région par défaut*. Vous pouvez utiliser cet onglet pour modifier la région par défaut définie pour les compartiments S3. link:../ilm/configuring-regions-optional-and-s3-only.html["En savoir plus >>"].
