---
permalink: ubuntu/automating-installation.html 
sidebar: sidebar 
keywords: how to automate ubuntu or debian installation 
summary: 'Vous pouvez automatiser l"installation du service hôte StorageGRID et la configuration des nœuds grid.' 
---
= Automatisation de l'installation (Ubuntu ou Debian)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez automatiser l'installation du service hôte StorageGRID et la configuration des nœuds grid.

.Description de la tâche
L'automatisation du déploiement peut être utile dans les cas suivants :

* Vous utilisez déjà un framework d'orchestration standard, comme Ansible, Puppet ou Chef, pour déployer et configurer des hôtes physiques ou virtuels.
* Vous prévoyez de déployer plusieurs instances StorageGRID.
* Vous déployez une instance StorageGRID vaste et complexe.


Le service hôte StorageGRID est installé par un package et piloté par des fichiers de configuration qui peuvent être créés de manière interactive lors d'une installation manuelle, ou préparés à l'avance (ou par programmation) pour permettre l'installation automatisée à l'aide des frameworks d'orchestration standard. StorageGRID propose des scripts Python en option pour l'automatisation de la configuration des appliances StorageGRID et de l'ensemble du système StorageGRID (la « grille »). Vous pouvez utiliser ces scripts directement, ou bien les inspecter pour apprendre à utiliser l'API REST d'installation StorageGRID dans les outils de déploiement et de configuration de grid que vous développez vous-même.



== Automatisez l'installation et la configuration du service d'hôte StorageGRID

Vous pouvez automatiser l'installation du service hôte StorageGRID à l'aide des frameworks d'orchestration standard tels qu'Ansible, Puppet, Chef, Fabric ou SaltStack.

Le service hôte StorageGRID est fourni dans un DEO et est piloté par des fichiers de configuration prêts à l'avance (ou par programmation) pour permettre une installation automatisée. Si vous utilisez déjà une infrastructure d'orchestration standard pour installer et configurer Ubuntu ou Debian, l'ajout de StorageGRID à vos playbooks ou à vos recettes doit être simple.

Vous pouvez automatiser ces tâches :

. Installation de Linux
. Configuration de Linux
. Configuration des interfaces réseau de l'hôte pour répondre aux exigences StorageGRID
. Configuration du stockage de l'hôte pour répondre aux exigences StorageGRID
. Installation de Docker
. Installation du service hôte StorageGRID
. Création de fichiers de configuration de nœud StorageGRID dans `/etc/storagegrid/nodes`
. Validation des fichiers de configuration de nœuds StorageGRID
. Démarrage du service hôte StorageGRID




=== Exemple de rôle et de PlayBook Ansible

Un exemple de rôle Ansible et de PlayBook sont fournis avec l'archive d'installation dans le `/extras` dossier. Ce PlayBook explique comment le `storagegrid` rôle prépare les hôtes et installe StorageGRID sur les serveurs cibles. Vous pouvez personnaliser le rôle ou le PlayBook selon vos besoins.



== Automatiser la configuration de StorageGRID

Une fois les nœuds grid déployés, vous pouvez automatiser la configuration du système StorageGRID.

.Avant de commencer
* Vous connaissez l'emplacement des fichiers suivants à partir de l'archive d'installation.
+
[cols="1a,1a"]
|===
| Nom du fichier | Description 


| configure-storagegrid.py  a| 
Script Python utilisé pour automatiser la configuration



| configurez-storagegrid.sample.json  a| 
Exemple de fichier de configuration à utiliser avec le script



| configurez-storagegrid.blank.json  a| 
Fichier de configuration vierge à utiliser avec le script

|===
* Vous avez créé un `configure-storagegrid.json` fichier de configuration. Pour créer ce fichier, vous pouvez modifier l'exemple de fichier de configuration (`configure-storagegrid.sample.json`) ou le fichier de configuration vide (`configure-storagegrid.blank.json`).



CAUTION: Stockez le mot de passe de gestion et le mot de passe de provisionnement dans la section mots de passe du fichier de configuration modifié `configure-storagegrid.json`, dans un emplacement sécurisé. Ces mots de passe sont requis pour les procédures d'installation, d'extension et de maintenance. Vous devez également sauvegarder le fichier de configuration modifié `configure-storagegrid.json` et le stocker dans un emplacement sécurisé.

.Description de la tâche
Vous pouvez utiliser `configure-storagegrid.py` le script Python et le `configure-storagegrid.json` fichier de configuration pour automatiser la configuration de votre système StorageGRID.


NOTE: Vous pouvez également configurer le système à l'aide de Grid Manager ou de l'API d'installation.

.Étapes
. Connectez-vous à la machine Linux que vous utilisez pour exécuter le script Python.
. Accédez au répertoire dans lequel vous avez extrait l'archive d'installation.
+
Par exemple :

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
où `platform` est `debs`, , `rpms` ou `vsphere`.

. Exécutez le script Python et utilisez le fichier de configuration que vous avez créé.
+
Par exemple :

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Résultat
Un fichier de package de récupération `.zip` est généré pendant le processus de configuration et est téléchargé dans le répertoire où vous exécutez le processus d'installation et de configuration. Vous devez sauvegarder le fichier du package de restauration afin de pouvoir restaurer le système StorageGRID en cas de défaillance d'un ou plusieurs nœuds de grid. Par exemple, copiez-le dans un emplacement sécurisé, sauvegardé sur le réseau et dans un emplacement de stockage cloud sécurisé.


CAUTION: Le fichier de package de récupération doit être sécurisé car il contient des clés de cryptage et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID.

Si vous avez indiqué que des mots de passe aléatoires doivent être générés, ouvrez le `Passwords.txt` fichier et recherchez les mots de passe requis pour accéder à votre système StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Votre système StorageGRID est installé et configuré lorsqu'un message de confirmation s'affiche.

[listing]
----
StorageGRID has been configured and installed.
----
.Informations associées
link:overview-of-installation-rest-api.html["Installation de l'API REST"]
