---
permalink: harden/hardening-guidelines-for-storagegrid-nodes.html 
sidebar: sidebar 
keywords: hardening guidelines, nodes, security 
summary: 'Les nœuds StorageGRID peuvent être déployés sur des machines virtuelles VMware, au sein d"un moteur de conteneurs sur des hôtes Linux, ou en tant qu"appliances matérielles dédiées. Chaque type de plateforme et chaque type de nœud dispose de ses propres pratiques de renforcement.' 
---
= Instructions de renforcement pour les nœuds StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les nœuds StorageGRID peuvent être déployés sur des machines virtuelles VMware, au sein d'un moteur de conteneurs sur des hôtes Linux, ou en tant qu'appliances matérielles dédiées. Chaque type de plateforme et chaque type de nœud dispose de ses propres pratiques de renforcement.



== [[block-remote-ipmi]]Contrôler l'accès IPMI à distance au BMC

Vous pouvez activer ou désactiver l'accès IPMI à distance pour tous les dispositifs contenant un contrôleur BMC. L'interface IPMI distante permet à toute personne disposant d'un compte BMC et d'un mot de passe d'accéder à votre matériel de bas niveau à vos appliances StorageGRID. Si vous n'avez pas besoin d'un accès IPMI à distance au contrôleur BMC, désactivez cette option.

* Pour contrôler l'accès IPMI à distance au BMC dans Grid Manager, accédez à *Configuration* > *Sécurité* > *Paramètres de sécurité* > *Appliances* :
+
** Décochez la case *Activer l'accès IPMI distant* pour désactiver l'accès IPMI au contrôleur BMC.
** Cochez la case *Activer l'accès IPMI distant* pour activer l'accès IPMI au contrôleur BMC.




Pour plus d'informations sur le renforcement du BMC , consultez le https://media.defense.gov/2023/Jun/14/2003241405/-1/-1/0/CSI_HARDEN_BMCS.PDF["Contrôleurs de gestion de la carte mère Harden"^] fiche d'information sur la cybersécurité du https://www.nsa.gov/["Agence de sécurité nationale (NSA)"^] et https://www.cisa.gov/["Agence de cybersécurité et de sécurité des infrastructures (CISA)"^] .



== Configuration du pare-feu

Dans le cadre du processus de renforcement du système, vous devez examiner les configurations de pare-feu externes et les modifier afin que le trafic soit accepté uniquement à partir des adresses IP et sur les ports à partir desquels il est strictement nécessaire.

StorageGRID comprend un pare-feu interne sur chaque nœud qui améliore la sécurité de votre grille en vous permettant de contrôler l'accès réseau au nœud. Vous devez link:../admin/manage-firewall-controls.html["gérer les contrôles de pare-feu internes"]empêcher l'accès au réseau sur tous les ports, à l'exception de ceux nécessaires à votre déploiement de grid spécifique. Les modifications de configuration effectuées sur la page de contrôle du pare-feu sont déployées sur chaque nœud.

Plus précisément, vous pouvez gérer les domaines suivants :

* *Adresses privilégiées* : vous pouvez autoriser certaines adresses IP ou sous-réseaux à accéder aux ports fermés par les paramètres de l'onglet gérer l'accès externe.
* *Gérer l'accès externe* : vous pouvez fermer les ports ouverts par défaut ou rouvrir les ports précédemment fermés.
* *Réseau client non approuvé* : vous pouvez spécifier si un nœud approuve le trafic entrant provenant du réseau client ainsi que les ports supplémentaires que vous souhaitez ouvrir lorsque le réseau client non approuvé est configuré.


Bien que ce pare-feu interne offre une couche supplémentaire de protection contre certaines menaces courantes, il ne supprime pas la nécessité d'un pare-feu externe.

Pour une liste de tous les ports internes et externes utilisés par StorageGRID, voirlink:../network/internal-grid-node-communications.html#storagegrid-internal-ports["Ports internes StorageGRID"] etlink:../network/external-communications.html#ports-used-for-external-communications["Ports utilisés pour les communications externes"] .



== Désactiver les services inutilisés

Pour tous les nœuds StorageGRID , vous devez désactiver ou bloquer l’accès aux services inutilisés.  Par exemple, si vous ne prévoyez pas d’utiliser DHCP, utilisez le gestionnaire de grille pour fermer le port 68.  Sélectionnez *Configuration* > *Contrôle du pare-feu* > *Gérer l'accès externe*.  Modifiez ensuite le statut du port 68 de *Ouvert* à *Fermé*.



== Virtualisation, conteneurs et matériel partagé

Pour tous les nœuds StorageGRID, évitez d'exécuter StorageGRID sur le même matériel physique que les logiciels non fiables. Ne supposez pas que les protections de l'hyperviseur empêchent les logiciels malveillants d'accéder aux données protégées par StorageGRID si StorageGRID et le logiciel malveillant existent sur le même matériel physique. Par exemple, les attaques Meltdown et Specter exploitent des vulnérabilités critiques dans les processeurs modernes et permettent aux programmes de voler des données en mémoire sur le même ordinateur.



== Protéger les nœuds pendant l'installation

N'autorisez pas les utilisateurs non approuvés à accéder aux nœuds StorageGRID sur le réseau lors de l'installation des nœuds. Les nœuds ne sont pas entièrement sécurisés tant qu'ils n'ont pas rejoint la grille.



== Limiter l'accès physique au matériel

Vous devez limiter l'accès physique aux nœuds de l'appliance matérielle StorageGRID ainsi qu'aux hôtes de machines virtuelles VMware et aux hôtes Linux exécutant StorageGRID aux seuls administrateurs autorisés.  Certains exemples de contrôles d’accès physiques comprennent les serrures, les gardes, les barrières physiques et la vidéosurveillance.

Les nœuds d’appareils matériels sont conçus pour être installés et exploités uniquement par des administrateurs autorisés.  N'autorisez pas les administrateurs non autorisés à accéder aux nœuds de l'appliance matérielle.



== Instructions pour les nœuds d'administration

Des nœuds d'administration qui assurent les services de gestion tels que la configuration du système, la surveillance et la journalisation. Lorsque vous vous connectez à Grid Manager ou au Gestionnaire de locataires, vous vous connectez à un noeud d'administration.

Suivez les instructions suivantes pour sécuriser les nœuds d'administration dans votre système StorageGRID :

* Sécurisez tous les nœuds d'administration des clients non fiables, tels que ceux qui sont sur Internet ouvert. Assurez-vous qu'aucun client non approuvé ne peut accéder à un nœud d'administration sur le réseau Grid, le réseau d'administration ou le réseau client.
* Les groupes StorageGRID contrôlent l'accès aux fonctionnalités de Grid Manager et de tenant Manager. Accordez à chaque groupe d'utilisateurs les autorisations minimales requises pour leur rôle et utilisez le mode d'accès en lecture seule pour empêcher les utilisateurs de modifier la configuration.
* Lorsque vous utilisez des terminaux d'équilibrage de charge StorageGRID, utilisez des nœuds de passerelle au lieu des nœuds d'administration pour le trafic client non fiable.
* Si vous avez des locataires non approuvés, ne les autorisez pas à avoir un accès direct au gestionnaire de locataires ou à l'API de gestion des locataires. Certains locataires non fiables utilisent un portail de locataires ou un système de gestion externe des locataires qui interagit avec l'API de gestion des locataires.
* Vous pouvez également utiliser un proxy d'administration pour davantage de contrôle sur la communication AutoSupport entre les nœuds d'administration et le support NetApp. Voir les étapes pour link:../admin/configuring-admin-proxy-settings.html["création d'un proxy d'administration"].
* Utilisez éventuellement les ports 8443 et 9443 restreints pour séparer les communications Grid Manager et tenant Manager. Bloquez le port partagé 443 et limitez les demandes des locataires au port 9443 pour une protection supplémentaire.
* La possibilité d'utiliser des nœuds d'administration distincts pour les administrateurs du grid et les utilisateurs des locataires.


Pour plus d'informations, reportez-vous aux instructions link:../admin/index.html["Administration d'StorageGRID"]de .



== Consignes relatives aux nœuds de stockage

Des nœuds de stockage gèrent et stockent les données et les métadonnées d'objets. Suivez ces instructions pour sécuriser les nœuds de stockage dans votre système StorageGRID.

* Ne permettez pas aux clients non approuvés de se connecter directement aux nœuds de stockage. Utilisez un terminal d'équilibrage de charge desservi par un nœud de passerelle ou un équilibreur de charge tiers.
* N'activez pas les services sortants pour les locataires non approuvés. Par exemple, lors de la création du compte pour un locataire non approuvé, n'autorisez pas le locataire à utiliser son propre référentiel d'identité et n'autorisez pas l'utilisation des services de plate-forme. Voir les étapes pour link:../admin/creating-tenant-account.html["création d'un compte de locataire"].
* Utilisez un équilibreur de charge tiers pour le trafic client non fiable. L'équilibrage de la charge fourni par des tiers offre un meilleur contrôle et des couches de protection supplémentaires contre les attaques.
* Vous pouvez également utiliser un proxy de stockage pour davantage de contrôle sur les pools de stockage cloud et la communication des services de plateforme depuis les nœuds de stockage vers les services externes. Voir les étapes pour link:../admin/configuring-storage-proxy-settings.html["création d'un proxy de stockage"].
* En option, connectez-vous à des services externes à l'aide du réseau client.  Ensuite, sélectionnez *Configuration* > *Sécurité* > *Contrôle du pare-feu* > *Réseaux clients non approuvés* et indiquez que le réseau client sur le nœud de stockage n'est pas approuvé.  Le nœud de stockage n'accepte plus aucun trafic entrant sur le réseau client, mais il continue d'autoriser les demandes sortantes pour les services de plate-forme.




== Instructions pour les nœuds de passerelle

Les nœuds de passerelle fournissent une interface d'équilibrage de la charge facultative que les applications client peuvent utiliser pour se connecter à StorageGRID. Pour sécuriser tous les nœuds de passerelle de votre système StorageGRID, procédez comme suit :

* Configurez et utilisez des terminaux d'équilibrage de charge. Voir link:../admin/managing-load-balancing.html["Considérations relatives à l'équilibrage de charge"].
* Utilisez un équilibreur de charge tiers entre le client et le nœud de passerelle ou les nœuds de stockage pour le trafic client non fiable. L'équilibrage de la charge fourni par des tiers offre un meilleur contrôle et des couches de protection supplémentaires contre les attaques. Si vous utilisez un équilibreur de charge tiers, le trafic réseau peut, éventuellement, être configuré de manière à passer par un terminal interne d'équilibrage de la charge ou être directement envoyé aux nœuds de stockage.
* Si vous utilisez des points de terminaison d'équilibrage de charge, vous pouvez éventuellement demander aux clients de se connecter via le réseau client.  Ensuite, sélectionnez *Configuration* > *Sécurité* > *Contrôle du pare-feu* > *Réseaux clients non approuvés* et indiquez que le réseau client sur le nœud de passerelle n'est pas approuvé.  Le nœud de passerelle accepte uniquement le trafic entrant sur les ports explicitement configurés comme points de terminaison d'équilibrage de charge.




== Consignes pour les nœuds d'appliances matérielles

Les appliances matérielles StorageGRID sont spécialement conçues pour une utilisation dans un système StorageGRID. Certaines appliances peuvent être utilisées comme nœuds de stockage. Les autres appliances peuvent être utilisées comme nœuds d'administration ou nœuds de passerelle. Vous pouvez associer des nœuds d'appliance à des nœuds basés sur logiciel ou déployer des grilles 100 % appliance entièrement conçues.

Pour sécuriser les nœuds d'appliance matérielle de votre système StorageGRID, procédez comme suit :

* Si l'appliance utilise SANtricity System Manager pour la gestion du contrôleur de stockage, empêchez les clients non fiables d'accéder à SANtricity System Manager sur le réseau.
* Si l'appareil dispose d'un contrôleur de gestion de la carte mère (BMC), sachez que le port de gestion BMC permet un accès matériel de bas niveau.  Connectez le port de gestion BMC uniquement à un réseau de gestion interne sécurisé et fiable.
+
Vous pouvez établir un VLAN pour isoler les connexions réseau BMC et restreindre l'accès Internet BMC aux réseaux approuvés.  Pour plus d'informations sur l'application de la séparation VLAN, consultez le https://media.defense.gov/2023/Jun/14/2003241405/-1/-1/0/CSI_HARDEN_BMCS.PDF["Contrôleurs de gestion de la carte mère Harden"^] fiche d'information sur la cybersécurité du https://www.nsa.gov/["Agence de sécurité nationale (NSA)"^] et https://www.cisa.gov/["Agence de cybersécurité et de sécurité des infrastructures (CISA)"^] .

+
Si un réseau de gestion interne sécurisé et fiable n'est pas disponible, laissez le port de gestion BMC déconnecté ou bloqué.  Le support technique peut demander un accès temporaire pendant une demande d'assistance.

* Si l'appliance prend en charge la gestion à distance du matériel du contrôleur via Ethernet à l'aide de la norme IPMI (Intelligent Platform Management interface), bloquez le trafic non fiable sur le port 623.



NOTE: Vous pouvez activer ou désactiver l'accès IPMI à distance pour tous les appareils contenant un BMC.  L'interface IPMI distante permet l'accès matériel de bas niveau à vos appliances StorageGRID par toute personne disposant d'un compte BMC et d'un mot de passe.  Si vous n'avez pas besoin d'un accès IPMI à distance au BMC, désactivez cette option à l'aide de l'une des méthodes suivantes : + Dans Grid Manager, accédez à *Configuration* > *Sécurité* > *Paramètres de sécurité* > *Appliances* et décochez la case *Activer l'accès IPMI à distance*.  + Dans l'API de gestion de grille, utilisez le point de terminaison privé : `PUT /private/bmc` .

+ Vous pouvez également<<block-remote-ipmi,désactiver l'accès IPMI à distance>> .

* Pour les modèles d'appliance contenant des disques SED, FDE ou NL-SAS FIPS que vous gérez avec SANtricity System Manager https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/accessing-and-configuring-santricity-system-manager.html["Activez et configurez la sécurité des lecteurs SANtricity"^].
* Pour les modèles d'appareils contenant des SSD NVMe SED ou FIPS que vous gérez à l'aide du programme d'installation de l'appareil StorageGRID et du gestionnaire de grille, https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html#enable-drive-encryption["Activez et configurez le chiffrement de lecteur StorageGRID"^] .
* Pour les appareils sans lecteurs SED, FDE ou FIPS, utilisez un serveur de gestion de clés (KMS) pour https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html#enable-node-encryption["activer et configurer le chiffrement du nœud logiciel StorageGRID"^] .


.Informations associées
https://docs.netapp.com/us-en/e-series-santricity/sm-settings/overview-drive-security.html["En savoir plus sur la sécurité des lecteurs dans SANtricity System Manager"^]
