---
permalink: network/external-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, external communications, ports, TCP, UDP, client communications 
summary: Les clients doivent communiquer avec les nœuds du grid pour ingérer et récupérer le contenu. Les ports utilisés dépendent des protocoles de stockage objet choisis. Ces ports doivent être accessibles au client. 
---
= Communications externes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les clients doivent communiquer avec les nœuds du grid pour ingérer et récupérer le contenu. Les ports utilisés dépendent des protocoles de stockage objet choisis. Ces ports doivent être accessibles au client.



== Accès restreint aux ports

Si les stratégies de mise en réseau d'entreprise limitent l'accès à l'un des ports, vous pouvez effectuer l'une des opérations suivantes :

* link:../admin/configuring-load-balancer-endpoints.html["terminaux d'équilibrage de charge"]Permet d'autoriser l'accès aux ports définis par l'utilisateur.
* Remap les ports lors du déploiement des nœuds. Toutefois, vous ne devez pas remapper les terminaux de l'équilibreur de charge. Pour plus d'informations sur le remappage des ports pour votre nœud StorageGRID, reportez-vous aux sections suivantes :



NOTE: La prise en charge du remappage des ports est obsolète et sera supprimée dans une prochaine version. Pour supprimer les ports remappés, reportez-vous àlink:../maintain/removing-port-remaps.html["Supprimer les remappages de ports sur les appliances StorageGRID"] oulink:../maintain/removing-port-remaps-on-bare-metal-hosts.html["Supprimez les mappes de ports sur les hôtes bare Metal"] .

* link:../swnodes/creating-node-configuration-files.html["Clés de remap de port pour StorageGRID sur Red Hat Enterprise Linux"]
* link:../swnodes/deploying-storagegrid-node-as-virtual-machine.html#vmware-remap-ports["Remappez les ports pour StorageGRID sur VMware"]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["Facultatif : remappage des ports réseau pour l'appliance"^]




== Ports utilisés pour les communications externes

Le tableau suivant indique les ports utilisés pour le trafic dans les nœuds.


NOTE: Cette liste n'inclut pas les ports qui peuvent être configurés comme link:../admin/configuring-load-balancer-endpoints.html["terminaux d'équilibrage de charge"].

[cols="1a,1a,1a,1a,1a,4a"]
|===
| Port | TCP ou UDP | Protocole | De | À | Détails 


 a| 
25
 a| 
TCP
 a| 
SMTP
 a| 
Nœuds d'administration
 a| 
Serveur de messagerie
 a| 
Utilisé pour les alertes et l'adresse AutoSupport basée sur des e-mails. Vous pouvez remplacer le paramètre de port par défaut de 25 à l'aide de la page serveurs de messagerie.



 a| 
53
 a| 
TCP/UDP
 a| 
DNS
 a| 
Tous les nœuds
 a| 
Serveurs DNS
 a| 
Utilisé pour DNS.



 a| 
67
 a| 
UDP
 a| 
DHCP
 a| 
Tous les nœuds
 a| 
Service DHCP
 a| 
Permet de prendre en charge la configuration réseau basée sur DHCP. Le service dhclient ne fonctionne pas pour les grilles configurées de façon statique.



 a| 
68
 a| 
UDP
 a| 
DHCP
 a| 
Service DHCP
 a| 
Tous les nœuds
 a| 
Permet de prendre en charge la configuration réseau basée sur DHCP. Le service dhclient ne s'exécute pas pour les grilles qui utilisent des adresses IP statiques.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Navigateur
 a| 
Nœuds d'administration
 a| 
Le port 80 redirige vers le port 443 pour l'interface utilisateur du nœud d'administration.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Navigateur
 a| 
Appliances
 a| 
Le port 80 redirige vers le port 8443 du programme d'installation de l'appliance StorageGRID.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Nœuds de stockage avec ADC
 a| 
AWS
 a| 
Utilisé pour les messages de services de plateforme envoyés à AWS ou à d'autres services externes utilisant HTTP. Les locataires peuvent remplacer le paramètre de port HTTP par défaut de 80 lors de la création d'un noeud final.



 a| 
80
 a| 
TCP
 a| 
HTTP
 a| 
Nœuds de stockage
 a| 
AWS
 a| 
Les demandes de pools de stockage cloud sont envoyées aux cibles AWS qui utilisent HTTP. Les administrateurs du grid peuvent remplacer le paramètre de port HTTP par défaut de 80 lors de la configuration d'un pool de stockage cloud.



 a| 
123
 a| 
UDP
 a| 
NTP
 a| 
Nœuds NTP principaux
 a| 
NTP externe
 a| 
Service de protocole de temps de réseau. Les nœuds sélectionnés comme sources NTP principales synchronisent également les heures d'horloge avec les sources d'heure NTP externes.



 a| 
161
 a| 
TCP/UDP
 a| 
SNMP
 a| 
Client SNMP
 a| 
Tous les nœuds
 a| 
Utilisé pour l'interrogation SNMP. Tous les nœuds fournissent des informations de base ; les nœuds d'administration fournissent également des données d'alerte. Le port UDP 161 est défini par défaut lorsqu'il est configuré.

*Remarque :* ce port n'est nécessaire que, et n'est ouvert que sur le pare-feu de nœud si SNMP est configuré. Si vous prévoyez d'utiliser SNMP, vous pouvez configurer d'autres ports.

*Remarque :* pour plus d'informations sur l'utilisation de SNMP avec StorageGRID, contactez votre ingénieur commercial NetApp.



 a| 
162
 a| 
TCP/UDP
 a| 
Notifications SNMP
 a| 
Tous les nœuds
 a| 
Destinations de notification
 a| 
Notifications et interruptions SNMP sortantes par défaut au port UDP 162.

*Remarque :* ce port n'est requis que si SNMP est activé et que les destinations de notification sont configurées. Si vous prévoyez d'utiliser SNMP, vous pouvez configurer d'autres ports.

*Remarque :* pour plus d'informations sur l'utilisation de SNMP avec StorageGRID, contactez votre ingénieur commercial NetApp.



 a| 
389
 a| 
TCP/UDP
 a| 
LDAP
 a| 
Nœuds de stockage avec ADC
 a| 
Active Directory/LDAP
 a| 
Utilisé pour la connexion à un serveur Active Directory ou LDAP pour la fédération des identités.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigateur
 a| 
Nœuds d'administration
 a| 
Utilisé par les navigateurs Web et les clients API de gestion pour accéder à Grid Manager et tenant Manager.

*Remarque* : si vous fermez les ports Grid Manager 443 ou 8443, tous les utilisateurs actuellement connectés sur un port bloqué, y compris vous, perdront l'accès à Grid Manager à moins que leur adresse IP n'ait été ajoutée à la liste d'adresses privilégiées. Reportez-vous  à la section link:../admin/configure-firewall-controls.html["Configurer les contrôles de pare-feu"] pour configurer des adresses IP privilégiées.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nœuds d'administration
 a| 
Active Directory
 a| 
Utilisé par les nœuds d'administration se connectant à Active Directory si l'authentification unique (SSO) est activée.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nœuds de stockage avec ADC
 a| 
AWS
 a| 
Utilisé pour les messages de services de plateforme envoyés à AWS ou à d'autres services externes utilisant HTTPS. Les locataires peuvent remplacer le paramètre de port HTTP par défaut de 443 lors de la création d'un noeud final.



 a| 
443
 a| 
TCP
 a| 
HTTPS
 a| 
Nœuds de stockage
 a| 
AWS
 a| 
Les demandes de pools de stockage cloud sont envoyées aux cibles AWS qui utilisent HTTPS. Les administrateurs du grid peuvent remplacer le paramètre de port HTTPS par défaut de 443 lors de la configuration d'un pool de stockage cloud.



 a| 
5353
 a| 
UDP
 a| 
MDNS
 a| 
Tous les nœuds
 a| 
Tous les nœuds
 a| 
Fournit le service DNS multidiffusion (mDNS) utilisé pour les modifications d'IP de grille complète et pour la découverte du nœud d'administration principal pendant l'installation, l'extension et la récupération.



 a| 
5696
 a| 
TCP
 a| 
KMIP
 a| 
Appliance
 a| 
KM
 a| 
Trafic externe KMIP (Key Management Interoperability Protocol) depuis les appliances configurées pour le chiffrement des nœuds vers le serveur de gestion des clés (KMS), sauf si un autre port est spécifié sur la page de configuration KMS du programme d'installation de l'appliance StorageGRID.



 a| 
8443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigateur
 a| 
Nœuds d'administration
 a| 
Facultatif. Utilisé par les navigateurs Web et les clients API de gestion pour accéder à Grid Manager. Peut être utilisé pour séparer les communications Grid Manager et tenant Manager.

*Remarque* : si vous fermez les ports Grid Manager 443 ou 8443, tous les utilisateurs actuellement connectés sur un port bloqué, y compris vous, perdront l'accès à Grid Manager à moins que leur adresse IP n'ait été ajoutée à la liste d'adresses privilégiées. Reportez-vous  à la section link:../admin/configure-firewall-controls.html["Configurer les contrôles de pare-feu"] pour configurer des adresses IP privilégiées.



 a| 
9022
 a| 
TCP
 a| 
SSH
 a| 
L'ordinateur portable de service
 a| 
Appliances
 a| 
Permet d'accéder aux appliances StorageGRID en mode préconfiguration pour le support et le dépannage. Ce port n'est pas nécessaire pour être accessible entre des nœuds grid ou pendant les opérations normales.



 a| 
9091
 a| 
TCP
 a| 
HTTPS
 a| 
Service externe Grafana
 a| 
Nœuds d'administration
 a| 
Utilisés par les services Grafana externes pour sécuriser l'accès au service StorageGRID Prometheus.

*Remarque :* ce port n'est nécessaire que si l'accès Prometheus basé sur un certificat est activé.



 a| 
9092
 a| 
TCP
 a| 
Kafka
 a| 
Nœuds de stockage avec ADC
 a| 
Cluster Kafka
 a| 
Utilisé pour les messages de services de plateforme envoyés à un cluster Kafka. Lors de la création d'un terminal, les locataires peuvent remplacer le paramètre par défaut du port Kafka 9092.



 a| 
9443
 a| 
TCP
 a| 
HTTPS
 a| 
Navigateur
 a| 
Nœuds d'administration
 a| 
Facultatif. Utilisé par les navigateurs Web et les clients API de gestion pour accéder au Gestionnaire de locataires. Peut être utilisé pour séparer les communications Grid Manager et tenant Manager.



 a| 
18082
 a| 
TCP
 a| 
HTTPS
 a| 
Clients S3
 a| 
Nœuds de stockage
 a| 
Trafic client S3 directement vers les nœuds de stockage (HTTPS).



 a| 
18084
 a| 
TCP
 a| 
HTTP
 a| 
Clients S3
 a| 
Nœuds de stockage
 a| 
Trafic client S3 directement vers les nœuds de stockage (HTTP).



 a| 
23000-23999
 a| 
TCP
 a| 
HTTPS
 a| 
Tous les nœuds du grid source pour la réplication inter-grid
 a| 
Nœuds d'administration et nœuds de passerelle sur le grid de destination pour la réplication inter-grid
 a| 
Cette plage de ports est réservée aux connexions de fédération de grille. Les deux grilles d'une connexion donnée utilisent le même port.

|===