= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Les données répliquées
--
* Pour obtenir une estimation du pourcentage d'achèvement de la réparation répliquée, ajoutez l' `show-replicated-repair-status`option à la commande repair-data.
+
`repair-data show-replicated-repair-status`

* Pour déterminer si les réparations sont terminées :
+
.. Sélectionnez *NŒUDS* > *_nœud de stockage en cours de réparation_* > *ILM*.
.. Vérifiez les attributs dans la section évaluation. Lorsque les réparations sont terminées, l'attribut *attente - tous* indique 0 objets.


* Pour surveiller la réparation plus en détail :
+
.. Sélectionnez *NOEUDS*.
.. Sélectionnez *_grid name_* > *ILM*.
.. Placez le curseur sur le graphique de la file d'attente ILM pour voir la valeur de l'attribut *Scan rate (objects/sec)*, qui est la vitesse à laquelle les objets de la grille sont analysés et mis en file d'attente pour ILM.
.. Dans la section ILM Queue, examinez les attributs suivants :
+
*** *Période d'analyse - estimation* : temps estimé pour effectuer une analyse ILM complète de tous les objets.
+
Une analyse complète ne garantit pas que le ILM a été appliqué à tous les objets.

*** *Tentatives de réparation* : nombre total d'opérations de réparation d'objets pour les données répliquées qui ont été tentées. Ce nombre est incrémenté chaque fois qu'un nœud de stockage tente de réparer un objet à haut risque. Les réparations ILM à haut risque sont hiérarchisées si le grid est occupé.
+
La réparation d'un même objet peut être de nouveau incrémentée si la réplication a échoué après la réparation. + ces attributs peuvent être utiles lorsque vous surveillez la progression de la restauration du volume du nœud de stockage. Si le nombre de réparations tentées a cessé d'augmenter et qu'une analyse complète a été effectuée, la réparation est probablement terminée.



.. Vous pouvez également envoyer une requête Prometheus pour `storagegrid_ilm_scan_period_estimated_minutes` et `storagegrid_ilm_repairs_attempted`.




--
.Données avec code d'effacement (EC)
--
Pour surveiller la réparation des données codées d'effacement et réessayer toute demande qui pourrait avoir échoué :

. Déterminez l'état des réparations des données par code d'effacement :
+
** Sélectionnez *SUPPORT* > *Tools* > *Metrics* pour afficher le temps de réalisation estimé et le pourcentage de réalisation de la tâche en cours. Sélectionnez ensuite *EC Overview* dans la section Grafana. Examinez les tableaux de bord *Grid EC Job estimé Time to Completion* et *Grid EC Job Percentage Finted*.
** Utiliser cette commande pour voir le statut d'une opération spécifique `repair-data` :
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Utilisez cette commande pour lister toutes les réparations :
+
`repair-data show-ec-repair-status`

+
Le résultat répertorie les informations, y compris `repair ID`, pour toutes les réparations en cours et antérieures.



. Si le résultat indique que l'opération de réparation a échoué, utilisez l' `--repair-id`option pour réessayer la réparation.
+
Cette commande relance une réparation de nœud ayant échoué à l'aide de l'ID de réparation 6949309319275667690 :

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Cette commande relance une réparation de volume en échec à l'aide de l'ID de réparation 6949309319275667690 :

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====