---
permalink: tenant/configuring-event-notifications.html 
sidebar: sidebar 
keywords: how to configure event notifications, bucket notification 
summary: Vous activez les notifications pour un compartiment en créant un XML de configuration de notification et en utilisant le gestionnaire de locataires pour appliquer le XML à un compartiment. 
---
= Configurer les notifications d'événements
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous activez les notifications pour un compartiment en créant un XML de configuration de notification et en utilisant le gestionnaire de locataires pour appliquer le XML à un compartiment.

.Avant de commencer
* Les services de plateforme ont été activés pour votre compte de locataire par un administrateur StorageGRID.
* Vous avez déjà créé un compartiment qui sert de source de notifications.
* Le noeud final que vous avez l'intention d'utiliser comme destination pour les notifications d'événements existe déjà, et vous avez son URN.
* Vous appartenez à un groupe d'utilisateurs qui possède le link:tenant-management-permissions.html["Gérez tous les compartiments ou l'autorisation d'accès racine"]. Ces autorisations remplacent les paramètres d'autorisation des stratégies de groupe ou de compartiment lors de la configuration du compartiment à l'aide du Gestionnaire de locataires.


.Description de la tâche
Vous configurez les notifications d’événements en associant le XML de configuration de notification à un bucket source.  Le XML de configuration de notification suit les conventions S3 pour la configuration des notifications de compartiment, avec la rubrique Amazon SNS de destination, la rubrique Kafka ou le point de terminaison webhook spécifié comme URN d'un point de terminaison.

Pour obtenir des informations générales sur les notifications d'événements et leur configuration, reportez-vous au https://docs.aws.amazon.com/s3/["Documentation Amazon"^]. Pour plus d'informations sur la manière dont StorageGRID implémente l'API de configuration des notifications de compartiment S3, reportez-vous au link:../s3/index.html["Instructions d'implémentation des applications client S3"].

Notez les exigences et caractéristiques suivantes lors de la configuration des notifications d'événement pour un compartiment :

* Lorsque vous créez et appliquez un XML de configuration de notification valide, il doit utiliser l'URN d'un noeud final de notification d'événement pour chaque destination.
* Bien que la notification d'événement puisse être configurée sur un compartiment avec le verrouillage objet S3 activé, les métadonnées de verrouillage objet S3 (y compris la date de conservation jusqu'à et l'état de conservation légale) des objets ne seront pas incluses dans les messages de notification.
* Une fois que vous avez configuré les notifications d'événements, chaque fois qu'un événement spécifié se produit pour un objet dans le compartiment source, une notification est générée et envoyée à la rubrique Amazon SNS, à la rubrique Kafka ou au point de terminaison webhook utilisé comme destination.
* Si vous activez les notifications d'événements pour un compartiment contenant des objets, les notifications sont envoyées uniquement pour les actions qui sont effectuées après l'enregistrement de la configuration de notification.


.Étapes
. Activer les notifications pour le compartiment source :
+
** Utilisez un éditeur de texte pour créer le XML de configuration de notification requis pour activer les notifications d'événement, comme spécifié dans l'API de notification S3.
** Lors de la configuration du XML, utilisez l'URN d'un terminal de notification d'événements comme sujet de destination.
+
[listing]
----
<NotificationConfiguration>
  <TopicConfiguration>
     <Id>Image-created</Id>
     <Filter>
        <S3Key>
          <FilterRule>
            <Name>prefix</Name>
            <Value>images/</Value>
          </FilterRule>
        </S3Key>
    </Filter>
    <Topic>arn:aws:sns:us-east-1:050340950352:sgws-topic</Topic>
    <Event>s3:ObjectCreated:*</Event>
   </TopicConfiguration>
 </NotificationConfiguration>
----


. Dans le Gestionnaire de locataires, sélectionnez *STORAGE (S3)* > *seaux*.
. Sélectionnez le nom du compartiment source.
+
La page des détails du compartiment s'affiche.

. Sélectionnez *Platform Services* > *Event Notifications*.
. Cochez la case *Activer les notifications d'événements*.
. Collez le XML de configuration de notification dans la zone de texte, puis sélectionnez *Enregistrer les modifications*.
+

NOTE: Les services de plateforme doivent être activés pour chaque compte de locataire par un administrateur StorageGRID à l'aide de Grid Manager ou de l'API de gestion du grid. Contactez votre administrateur StorageGRID si une erreur se produit lors de l'enregistrement du XML de configuration.

. Vérifiez que les notifications d'événements sont correctement configurées :
+
.. Exécutez une action sur un objet du compartiment source qui répond aux exigences de déclenchement d'une notification telles qu'elles sont configurées dans le fichier XML de configuration.
+
Dans cet exemple, une notification d'événement est envoyée chaque fois qu'un objet est créé avec le `images/` préfixe.

.. Confirmez qu'une notification a été envoyée à la rubrique Amazon SNS de destination, à la rubrique Kafka ou au point de terminaison du webhook.
+
Par exemple, si votre sujet de destination est hébergé sur Amazon SNS, vous pouvez configurer le service pour qu'il vous envoie un e-mail lorsque la notification est remise.

+
[listing]
----
{
   "Records":[
      {
         "eventVersion":"2.0",
         "eventSource":"sgws:s3",
         "eventTime":"2017-08-08T23:52:38Z",
         "eventName":"ObjectCreated:Put",
         "userIdentity":{
            "principalId":"1111111111111111111"
         },
         "requestParameters":{
            "sourceIPAddress":"193.51.100.20"
         },
         "responseElements":{
            "x-amz-request-id":"122047343"
         },
         "s3":{
            "s3SchemaVersion":"1.0",
            "configurationId":"Image-created",
            "bucket":{
               "name":"test1",
               "ownerIdentity":{
                  "principalId":"1111111111111111111"
               },
               "arn":"arn:sgws:s3:::test1"
            },
            "object":{
               "key":"images/cat.jpg",
               "size":0,
               "eTag":"d41d8cd98f00b204e9800998ecf8427e",
               "sequencer":"14D90402421461C7"
            }
         }
      }
   ]
}
----
+
Si la notification est reçue dans la rubrique de destination, vous avez configuré votre compartiment source pour les notifications StorageGRID.





.Informations associées
* link:understanding-notifications-for-buckets.html["Description des notifications pour les compartiments"]
* link:../s3/index.html["UTILISEZ L'API REST S3"]
* link:creating-platform-services-endpoint.html["Créer un terminal de services de plate-forme"]

