---
permalink: tenant/creating-groups-for-swift-tenant.html 
sidebar: sidebar 
keywords: how to create Swift tenant groups 
summary: 'Vous pouvez gérer les autorisations d"accès pour un compte de locataire Swift en important des groupes fédérés ou en créant des groupes locaux. Au moins un groupe doit disposer de l"autorisation Administrateur Swift, qui est requise pour gérer les conteneurs et les objets d"un compte de locataire Swift.' 
---
= Créez des groupes pour un locataire Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer les autorisations d'accès pour un compte de locataire Swift en important des groupes fédérés ou en créant des groupes locaux. Au moins un groupe doit disposer de l'autorisation Administrateur Swift, qui est requise pour gérer les conteneurs et les objets d'un compte de locataire Swift.


NOTE: La prise en charge des applications du client Swift a été obsolète et sera supprimée dans une prochaine version.

.Avant de commencer
* Vous êtes connecté au gestionnaire de locataires à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous appartenez à un groupe d'utilisateurs qui possède le link:tenant-management-permissions.html["Autorisation d'accès racine"].
* Si vous prévoyez d'importer un groupe fédéré, vous avez link:using-identity-federation.html["fédération des identités configurée"]et le groupe fédéré existe déjà dans le référentiel d'identité configuré.




== Accédez à l'assistant de création de groupe

.Étapes
Pour la première étape, accédez à l'assistant de création de groupe.

. Sélectionnez *ACCESS MANAGEMENT* > *Groups*.
. Sélectionnez *Créer groupe*.




== Choisissez un type de groupe

Vous pouvez créer un groupe local ou importer un groupe fédéré.

.Étapes
. Sélectionnez l'onglet *Groupe local* pour créer un groupe local ou sélectionnez l'onglet *Groupe fédéré* pour importer un groupe à partir du référentiel d'identité configuré précédemment.
+
Si l'authentification unique (SSO) est activée pour votre système StorageGRID, les utilisateurs appartenant à des groupes locaux ne pourront pas se connecter au Gestionnaire de locataires, bien qu'ils puissent utiliser les applications client pour gérer les ressources du locataire, en fonction des autorisations de groupe.

. Entrez le nom du groupe.
+
** *Groupe local* : saisissez à la fois un nom d'affichage et un nom unique. Vous pouvez modifier le nom d'affichage ultérieurement.
** *Groupe fédéré* : saisissez le nom unique. Pour Active Directory, le nom unique est le nom associé à l' `sAMAccountName`attribut. Pour OpenLDAP, le nom unique est le nom associé à l' `uid`attribut.


. Sélectionnez *Continuer*.




== Gérer les autorisations de groupe

Les autorisations de groupe contrôlent les tâches que les utilisateurs peuvent effectuer dans le Gestionnaire de locataires et l'API de gestion des locataires.

.Étapes
. Pour *Access mode*, sélectionnez l'une des options suivantes :
+
** *Lecture-écriture* (par défaut) : les utilisateurs peuvent se connecter au gestionnaire de locataires et gérer la configuration du locataire.
** *Lecture seule* : les utilisateurs peuvent uniquement afficher les paramètres et les fonctionnalités. Ils ne peuvent pas apporter de modifications ni exécuter d'opérations dans le gestionnaire de locataires ou l'API de gestion des locataires. Les utilisateurs locaux en lecture seule peuvent modifier leurs propres mots de passe.
+

NOTE: Si un utilisateur appartient à plusieurs groupes et qu'un groupe est défini sur lecture seule, l'utilisateur dispose d'un accès en lecture seule à tous les paramètres et fonctions sélectionnés.



. Cochez la case *accès racine* si les utilisateurs du groupe doivent se connecter à l'API tenant Manager ou tenant Management.
. Sélectionnez *Continuer*.




== Définissez la stratégie de groupe Swift

Les utilisateurs Swift ont besoin d'une autorisation d'administrateur pour s'authentifier auprès de l'API REST Swift afin de créer des conteneurs et d'ingérer des objets.

. Cochez la case *Swift Administrator* si les utilisateurs du groupe doivent utiliser l'API REST Swift pour gérer les conteneurs et les objets.
. Si vous créez un groupe local, sélectionnez *Continuer*. Si vous créez un groupe fédéré, sélectionnez *Créer groupe* et *Terminer*.




== Ajouter des utilisateurs (groupes locaux uniquement)

Vous pouvez enregistrer le groupe sans ajouter d'utilisateurs, ou vous pouvez éventuellement ajouter des utilisateurs locaux qui existent déjà.

.Étapes
. Vous pouvez également sélectionner un ou plusieurs utilisateurs locaux pour ce groupe.
+
Si vous n'avez pas encore créé d'utilisateurs locaux, vous pouvez ajouter ce groupe à l'utilisateur sur la page utilisateurs. Voir link:../tenant/managing-local-users.html["Gérez les utilisateurs locaux"].

. Sélectionnez *Créer groupe* et *Terminer*.
+
Le groupe que vous avez créé apparaît dans la liste des groupes.


