---
permalink: tenant/enable-cross-origin-resource-sharing-for-management-interface.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors, management, api, domain 
summary: 'Vous pouvez activer le partage de ressources d"origine croisée (CORS) pour les demandes d"API de gestion à StorageGRID, si vous souhaitez que les données dans StorageGRID soient accessibles à l"aide d"API de gestion vers un autre domaine.' 
---
= Activez StorageGRID CORS pour une interface de gestion
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer le partage de ressources d'origine croisée (CORS) pour les demandes d'API de gestion à StorageGRID, si vous souhaitez que les données dans StorageGRID soient accessibles à l'aide d'API de gestion vers un autre domaine.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Le link:tenant-management-permissions.html["Autorisation d'accès racine"] permet d'accéder à toutes les demandes de configuration CORS.


.Description de la tâche
CORS est un mécanisme de sécurité qui permet aux applications Web clientes d'un domaine d'accéder aux ressources d'un domaine différent. Par exemple, supposons que vous souhaitiez créer un tableau de bord de surveillance pour StorageGRID dans le domaine `\http://www.example.com`. En activant le CORS dans StorageGRID pour `\http://www.example.com` et le « Gestionnaire de grille », le domaine StorageGRID répond aux requêtes de l'API de gestion de grille de `\http://www.example.com`.

Les demandes d'API de gestion (Mgmt-api) avec `application/json` ou `multipart/formdata` pour `Content-Type` sont prises en charge pour les CORS.

.Étapes
. Sous *réseau* sur la page de configuration StorageGRID, sélectionnez *Paramètres CORS de l'interface de gestion*.
. Sélectionnez *Grid Manager*, *tenant Manager* ou les deux options.
+
** *Grid Manager* : active CORS pour les requêtes API de gestion de grille interdomaines.
** *Tenant Manager* : active CORS pour les requêtes API de gestion des locataires interdomaines.


. Entrez l'URL de l'autre domaine dans le champ *domaines*.
+
Sélectionnez *Ajouter un autre domaine* si vous souhaitez activer CORS dans StorageGRID pour plusieurs domaines.

. Sélectionnez *Enregistrer*.


.Informations associées
link:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["Configurer StorageGRID CORS pour les compartiments et les objets"]
