---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: 'Un compartiment de dérivation permet d"accéder aux objets d"un compartiment tels qu"ils existaient à un moment donné, à condition qu"ils existent toujours dans le compartiment. Utilisez le Gestionnaire de locataires pour créer et afficher des compartiments de succursales.' 
---
= Gérer les compartiments de branche
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un compartiment de dérivation permet d'accéder aux objets d'un compartiment tels qu'ils existaient à un moment donné, à condition qu'ils existent toujours dans le compartiment. Utilisez le Gestionnaire de locataires pour créer et afficher des compartiments de succursales.

Un compartiment de succursale permet d'accéder aux données protégées, mais ne sert pas de sauvegarde. Pour continuer à protéger les données, utilisez ces fonctionnalités sur les compartiments de base :

* link:../tenant/using-s3-object-lock.html["Verrouillage d'objet S3"]
* link:../admin/grid-federation-what-is-cross-grid-replication.html["Réplication entre plusieurs grilles"] pour godets de base
* link:../tenant/manage-bucket-policy.html["Règles de compartiment"] pour les compartiments avec version permettant de nettoyer les anciennes versions d'objets


.Description de la tâche
Vous créez un compartiment de branchement à partir d'un compartiment existant. Après avoir créé un compartiment de branchement, le compartiment d'origine à partir duquel il a été créé est appelé le compartiment de base. En outre, vous pouvez créer un compartiment de branchement à partir d'un autre compartiment de branchement. Lorsque vous effectuez des opérations sur le compartiment de base, les résultats sur le compartiment de branchement dépendent de l'opération et du type de compartiment de branchement que vous avez créé.

Vous pouvez utiliser un compartiment de branche pour supprimer les objets corrompus en créant un compartiment de branche à un point dans le temps avant la corruption, puis en pointant les applications vers le compartiment de branche au lieu du compartiment de base contenant des objets corrompus.


CAUTION: Un compartiment de succursale ne sert pas de sauvegarde, mais permet d'accéder aux données protégées. Vous devez continuer à utiliser link:../ilm/managing-objects-with-s3-object-lock.html["Verrouillage d'objet S3"] ou link:../admin/grid-federation-what-is-cross-grid-replication.html["réplication entre plusieurs grilles"] à protéger les données.

La réplication entre les grilles n'est pas prise en charge pour les compartiments de succursale.

.Avant de commencer
* Vous vous êtes connecté au gestionnaire de locataires à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous appartenez à un groupe d'utilisateurs disposant de l'accès racine ou de la fonction gérer tous les compartiments link:tenant-management-permissions.html["permission"]. Ces autorisations remplacent les paramètres d'autorisations des stratégies de groupes ou de compartiments.
* Le compartiment de base à partir duquel vous souhaitez créer une branche a link:../tenant/changing-bucket-versioning.html["gestion des versions activée"].
* Vous êtes le propriétaire du seau de base.
+

NOTE: Les autorisations permettant de définir ou de modifier les propriétés S3 Object Lock des compartiments ou des objets peuvent être accordées par link:../s3/bucket-and-group-access-policies.html["politique de compartiment ou règle de groupe"].





== Créer un compartiment de branchement

.Étapes
. Sélectionnez *Afficher les compartiments* dans le tableau de bord ou sélectionnez *STOCKAGE (S3)* > *compartiments*.
. Sélectionnez le compartiment à partir duquel vous souhaitez créer un branchement (le « godet de base »).
. Sur la page des détails du compartiment, sélectionnez *branches* > *Créer un compartiment de branchement*.
+
Le bouton *Créer un compartiment de branche* est désactivé si la gestion des versions du compartiment de base n'est pas activée.





== Entrez les détails

.Étapes
. Entrez les détails du compartiment de branche.
+
[cols="1a,3a"]
|===
| Champ | Description 


 a| 
Nom du compartiment de branche
 a| 
Nom du compartiment de branche conforme aux règles suivantes :

** Il doit être unique sur chaque système StorageGRID (et pas seulement au sein du compte du locataire).
** Doit être conforme DNS.
** Doit contenir au moins 3 et 63 caractères.
** Chaque étiquette doit commencer et se terminer par une lettre ou un chiffre en minuscules et ne peut utiliser que des lettres minuscules, des chiffres et des tirets.
** Ne doit pas contenir de périodes dans les demandes de type hébergement virtuel. Les périodes provoquera des problèmes avec la vérification du certificat générique du serveur.


Pour plus d'informations, voir https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Documentation Amazon Web Services (AWS) sur les règles d'attribution de nom de compartiment"^].

*Remarque* : vous ne pouvez pas modifier le nom après avoir créé le compartiment de branchement.



 a| 
Région (modification impossible pour les compartiments de branchement)
 a| 
Région du compartiment de branche.

La région du compartiment de branche doit correspondre à la région du compartiment de base, ce champ est donc désactivé pour les compartiments de branche.



 a| 
Avant l'heure
 a| 
Temps de coupure pour les versions d'objet créées dans le compartiment de base pour être accessibles à partir du compartiment de branche. Le compartiment de branche permet d'accéder aux versions d'objet créées avant le temps.



 a| 
Type de compartiment de dérivation
 a| 
** *Read-write* : vous pouvez ajouter ou supprimer des objets ou des versions d'objet dans le compartiment de branche.
** *Lecture seule* : vous ne pouvez pas modifier les objets dans le compartiment de branche.


|===
. Sélectionnez *Continuer*.




== Gérer les paramètres

Les paramètres d'un compartiment de branche n'affectent pas les versions d'objet dans le compartiment de base.

.Étapes
. Si le paramètre global S3 Object Lock est activé, activez éventuellement S3 Object Lock pour le compartiment de branche. Pour activer le verrouillage objet S3, le compartiment de branche doit être un compartiment en lecture-écriture.
+
Activez le verrouillage objet S3 pour un compartiment de succursale uniquement si vous devez conserver des objets pendant une durée fixe, par exemple pour répondre à certaines exigences réglementaires. Le verrouillage objet S3 est un paramètre permanent qui vous permet d'empêcher la suppression ou l'écrasement d'objets pendant une durée fixe ou indéfiniment.

+

CAUTION: Une fois le paramètre S3 Object Lock activé pour un compartiment, il ne peut pas être désactivé. Toute personne disposant des autorisations appropriées peut ajouter des objets au compartiment de branche qui ne peuvent pas être modifiés. Il se peut que vous ne puissiez pas supprimer ces objets ou le compartiment de branche lui-même.

. Si vous avez sélectionné *Activer le verrouillage d'objet S3*, vous pouvez activer *rétention par défaut* pour le compartiment de branche.
+

NOTE: Votre administrateur de grille doit vous donner l'autorisation de link:../tenant/using-s3-object-lock.html["Utiliser les fonctionnalités spécifiques du verrouillage objet S3"].

+
Lorsque *Default Retention* est activé, les nouveaux objets ajoutés au compartiment de branche sont automatiquement protégés contre la suppression ou l'écrasement. Le paramètre *rétention par défaut* ne s'applique pas aux objets qui ont leurs propres périodes de rétention.

+
.. Si *Default Retention* est activé, spécifiez un *mode de rétention par défaut* pour le compartiment de branche.
+
[cols="1a,2a"]
|===
| Mode de rétention par défaut | Description 


 a| 
La gouvernance
 a| 
*** Les utilisateurs disposant de l' `s3:BypassGovernanceRetention`autorisation peuvent utiliser l' `x-amz-bypass-governance-retention: true`en-tête de la demande pour contourner les paramètres de rétention.
*** Ces utilisateurs peuvent supprimer une version d'objet avant d'atteindre sa date de conservation jusqu'à.
*** Ces utilisateurs peuvent augmenter, diminuer ou supprimer la date de conservation d'un objet.




 a| 
La conformité
 a| 
*** L'objet ne peut pas être supprimé tant que sa date de conservation jusqu'à n'est pas atteinte.
*** La date de conservation de l'objet peut être augmentée, mais elle ne peut pas être réduite.
*** La date de conservation de l'objet jusqu'à ne peut pas être supprimée tant que cette date n'est pas atteinte.


*Remarque* : votre administrateur de grille doit vous permettre d'utiliser le mode de conformité.

|===
.. Si *rétention par défaut* est activé, spécifiez la *période de rétention par défaut* pour le compartiment de branche.
+
La *période de rétention par défaut* indique la durée pendant laquelle les nouveaux objets ajoutés au compartiment de branche doivent être conservés, à partir du moment où ils sont ingérés. Spécifiez une valeur inférieure ou égale à la période de rétention maximale pour le tenant, telle que définie par l'administrateur de la grille.

+
Une période de rétention _maximum_, qui peut être de 1 jour à 100 ans, est définie lorsque l'administrateur de la grille crée le locataire. Lorsque vous définissez une période de rétention _default_, elle ne peut pas dépasser la valeur définie pour la période de rétention maximale. Si nécessaire, demandez à votre administrateur de grille d'augmenter ou de réduire la période de rétention maximale.



. [[Capacity-limit]]en option, sélectionnez *Enable Capacity limit*.
+
La limite de capacité est la capacité maximale disponible pour le godet de dérivation. Cette valeur représente une quantité logique (taille de l'objet), et non une quantité physique (taille sur le disque).

+
Si aucune limite n'est définie, la capacité du compartiment de dérivation est illimitée. Pour plus d'informations, reportez-vous à la section link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["Utilisation limitée de la capacité"] .

+

NOTE: Ce paramètre s'applique uniquement aux objets directement ingérés dans le compartiment de branchement, et non aux objets visibles depuis le compartiment de base via le compartiment de branchement.

. Vous pouvez également sélectionner *Activer limite de nombre d'objets*.
+
La limite de nombre d'objets est le nombre maximal d'objets que le compartiment de branche peut contenir. Cette valeur représente une quantité logique (nombre d'objets). Si aucune limite n'est définie, le nombre d'objets est illimité.

+

NOTE: Ce paramètre s'applique uniquement aux objets directement ingérés dans le compartiment de branchement, et non aux objets visibles depuis le compartiment de base via le compartiment de branchement.

. Sélectionnez *Créer un compartiment*.
+
Le compartiment de branchement est créé et ajouté à la table sur la page compartiments.

. Si vous le souhaitez, sélectionnez *aller à la page des détails du compartiment* pour link:viewing-s3-bucket-details.html["afficher les détails du compartiment de branche"]effectuer une configuration supplémentaire.
+
Sur la page Détails du compartiment, certaines options de configuration liées à la modification des objets sont désactivées pour les compartiments en lecture seule.


