---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 'Avant de créer un groupe de locataires, tenez compte des autorisations que vous souhaitez attribuer à ce groupe. Les autorisations de gestion des locataires déterminent les tâches que les utilisateurs peuvent effectuer à l"aide du Gestionnaire de locataires ou de l"API de gestion des locataires. Un utilisateur peut appartenir à un ou plusieurs groupes. Les autorisations sont cumulatives si un utilisateur appartient à plusieurs groupes.' 
---
= Autorisations de gestion des locataires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de créer un groupe de locataires, tenez compte des autorisations que vous souhaitez attribuer à ce groupe. Les autorisations de gestion des locataires déterminent les tâches que les utilisateurs peuvent effectuer à l'aide du Gestionnaire de locataires ou de l'API de gestion des locataires. Un utilisateur peut appartenir à un ou plusieurs groupes. Les autorisations sont cumulatives si un utilisateur appartient à plusieurs groupes.

Pour vous connecter au Gestionnaire de locataires ou utiliser l'API de gestion des locataires, les utilisateurs doivent appartenir à un groupe disposant d'au moins une autorisation. Tous les utilisateurs autorisés à se connecter peuvent effectuer les tâches suivantes :

* Afficher le tableau de bord
* Modifier son propre mot de passe (pour les utilisateurs locaux)


Pour toutes les autorisations, le paramètre mode d'accès du groupe détermine si les utilisateurs peuvent modifier les paramètres et effectuer des opérations ou s'ils ne peuvent afficher que les paramètres et les fonctions associés.


NOTE: Si un utilisateur appartient à plusieurs groupes et qu'un groupe est défini sur lecture seule, l'utilisateur dispose d'un accès en lecture seule à tous les paramètres et fonctions sélectionnés.

Vous pouvez attribuer les autorisations suivantes à un groupe.

[cols="1a,3a,3a"]
|===
| Autorisations | Description | Détails 


 a| 
Accès racine
 a| 
Donne un accès complet au gestionnaire des locataires et à l'API de gestion des locataires.
 a| 



 a| 
Gérez vos identifiants S3
 a| 
Permet aux utilisateurs de créer et de supprimer leurs propres clés d'accès S3.
 a| 
Les utilisateurs qui ne disposent pas de cette autorisation ne voient pas l'option de menu *STORAGE (S3)* > *My S3 Access keys*.



 a| 
Afficher tous les compartiments
 a| 
Permet aux utilisateurs d'afficher tous les buckets et configurations de buckets.
 a| 
Les utilisateurs qui ne disposent pas de l'autorisation Afficher tous les compartiments ou gérer tous les compartiments ne voient pas l'option de menu *compartiments*.

Cette autorisation est remplacée par l’autorisation Gérer tous les buckets.  Cela n'affecte pas les stratégies de groupe ou de compartiment S3 utilisées par les clients S3 ou la console S3.



 a| 
Gestion de tous les compartiments
 a| 
Permet aux utilisateurs d'utiliser Tenant Manager et l'API Tenant Management pour créer et supprimer des compartiments S3 et pour gérer les paramètres de tous les compartiments S3 du compte locataire, quels que soient les compartiments S3 ou les stratégies de groupe.
 a| 
Les utilisateurs qui ne disposent pas de l'autorisation Afficher tous les compartiments ou gérer tous les compartiments ne voient pas l'option de menu *compartiments*.

Cette autorisation remplace l’autorisation Afficher tous les buckets.  Cela n'affecte pas les stratégies de groupe ou de compartiment S3 utilisées par les clients S3 ou la console S3.



 a| 
Gestion des terminaux
 a| 
Permet aux utilisateurs d'utiliser le gestionnaire de locataires ou l'API de gestion des locataires pour créer ou modifier des terminaux de service de plateforme, qui sont utilisés comme destination pour les services de plateforme StorageGRID.
 a| 
Les utilisateurs qui ne disposent pas de cette autorisation ne voient pas l'option de menu *Platform Services Endpoints*.



 a| 
Utilisez l'onglet de la console S3
 a| 
Associé à l'autorisation Afficher tous les compartiments ou gérer tous les compartiments, permet aux utilisateurs d'afficher et de gérer des objets à partir de l'onglet de la console S3 de la page de détails d'un compartiment.
 a| 

|===