---
permalink: vmware/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords: how to collect information about your deployment environment 
summary: 'Avant de déployer les nœuds de la grille, vous devez collecter des informations sur la configuration de votre réseau et l"environnement VMware.' 
---
= Collecte d'informations sur votre environnement de déploiement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer les nœuds de la grille, vous devez collecter des informations sur la configuration de votre réseau et l'environnement VMware.


NOTE: Il est plus efficace d'effectuer une seule installation de tous les nœuds, au lieu d'installer certains nœuds maintenant et certains nœuds ultérieurement.



== Informations sur VMware

Vous devez accéder à l'environnement de déploiement et collecter des informations sur l'environnement VMware, les réseaux créés pour les réseaux Grid, Admin et client, ainsi que les types de volume de stockage que vous envisagez d'utiliser pour les nœuds de stockage.

Vous devez collecter des informations sur votre environnement VMware, notamment :

* Nom d'utilisateur et mot de passe d'un compte VMware vSphere disposant des autorisations appropriées pour terminer le déploiement.
* Informations sur l'hôte, le datastore et la configuration réseau pour chaque machine virtuelle de nœud StorageGRID.



NOTE: VMware Live vMotion provoque l'augmentation de l'horloge de la machine virtuelle et n'est pas pris en charge pour les nœuds grid d'aucun type. Bien que les temps d'horloge rares et incorrects peuvent entraîner une perte de données ou des mises à jour de la configuration.



== Informations sur le réseau

Vous devez collecter des informations sur le réseau VMware créé pour le réseau StorageGRID Grid Network (obligatoire), notamment :

* Nom du réseau.
* Méthode utilisée pour attribuer des adresses IP, statiques ou DHCP.
+
** Si vous utilisez des adresses IP statiques, les informations de mise en réseau requises pour chaque nœud de la grille (adresse IP, passerelle, masque de réseau).
** Si vous utilisez DHCP, l'adresse IP du nœud d'administration principal sur le réseau Grid. Voir link:how-grid-nodes-discover-primary-admin-node.html["Mode de détection des nœuds du grid sur le nœud d'administration principal"] pour plus d'informations.






== Informations sur le réseau d'administration

Pour les nœuds qui seront connectés au réseau d'administration StorageGRID facultatif, vous devez collecter des informations sur le réseau VMware créé pour ce réseau, notamment :

* Nom du réseau.
* Méthode utilisée pour attribuer des adresses IP, statiques ou DHCP.
+
** Si vous utilisez des adresses IP statiques, les informations de mise en réseau requises pour chaque nœud de la grille (adresse IP, passerelle, masque de réseau).
** Si vous utilisez DHCP, l'adresse IP du nœud d'administration principal sur le réseau Grid. Voir link:how-grid-nodes-discover-primary-admin-node.html["Mode de détection des nœuds du grid sur le nœud d'administration principal"] pour plus d'informations.


* La liste des sous-réseaux externes (ESL) pour le réseau Admin.




== Informations sur le réseau client

Pour les nœuds qui seront connectés au réseau client StorageGRID en option, vous devez collecter des informations sur le réseau VMware créé pour ce réseau, notamment :

* Nom du réseau.
* Méthode utilisée pour attribuer des adresses IP, statiques ou DHCP.
* Si vous utilisez des adresses IP statiques, les informations de mise en réseau requises pour chaque nœud de la grille (adresse IP, passerelle, masque de réseau).




== Informations sur les interfaces supplémentaires

Vous pouvez éventuellement ajouter une jonction ou des interfaces d'accès à la machine virtuelle dans vCenter après l'installation du nœud. Par exemple, vous pouvez ajouter une interface de jonction à un noeud d'administration ou de passerelle, de sorte que vous pouvez utiliser des interfaces VLAN pour isoler le trafic appartenant à différentes applications ou locataires. Vous pouvez également ajouter une interface d'accès à utiliser au sein d'un groupe de haute disponibilité (HA).

Les interfaces que vous ajoutez s'affichent sur la page des interfaces VLAN et sur la page HA Groups de la grille Manager.

* Si vous ajoutez une interface de jonction, configurez une ou plusieurs interfaces VLAN pour chaque nouvelle interface parent. Voir link:../admin/configure-vlan-interfaces.html["Configurez les interfaces VLAN"].
* Si vous ajoutez une interface d'accès, vous devez l'ajouter directement aux groupes haute disponibilité. Voir link:../admin/configure-high-availability-group.html["configurez les groupes haute disponibilité"].




== Volumes de stockage pour les nœuds de stockage virtuels

Vous devez collecter les informations suivantes pour les nœuds de stockage basés sur des machines virtuelles :

* Le nombre et la taille des volumes de stockage (LUN de stockage) que vous prévoyez d'ajouter. Voir link:storage-and-performance-requirements.html["Les besoins en matière de stockage et de performances"].




== Informations de configuration de la grille

Vous devez collecter des informations pour configurer votre grille :

* Licence Grid
* Adresses IP du serveur NTP (Network Time Protocol)
* Adresses IP du serveur DNS

