---
permalink: rhel/configuring-docker-storage-volume.html 
sidebar: sidebar 
keywords: how to configure container engine storage volume, Docker, Podman 
summary: 'Avant d"installer le moteur de mise en conteneurs (Docker ou Podman), vous devrez peut-être formater le volume de stockage et le monter.' 
---
= Configurer le volume de stockage du moteur du conteneur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer le moteur de mise en conteneurs (Docker ou Podman), vous devrez peut-être formater le volume de stockage et le monter.


NOTE: La prise en charge de Docker, car le moteur de mise en conteneurs pour les déploiements exclusivement logiciels est obsolète. Docker sera remplacé par un autre moteur de mise en conteneurs dans une prochaine version.

.Description de la tâche
Vous pouvez ignorer ces étapes si vous prévoyez d'utiliser le stockage local pour le volume de stockage Docker ou Podman et si vous disposez de suffisamment d'espace disponible sur la partition hôte contenant `/var/lib/docker` pour Docker et `/var/lib/containers` pour Podman.


NOTE: Podman est pris en charge uniquement sur Red Hat Enterprise Linux (RHEL).

.Étapes
. Créer un système de fichiers sur le volume de stockage du moteur de conteneur :
+
[listing]
----
sudo mkfs.ext4 container-engine-storage-volume-device
----
. Monter le volume de stockage du moteur du conteneur :
+
** Pour Docker :
+
[listing]
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
** Pour Podman :
+
[listing]
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----


. Ajoutez une entrée pour conteneur-Storage-volume-device à /etc/fstab.
+
Cette étape permet de s'assurer que le volume de stockage se réajuste automatiquement après le redémarrage de l'hôte.





== Installez Docker

Le système StorageGRID fonctionne sous Red Hat Enterprise Linux comme un ensemble de conteneurs. Si vous avez choisi d'utiliser le moteur de mise en conteneurs Docker, procédez comme suit pour installer Docker. Sinon, <<Installez Podman,Installez Podman>>.

.Étapes
. Installez Docker en suivant les instructions de votre distribution Linux.
+

NOTE: Si Docker n'est pas inclus dans votre distribution Linux, vous pouvez le télécharger sur le site Web de Docker.

. Assurez-vous que Docker a été activé et démarré en exécutant les deux commandes suivantes :
+
[listing]
----
sudo systemctl enable docker
----
+
[listing]
----
sudo systemctl start docker
----
. Vérifiez que vous avez installé la version attendue de Docker en saisissant les éléments suivants :
+
[listing]
----
sudo docker version
----
+
Les versions client et serveur doivent être 1.11.0 ou supérieures.





== Installez Podman

Le système StorageGRID fonctionne sous Red Hat Enterprise Linux comme un ensemble de conteneurs. Si vous avez choisi d'utiliser le moteur de mise en conteneurs Podman, suivez ces étapes pour installer Podman. Sinon, <<Installez Docker,Installez Docker>>.


NOTE: Podman est pris en charge uniquement sur Red Hat Enterprise Linux (RHEL).

.Étapes
. Installez Podman et Podman-Docker en suivant les instructions pour votre distribution Linux.
+

NOTE: Vous devez également installer le package Podman-Docker lorsque vous installez Podman.

. Vérifiez que vous avez installé la version attendue de Podman et Podman-Docker en saisissant les éléments suivants :
+
[listing]
----
sudo docker version
----
+

NOTE: Le package Podman-Docker vous permet d'utiliser des commandes Docker.

+
Les versions client et serveur doivent être 3.2.3 ou supérieures.

+
[listing]
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----

