---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: 'Vous devez installer StorageGRID sur tous les hôtes Red Hat Enterprise Linux GRID. Pour obtenir la liste des versions prises en charge, utilisez la matrice d"interopérabilité de NetApp.' 
---
= Installez Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer StorageGRID sur tous les hôtes Red Hat Enterprise Linux GRID. Pour obtenir la liste des versions prises en charge, utilisez la matrice d'interopérabilité de NetApp.

.Avant de commencer
Assurez-vous que votre système d'exploitation répond aux exigences minimales de StorageGRID en matière de version du noyau, comme indiqué ci-dessous. Utilisez la commande `uname -r` pour obtenir la version du noyau de votre système d'exploitation ou consultez votre fournisseur de système d'exploitation.

[cols="1a,2a,2a"]
|===
| Version de Red Hat Enterprise Linux | Version minimale du noyau | Nom du package du noyau 


 a| 
8.8 (obsolète)
 a| 
4.18.0-477.10.1.el8_8.x86_64
 a| 
kernel-4.18.0-477.10.1.el8_8.x86_64



 a| 
8.10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
kernel-4.18.0-553.el8_10.x86_64



 a| 
9.0 (obsolète)
 a| 
5.14.0-70.22.1.el9_0.x86_64
 a| 
kernel-5.14.0-70.22.1.el9_0.x86_64



 a| 
9.2 (obsolète)
 a| 
5.14.0-284.11.1.el9_2.x86_64
 a| 
kernel-5.14.0-284.11.1.el9_2.x86_64



 a| 
9,4
 a| 
5.14.0-427.18.1.el9_4.x86_64
 a| 
kernel-5.14.0-427.18.1.el9_4.x86_64

|===
.Étapes
. Installez Linux sur tous les hôtes de réseau physiques ou virtuels conformément aux instructions du distributeur ou à la procédure standard.
+

NOTE: Si vous utilisez le programme d'installation Linux standard, sélectionnez la configuration logicielle du « nœud de calcul », si disponible, ou l'environnement de base « installation minimale ». N'installez aucun environnement de bureau graphique.

. Assurez-vous que tous les hôtes ont accès aux référentiels de paquets, y compris le canal Extras.
+
Vous aurez peut-être besoin de ces modules supplémentaires plus tard dans cette procédure d'installation.

. Si le swap est activé :
+
.. Exécutez la commande suivante : `$ sudo swapoff --all`
.. Supprimez toutes les entrées d'échange de `/etc/fstab` pour conserver les paramètres.


+

NOTE: Si vous ne désactivez pas ces fichiers, les performances peuvent être considérablement réduites.


