---
permalink: admin/administering-storagegrid-system.html 
sidebar: sidebar 
keywords: administration overview 
summary: Suivez ces instructions pour configurer et administrer un système StorageGRID. 
---
= Administration d'un système StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez ces instructions pour configurer et administrer un système StorageGRID.

Les instructions suivantes décrivent comment utiliser le Gestionnaire de grille pour configurer des groupes et des utilisateurs, créer des comptes de locataire pour permettre aux applications client S3 de stocker et de récupérer des objets, configurer et gérer des réseaux StorageGRID, configurer AutoSupport, gérer les paramètres de nœud, etc.

Ces instructions s'adresse au personnel technique qui devra configurer, administrer et prendre en charge un système StorageGRID après son installation.

.Avant de commencer
* Vous disposez d'une compréhension générale du système StorageGRID.
* Vous disposez d'une connaissance assez détaillée des shells de commande Linux, de la mise en réseau et de la configuration matérielle du serveur.

