---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords: change password, grid manager password 
summary: Si vous êtes un utilisateur local de Grid Manager, vous pouvez modifier votre propre mot de passe. 
---
= Changer votre mot de passe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous êtes un utilisateur local de Grid Manager, vous pouvez modifier votre propre mot de passe.

.Avant de commencer
Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].

.Description de la tâche
Si vous vous connectez à StorageGRID en tant qu'utilisateur fédéré ou si l'authentification unique (SSO) est activée, vous ne pouvez pas modifier votre mot de passe dans le Gestionnaire de grille. Vous devez plutôt modifier votre mot de passe dans le référentiel d'identité externe, par exemple Active Directory ou OpenLDAP.

.Étapes
. Dans l'en-tête de Grid Manager, sélectionnez *_votre nom_* > *changer mot de passe*.
. Saisissez votre mot de passe actuel.
. Saisissez un nouveau mot de passe.
+
Votre mot de passe doit contenir au moins 8 caractères et pas plus de 32 caractères. Les mots de passe sont sensibles à la casse.

. Saisissez à nouveau le nouveau mot de passe.
. Sélectionnez *Enregistrer*.

