---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 'Chaque nœud de la grille dispose d"un mot de passe de console de nœud, que vous utilisez pour vous connecter au nœud. Par défaut, chaque nœud possède un mot de passe unique. Vous pouvez remplacer chaque mot de passe par un nouveau mot de passe unique ou modifier le mot de passe de chaque nœud pour utiliser un mot de passe global. Les mots de passe sont stockés dans le package de récupération.' 
---
= Changer les mots de passe de la console du nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque nœud de la grille dispose d'un mot de passe de console de nœud, que vous utilisez pour vous connecter au nœud. Par défaut, chaque nœud possède un mot de passe unique. Vous pouvez remplacer chaque mot de passe par un nouveau mot de passe unique ou modifier le mot de passe de chaque nœud pour utiliser un mot de passe global. Les mots de passe sont stockés dans le package de récupération.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez le link:admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Vous disposez de la phrase secrète pour le provisionnement.


.Description de la tâche
Utilisez un mot de passe de la console du nœud pour vous connecter à un nœud en tant qu'administrateur via SSH ou à l'utilisateur root sur une connexion de console physique/machine virtuelle. Vous pouvez modifier les mots de passe de la console de nœuds à l'aide de l'une des options suivantes :

* Appliquez automatiquement des mots de passe aléatoires à chaque nœud
* Spécifiez et appliquez un mot de passe global à tous les nœuds
* Spécifiez et appliquez un mot de passe unique à un ou plusieurs nœuds


Les mots de passe sont stockés dans un fichier mis à jour `Passwords.txt` dans le package de récupération. Les mots de passe sont répertoriés dans la colonne Mot de passe du fichier.


NOTE: Les link:../admin/change-ssh-access-passwords.html["Mots de passe d'accès SSH"]clés SSH utilisées pour la communication entre les nœuds sont séparées des mots de passe de la console du nœud. Cette procédure ne modifie pas les mots de passe d'accès SSH.



== Accéder à l'assistant

.Étapes
. Sélectionnez *CONFIGURATION* > *contrôle d'accès* > *mots de passe de grille*.
. Sous *Modifier les mots de passe de la console de nœuds*, sélectionnez *faire une modification*.




== [[download-current]]Téléchargez le package de récupération actuel

Avant de modifier les mots de passe de la console de nœuds, téléchargez le pack de restauration actuel. Vous pouvez utiliser les mots de passe de ce fichier si le processus de modification du mot de passe échoue pour un noeud quelconque.

.Étapes
. Saisissez la phrase de passe de provisionnement pour votre grid.
. Sélectionnez *Télécharger le paquet de récupération*.
. Copiez le fichier du package de récupération (`.zip`) dans deux emplacements sécurisés et séparés.
+

CAUTION: Le fichier de package de récupération doit être sécurisé car il contient des clés de cryptage et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID.

. Sélectionnez *Continuer*.




== Fournir de nouveaux mots de passe

. Sélectionnez la méthode de modification du mot de passe que vous souhaitez utiliser.
+
** *Automatique* : StorageGRID attribue automatiquement un nouveau mot de passe de console aléatoire à tous les nœuds.
** *Personnalisé* : vous fournissez des mots de passe de console.




[role="tabbed-block"]
====
.Automatique
--
. Sélectionnez *Continuer*.


--
.Personnalisées
--
. Sélectionnez l'une des options suivantes :
+
** *Mot de passe global de la console* : appliquez le même mot de passe à tous les nœuds.
** *Mots de passe de console uniques* : appliquez un mot de passe différent sur un ou plusieurs nœuds.


. Si vous avez sélectionné *Global console password*, entrez le mot de passe que vous souhaitez utiliser pour tous les nœuds.
. Si vous avez sélectionné *unique console mots de passe*, entrez un mot de passe unique pour un ou plusieurs nœuds.
. Sélectionnez *Continuer*.


--
====


== Terminez le changement de mot de passe

. Lorsque la boîte de dialogue de confirmation s'affiche, sélectionnez *Oui* si vous êtes prêt à ce que StorageGRID commence à modifier les mots de passe de la console du nœud.
+

NOTE: Vous ne pouvez pas annuler ce processus après son démarrage.

+
StorageGRID génère un nouveau package de récupération contenant le nouveau mot de passe.

. Lorsque le nouveau package de récupération est prêt, sélectionnez *Télécharger le nouveau package de récupération* et enregistrez le package de récupération.
. Ouvrez le `.zip` fichier.
. Vérifiez que vous pouvez accéder au contenu, y compris au `Passwords.txt` fichier qui contient les nouveaux mots de passe de la console du nœud.
. Copiez le nouveau fichier de package de récupération (`.zip`) dans deux emplacements sûrs, sécurisés et séparés.
+

CAUTION: Ne remplacez pas l'ancien package de récupération.

+
Vous devez sécuriser le fichier de récupération, car il contient des clés de cryptage et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID.

. Cochez la case pour indiquer que vous avez téléchargé le nouveau package de récupération et vérifié le contenu.
. Sélectionnez *Continuer*.
+
StorageGRID met à jour le mot de passe de chaque nœud.

+
En cas d'erreur lors du processus de mise à jour, la barre de progression indique le nombre de nœuds dont le mot de passe n'a pas pu être modifié. Le système réexécute automatiquement le processus sur tout nœud dont le mot de passe n'a pas été modifié. Si le processus se termine avec certains nœuds qui n'ont toujours pas de mot de passe modifié, le bouton *Réessayer* s'affiche.

. Si la mise à jour du mot de passe a échoué pour un ou plusieurs nœuds :
+
.. Vérifiez les messages d'erreur répertoriés dans le tableau.
.. Résolvez les problèmes.
.. Sélectionnez *Réessayer*.
+

NOTE: La tentative de nouveau modifie uniquement les mots de passe de la console de nœud sur les nœuds qui ont échoué lors des précédentes tentatives de changement de mot de passe.



. Lorsque la barre de progression indique qu'il ne reste aucune mise à jour, sélectionnez *Terminer*.
. Une fois que les mots de passe de la console du nœud ont été modifiés pour tous les nœuds, supprimez le <<download-current,premier paquet de récupération que vous avez téléchargé>>.

