---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 'Chaque nœud de votre grid dispose d"un mot de passe de console de nœud unique que vous devez vous connecter au nœud. Procédez comme suit pour modifier le mot de passe de la console des nœuds de chaque nœud de votre grille. Les mots de passe sont stockés dans le progiciel de restauration.' 
---
= Changer les mots de passe de la console du nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque nœud de votre grid dispose d'un mot de passe de console de nœud unique que vous devez vous connecter au nœud. Procédez comme suit pour modifier chaque mot de passe de console de nœud unique pour chaque nœud de votre grille.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez le link:admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Vous disposez de la phrase secrète pour le provisionnement.


.Description de la tâche
Utilisez le mot de passe de la console du nœud pour vous connecter à un nœud en tant qu'administrateur via SSH ou à l'utilisateur root sur une connexion de console physique/machine virtuelle. Le processus de modification du mot de passe de la console des nœuds crée de nouveaux mots de passe pour chaque nœud de votre grille et stocke les mots de passe dans un fichier mis à jour `Passwords.txt` dans le module de récupération. Les mots de passe sont répertoriés dans la colonne Mot de passe du fichier Passwords.txt.


NOTE: Il existe des mots de passe d'accès SSH distincts pour les clés SSH utilisées pour la communication entre les nœuds. Les mots de passe d'accès SSH ne sont pas modifiés par cette procédure.



== Accéder à l'assistant

.Étapes
. Sélectionnez *CONFIGURATION* > *contrôle d'accès* > *mots de passe de grille*.
. Sous *Modifier les mots de passe de la console de nœuds*, sélectionnez *faire une modification*.




== Saisissez la phrase secrète pour le provisionnement

.Étapes
. Saisissez la phrase de passe de provisionnement pour votre grid.
. Sélectionnez *Continuer*.




== [[download-current]]Téléchargez le package de récupération actuel

Avant de modifier les mots de passe de la console de nœuds, téléchargez le progiciel de récupération actuel. Vous pouvez utiliser les mots de passe de ce fichier si le processus de modification du mot de passe échoue pour un noeud quelconque.

.Étapes
. Sélectionnez *Télécharger le paquet de récupération*.
. Copiez le fichier du package de récupération (`.zip`) dans deux emplacements sécurisés et séparés.
+

CAUTION: Le fichier du progiciel de récupération doit être sécurisé car il contient des clés de cryptage et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID.

. Sélectionnez *Continuer*.
. Lorsque la boîte de dialogue de confirmation apparaît, sélectionnez *Oui* si vous êtes prêt à modifier les mots de passe de la console du nœud.
+
Vous ne pouvez pas annuler ce processus après son démarrage.





== Changer les mots de passe de la console du nœud

Lorsque le processus de mot de passe de la console du nœud démarre, un nouveau package de récupération est généré, qui inclut les nouveaux mots de passe. Les mots de passe sont ensuite mis à jour sur chaque nœud.

.Étapes
. Attendez que le nouveau package de récupération soit généré, ce qui peut prendre quelques minutes.
. Sélectionnez *Télécharger nouveau paquet de récupération*.
. Une fois le téléchargement terminé :
+
.. Ouvrez le `.zip` fichier.
.. Vérifiez que vous pouvez accéder au contenu, y compris au `Passwords.txt` fichier qui contient les nouveaux mots de passe de la console du nœud.
.. Copiez le nouveau fichier de package de récupération (`.zip`) dans deux emplacements sécurisés et séparés.
+

CAUTION: Ne remplacez pas l'ancien package de récupération.

+
Le fichier du progiciel de récupération doit être sécurisé car il contient des clés de cryptage et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID.



. Cochez la case pour indiquer que vous avez téléchargé le nouveau package de récupération et vérifié le contenu.
. Sélectionnez *Modifier les mots de passe de la console de nœuds* et attendez que tous les nœuds soient mis à jour avec les nouveaux mots de passe. Cette opération peut prendre quelques minutes.
+
Si les mots de passe sont modifiés pour tous les nœuds, une bannière de réussite verte s'affiche. Passez à l'étape suivante.

+
En cas d'erreur lors du processus de mise à jour, un message de bannière indique le nombre de nœuds dont les mots de passe n'ont pas été modifiés. Le système réexécute automatiquement le processus sur tout nœud dont le mot de passe n'a pas été modifié. Si le processus se termine avec certains nœuds qui n'ont toujours pas de mot de passe modifié, le bouton *Réessayer* s'affiche.

+
Si la mise à jour du mot de passe a échoué pour un ou plusieurs nœuds :

+
.. Vérifiez les messages d'erreur répertoriés dans le tableau.
.. Résolvez les problèmes.
.. Sélectionnez *Réessayer*.
+

NOTE: La tentative de nouveau modifie uniquement les mots de passe de la console de nœud sur les nœuds qui ont échoué lors des précédentes tentatives de changement de mot de passe.



. Une fois que les mots de passe de la console du nœud ont été modifiés pour tous les nœuds, supprimez le <<download-current,Premier package de récupération que vous avez téléchargé>>.
. Vous pouvez également utiliser le lien *Recovery package* pour télécharger une copie supplémentaire du nouveau progiciel de récupération.

