---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 'La modification des mots de passe d"accès SSH pour les nœuds d"administration met également à jour les ensembles uniques de clés SSH internes pour chaque nœud de la grille. Le nœud d"administration principal utilise ces clés SSH pour accéder aux nœuds via une authentification sécurisée sans mot de passe.' 
---
= Modifier les mots de passe d'accès SSH des nœuds d'administration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La modification des mots de passe d'accès SSH pour les nœuds d'administration met également à jour les ensembles uniques de clés SSH internes pour chaque nœud de la grille. Le nœud d'administration principal utilise ces clés SSH pour accéder aux nœuds via une authentification sécurisée sans mot de passe.

Utilisez une clé SSH pour vous connecter à un nœud en tant que `admin` ou à l'utilisateur root sur une VM ou une connexion à une console physique.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez le link:admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Vous disposez de la phrase secrète pour le provisionnement.


.Description de la tâche
Les nouveaux mots de passe d'accès pour les nœuds d'administration et les nouvelles clés internes pour chaque nœud sont stockés dans le `Passwords.txt` fichier dans le package de récupération.  Les clés sont répertoriées dans la colonne Mot de passe de ce fichier.

Il existe des mots de passe d'accès SSH distincts pour les clés SSH utilisées pour la communication entre les nœuds. Celles-ci ne sont pas modifiées par cette procédure.



== Accéder à l'assistant

.Étapes
. Sélectionnez *Configuration* > *Contrôle d'accès* > *Mots de passe de grille*.
. Sous *Modifier les clés SSH*, sélectionnez *faire une modification*.




== [[download-current]]Téléchargez le package de récupération actuel

Avant de modifier les clés d’accès SSH, téléchargez le package de récupération actuel.  Vous pouvez utiliser les clés de ce fichier si le processus de changement de clé échoue pour un nœud.

.Étapes
. Saisissez la phrase de passe de provisionnement pour votre grid.
. Sélectionnez *Télécharger le paquet de récupération*.
. Copier le fichier du package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID .

. Sélectionnez *Continuer*.
. Lorsque la boîte de dialogue de confirmation s'affiche, sélectionnez *Oui* si vous êtes prêt à changer les clés d'accès SSH.
+

CAUTION: Vous ne pouvez pas annuler ce processus après son démarrage.





== Modifier les clés d'accès SSH

Lorsque le processus de modification des clés d’accès SSH démarre, un nouveau package de récupération est généré qui inclut les nouvelles clés.  Ensuite, les clés sont mises à jour sur chaque nœud.

.Étapes
. Attendez que le nouveau package de récupération soit généré, ce qui peut prendre quelques minutes.
. Lorsque le bouton Télécharger un nouveau package de récupération est activé, sélectionnez *Télécharger un nouveau package de récupération* et enregistrez le nouveau fichier de package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
. Une fois le téléchargement terminé :
+
.. Ouvrez le `.zip` fichier.
.. Vérifiez que vous pouvez accéder au contenu, y compris au `Passwords.txt` fichier qui contient les nouvelles clés d'accès SSH.
.. Copiez le nouveau fichier de package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: N'écrasez pas l'ancien package de récupération.

+
Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID .



. Attendez que les clés soient mises à jour sur chaque nœud, ce qui peut prendre quelques minutes.
+
Si les clés sont modifiées pour tous les nœuds, une bannière de réussite verte s'affiche.

+
En cas d'erreur lors du processus de mise à jour, un message d'avertissement indique le nombre de nœuds dont les clés n'ont pas pu être modifiées. Le système réessaiera automatiquement le processus sur tout nœud dont la clé n'a pas pu être modifiée. Si le processus se termine alors que certains nœuds n'ont toujours pas de clé modifiée, le bouton *Réessayer* s'affiche.

+
Si la mise à jour de la clé a échoué pour un ou plusieurs nœuds :

+
.. Vérifiez les messages d'erreur répertoriés dans le tableau.
.. Résolvez les problèmes.
.. Sélectionnez *Réessayer*.
+
La reconnexion ne modifie que les clés d'accès SSH sur les nœuds qui ont échoué lors des tentatives précédentes de changement de clé.



. Une fois les clés d'accès SSH modifiées pour tous les nœuds, supprimez le<<download-current,premier package de récupération que vous avez téléchargé>> .
. Vous pouvez également sélectionner *Maintenance* > *Système* > *Package de récupération* pour télécharger une copie supplémentaire du nouveau package de récupération.

