---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 'Chaque nœud de votre grille dispose d"un mot de passe de console de nœud, que vous utilisez pour vous connecter au nœud.  Par défaut, chaque nœud possède un mot de passe unique.  Vous pouvez modifier chaque mot de passe par un nouveau mot de passe unique ou modifier le mot de passe de chaque nœud pour utiliser un mot de passe global.  Les mots de passe sont stockés dans le package de récupération.' 
---
= Changer les mots de passe de la console du nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque nœud de votre grille dispose d'un mot de passe de console de nœud, que vous utilisez pour vous connecter au nœud.  Par défaut, chaque nœud possède un mot de passe unique.  Vous pouvez modifier chaque mot de passe par un nouveau mot de passe unique ou modifier le mot de passe de chaque nœud pour utiliser un mot de passe global.  Les mots de passe sont stockés dans le package de récupération.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez le link:admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Vous disposez de la phrase secrète pour le provisionnement.


.Description de la tâche
Vous utilisez un mot de passe de console de nœud pour vous connecter à un nœud en tant qu'« administrateur » à l'aide de SSH ou en tant qu'utilisateur root sur une connexion VM/console physique.  Vous pouvez modifier les mots de passe de la console du nœud à l’aide de l’une de ces options :

* Appliquer automatiquement des mots de passe aléatoires à chaque nœud
* Spécifiez et appliquez un mot de passe global à tous les nœuds
* Spécifiez et appliquez un mot de passe unique à un ou plusieurs nœuds


Les mots de passe sont stockés dans un fichier mis à jour `Passwords.txt` fichier dans le package de récupération.  Les mots de passe sont répertoriés dans la colonne Mot de passe du fichier.


NOTE: Lelink:../admin/change-ssh-access-passwords.html["Mots de passe d'accès SSH"] car les clés SSH utilisées pour la communication entre les nœuds sont distinctes des mots de passe de la console des nœuds.  Cette procédure ne modifie pas les mots de passe d’accès SSH.



== Accéder à l'assistant

.Étapes
. Sélectionnez *Configuration* > *Contrôle d'accès* > *Mots de passe de grille*.
. Sous *Modifier les mots de passe de la console de nœuds*, sélectionnez *faire une modification*.




== [[download-current]]Téléchargez le package de récupération actuel

Avant de modifier les mots de passe de la console du nœud, téléchargez le package de récupération actuel.  Vous pouvez utiliser les mots de passe de ce fichier si le processus de changement de mot de passe échoue pour un nœud.

.Étapes
. Saisissez la phrase de passe de provisionnement pour votre grid.
. Sélectionnez *Télécharger le paquet de récupération*.
. Copier le fichier du package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID .

. Sélectionnez *Continuer*.




== Fournir de nouveaux mots de passe

. Sélectionnez la méthode de changement de mot de passe que vous souhaitez utiliser.
+
** *Automatique* : StorageGRID attribue automatiquement un nouveau mot de passe de console aléatoire à tous les nœuds.
** *Personnalisé* : Vous fournissez les mots de passe de la console.




[role="tabbed-block"]
====
.Automatique
--
. Sélectionnez *Continuer*.


--
.Personnalisées
--
. Sélectionnez l'une des options suivantes :
+
** *Mot de passe de la console globale* : appliquez le même mot de passe de console à tous les nœuds.
** *Mots de passe de console uniques* : appliquez un mot de passe différent sur un ou plusieurs nœuds.


. Si vous avez sélectionné *Mot de passe de la console globale*, saisissez le mot de passe que vous souhaitez utiliser pour tous les nœuds.
. Si vous avez sélectionné *Mots de passe de console uniques*, saisissez un mot de passe unique pour un ou plusieurs nœuds.
. Sélectionnez *Continuer*.


--
====


== Terminer le changement de mot de passe

. Lorsque la boîte de dialogue de confirmation s'affiche, sélectionnez *Oui* si vous êtes prêt à ce que StorageGRID commence à modifier les mots de passe de la console du nœud.
+

NOTE: Vous ne pouvez pas annuler ce processus après son démarrage.

+
StorageGRID génère un nouveau package de récupération contenant le nouveau mot de passe.

. Lorsque le nouveau package de récupération est prêt, sélectionnez *Télécharger le nouveau package de récupération* et enregistrez le package de récupération.
. Ouvrez le `.zip` fichier.
. Vérifiez que vous pouvez accéder au contenu, y compris au `Passwords.txt` fichier qui contient les nouveaux mots de passe de la console du nœud.
. Copiez le nouveau fichier de package de récupération(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: N'écrasez pas l'ancien package de récupération.

+
Vous devez sécuriser le fichier de récupération, car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données à partir du système StorageGRID .

. Cochez la case pour indiquer que vous avez téléchargé le nouveau package de récupération et vérifié le contenu.
. Sélectionnez *Continuer*.
+
StorageGRID met à jour le mot de passe pour chaque nœud.

+
S'il y a une erreur pendant le processus de mise à jour, la barre de progression indique le nombre de nœuds dont le mot de passe n'a pas pu être modifié.  Le système réessaiera automatiquement le processus sur tout nœud dont le mot de passe n'a pas été modifié.  Si le processus se termine et que certains nœuds n'ont toujours pas de mot de passe modifié, le bouton *Réessayer* apparaît.

. Si la mise à jour du mot de passe a échoué pour un ou plusieurs nœuds :
+
.. Vérifiez les messages d'erreur répertoriés dans le tableau.
.. Résolvez les problèmes.
.. Sélectionnez *Réessayer*.
+

NOTE: La tentative de nouveau modifie uniquement les mots de passe de la console de nœud sur les nœuds qui ont échoué lors des précédentes tentatives de changement de mot de passe.



. Lorsque la barre de progression indique qu'il ne reste aucune mise à jour, sélectionnez *Terminer*.
. Une fois les mots de passe de la console de nœud modifiés pour tous les nœuds, supprimez le<<download-current,premier package de récupération que vous avez téléchargé>> .

