---
permalink: admin/configuring-custom-server-certificate-for-storage-node.html 
sidebar: sidebar 
keywords: global S3 API certificate 
summary: 'Vous pouvez remplacer ou restaurer le certificat du serveur utilisé pour les connexions client S3 avec les nœuds de stockage ou pour les terminaux d"équilibrage de charge. Le certificat de serveur personnalisé de remplacement est spécifique à votre organisation.' 
---
= Configurer les certificats d'API S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez remplacer ou restaurer le certificat du serveur utilisé pour les connexions client S3 avec les nœuds de stockage ou pour les terminaux d'équilibrage de charge. Le certificat de serveur personnalisé de remplacement est spécifique à votre organisation.


TIP: Les détails SWIFT ont été supprimés de cette version du site doc. Voir https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-custom-server-certificate-for-storage-node.html["StorageGRID 11.8 : configurez les certificats d'API S3 et Swift"^].

.Description de la tâche
Par défaut, chaque nœud de stockage est doté d'un certificat de serveur X.509 signé par l'autorité de certification de la grille. Ces certificats signés par l'autorité de certification peuvent être remplacés par un seul certificat de serveur personnalisé commun et une clé privée correspondante.

Un seul certificat de serveur personnalisé est utilisé pour tous les nœuds de stockage. Vous devez donc spécifier le certificat comme un certificat générique ou multidomaine si les clients doivent vérifier le nom d'hôte lors de la connexion au noeud final de stockage. Définissez le certificat personnalisé de sorte qu'il corresponde à tous les nœuds de stockage de la grille.

Une fois la configuration terminée sur le serveur, vous devrez peut-être installer le certificat de l'autorité de certification Grid dans le client de l'API S3 que vous utiliserez pour accéder au système, selon l'autorité de certification racine (CA) que vous utilisez.


NOTE: Pour garantir que les opérations ne sont pas perturbées par un certificat de serveur défaillant, l'alerte *Expiration du certificat de serveur global pour l'API S3* est déclenchée lorsque le certificat du serveur racine est sur le point d'expirer.  Si nécessaire, vous pouvez voir quand le certificat actuel expire en sélectionnant *Configuration* > *Sécurité* > *Certificats* et en regardant la date d'expiration du certificat API S3 dans l'onglet Global.

Vous pouvez télécharger ou générer un certificat d'API S3 personnalisé.



== Ajoutez un certificat d'API S3 personnalisé

.Étapes
. Sélectionnez *Configuration* > *Sécurité* > *Certificats*.
. Dans l'onglet *Global*, sélectionnez *S3 API Certificate*.
. Sélectionnez *utiliser le certificat personnalisé*.
. Chargez ou générez le certificat.
+
[role="tabbed-block"]
====
.Télécharger le certificat
--
Téléchargez les fichiers de certificat de serveur requis.

.. Sélectionnez *Télécharger le certificat*.
.. Téléchargez les fichiers de certificat de serveur requis :
+
*** *Certificat de serveur* : fichier de certificat de serveur personnalisé (codé PEM).
*** *Clé privée de certificat* : fichier de clé privée de certificat de serveur personnalisé (`.key`).
+

NOTE: Les clés privées EC doivent être de 224 bits ou plus. Les clés privées RSA doivent être de 2048 bits ou plus.

*** *Paquet CA* : un fichier facultatif unique contenant les certificats de chaque autorité de délivrance de certificat intermédiaire. Le fichier doit contenir chacun des fichiers de certificat d'autorité de certification codés au PEM, concaténés dans l'ordre de la chaîne de certificats.


.. Sélectionnez les détails du certificat pour afficher les métadonnées et le PEM pour chaque certificat d'API S3 personnalisé téléchargé. Si vous avez téléchargé un bundle CA facultatif, chaque certificat s'affiche sur son propre onglet.
+
*** Sélectionnez *Télécharger le certificat* pour enregistrer le fichier de certificat ou sélectionnez *Télécharger le paquet CA* pour enregistrer le lot de certificats.
+
Spécifiez le nom du fichier de certificat et l'emplacement de téléchargement. Enregistrez le fichier avec l'extension `.pem`.

+
Par exemple : `storagegrid_certificate.pem`

*** Sélectionnez *Copy certificate PEM* ou *Copy CA bundle PEM* pour copier le contenu du certificat pour le coller ailleurs.


.. Sélectionnez *Enregistrer*.
+
Le certificat de serveur personnalisé est utilisé pour les nouvelles connexions client S3 suivantes.



--
.Générez un certificat
--
Générez les fichiers de certificat du serveur.

.. Sélectionnez *générer certificat*.
.. Spécifiez les informations de certificat :
+
[cols="1a,3a"]
|===
| Champ | Description 


 a| 
Nom de domaine
 a| 
Un ou plusieurs noms de domaine complets à inclure dans le certificat. Utilisez un * comme caractère générique pour représenter plusieurs noms de domaine.



 a| 
IP
 a| 
Une ou plusieurs adresses IP à inclure dans le certificat.



 a| 
Objet (facultatif)
 a| 
Objet X.509 ou nom distinctif (DN) du propriétaire du certificat.

Si aucune valeur n'est saisie dans ce champ, le certificat généré utilise le premier nom de domaine ou l'adresse IP comme nom commun de l'objet (CN).



 a| 
Jours valides
 a| 
Nombre de jours après la création, pendant lesquels le certificat expire.



 a| 
Ajouter des extensions d'utilisation de clé
 a| 
Si cette option est sélectionnée (par défaut et recommandée), l'utilisation des clés et les extensions d'utilisation des clés étendues sont ajoutées au certificat généré.

Ces extensions définissent l'objectif de la clé contenue dans le certificat.

*Remarque* : ne cochez pas cette case si vous rencontrez des problèmes de connexion avec des clients plus anciens lorsque les certificats incluent ces extensions.

|===
.. Sélectionnez *generate*.
.. Sélectionnez *Détails du certificat* pour afficher les métadonnées et le PEM du certificat API S3 personnalisé généré.
+
*** Sélectionnez *Télécharger le certificat* pour enregistrer le fichier de certificat.
+
Spécifiez le nom du fichier de certificat et l'emplacement de téléchargement. Enregistrez le fichier avec l'extension `.pem`.

+
Par exemple : `storagegrid_certificate.pem`

*** Sélectionnez *Copier le certificat PEM* pour copier le contenu du certificat pour le coller ailleurs.


.. Sélectionnez *Enregistrer*.
+
Le certificat de serveur personnalisé est utilisé pour les nouvelles connexions client S3 suivantes.



--
====
. Sélectionnez un onglet pour afficher les métadonnées du certificat de serveur StorageGRID par défaut, un certificat signé par l'autorité de certification qui a été chargé ou un certificat personnalisé qui a été généré.
+

NOTE: Après avoir téléchargé ou généré un nouveau certificat, autorisez jusqu'à un jour l'effacement des alertes d'expiration de certificat associées.

. Actualisez la page pour vous assurer que le navigateur Web est mis à jour.
. Après avoir ajouté un certificat d'API S3 personnalisé, la page de certificat d'API S3 affiche des informations détaillées sur le certificat d'API S3 personnalisé en cours d'utilisation. + vous pouvez télécharger ou copier le certificat PEM selon vos besoins.




== Restaurez le certificat d'API S3 par défaut

Vous pouvez revenir à l'utilisation du certificat d'API S3 par défaut pour les connexions client S3 aux nœuds de stockage. Toutefois, vous ne pouvez pas utiliser le certificat d'API S3 par défaut pour un terminal d'équilibreur de charge.

.Étapes
. Sélectionnez *Configuration* > *Sécurité* > *Certificats*.
. Dans l'onglet *Global*, sélectionnez *S3 API Certificate*.
. Sélectionnez *utiliser le certificat par défaut*.
+
Lorsque vous restaurez la version par défaut du certificat d'API S3 global, les fichiers de certificat de serveur personnalisé que vous avez configurés sont supprimés et ne peuvent pas être récupérés du système. Le certificat d'API S3 par défaut sera utilisé pour les nouvelles connexions client S3 suivantes aux nœuds de stockage.

. Sélectionnez *OK* pour confirmer l'avertissement et restaurer le certificat API S3 par défaut.
+
Si vous disposez de l'autorisation d'accès racine et que le certificat d'API S3 personnalisé a été utilisé pour les connexions de terminaux d'équilibrage de charge, une liste s'affiche indiquant les terminaux d'équilibrage de charge qui ne seront plus accessibles à l'aide du certificat d'API S3 par défaut. Accédez à link:../admin/configuring-load-balancer-endpoints.html["Configurer les terminaux de l'équilibreur de charge"] pour modifier ou supprimer les points finaux affectés.

. Actualisez la page pour vous assurer que le navigateur Web est mis à jour.




== Téléchargez ou copiez le certificat d'API S3

Vous pouvez enregistrer ou copier le contenu du certificat de l'API S3 pour l'utiliser ailleurs.

.Étapes
. Sélectionnez *Configuration* > *Sécurité* > *Certificats*.
. Dans l'onglet *Global*, sélectionnez *S3 API Certificate*.
. Sélectionnez l'onglet *Server* ou *CA bundle*, puis téléchargez ou copiez le certificat.
+
[role="tabbed-block"]
====
.Téléchargez le fichier de certificat ou le bundle CA
--
Téléchargez le fichier de certificat ou de bundle CA `.pem`. Si vous utilisez un bundle CA facultatif, chaque certificat du bundle s'affiche dans son propre sous-onglet.

.. Sélectionnez *Télécharger le certificat* ou *Télécharger le paquet CA*.
+
Si vous téléchargez un bundle CA, tous les certificats des onglets secondaires de l'offre CA sont téléchargés en un seul fichier.

.. Spécifiez le nom du fichier de certificat et l'emplacement de téléchargement. Enregistrez le fichier avec l'extension `.pem`.
+
Par exemple : `storagegrid_certificate.pem`



--
.Copie du certificat ou pack CA PEM
--
Copiez le texte du certificat pour le coller ailleurs. Si vous utilisez un bundle CA facultatif, chaque certificat du bundle s'affiche dans son propre sous-onglet.

.. Sélectionnez *Copy Certificate PEM* ou *Copy CA bundle PEM*.
+
Si vous copiez un bundle CA, tous les certificats des onglets secondaires de l'offre CA sont copiés ensemble.

.. Collez le certificat copié dans un éditeur de texte.
.. Enregistrez le fichier texte avec l'extension `.pem`.
+
Par exemple : `storagegrid_certificate.pem`



--
====


.Informations associées
* link:../s3/index.html["UTILISEZ L'API REST S3"]
* link:configuring-s3-api-endpoint-domain-names.html["Configuration des noms de domaine de terminaux S3"]

