---
permalink: admin/creating-enterprise-application-entra-id.html 
sidebar: sidebar 
keywords: enterprise application, entra id, single sign on, sso 
summary: 'Vous utilisez Entra ID pour créer une application d"entreprise pour chaque nœud d"administration de votre système.' 
---
= Créez des applications d'entreprise dans Entra ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez Entra ID pour créer une application d'entreprise pour chaque nœud d'administration de votre système.

.Avant de commencer
* Vous avez commencé à configurer l'authentification unique pour StorageGRID et vous avez sélectionné *Entra ID* comme type SSO.
* Vous avez link:../admin/configure-sso.html#enter-sandbox-mode["entrée en mode sandbox"] dans le Gestionnaire de grille.
* Vous disposez du *Nom d'application entreprise* pour chaque noeud d'administration de votre système. Vous pouvez copier ces valeurs à partir du tableau de détails du nœud d'administration de la page configurer SSO.
+

NOTE: Vous devez créer une application d'entreprise pour chaque nœud d'administration de votre système StorageGRID. La présence d'une application d'entreprise pour chaque nœud d'administration garantit que les utilisateurs peuvent se connecter et se déconnecter en toute sécurité à n'importe quel nœud d'administration.

* Vous avez de l'expérience dans la création d'applications d'entreprise dans Entra ID.
* Vous disposez d'un compte Azure avec un abonnement actif.
* Vous avez l'un des rôles suivants dans le compte Entra ID : Administrateur global, Administrateur d'application cloud, Administrateur d'application ou propriétaire du principal de service.




== Accéder à l'Entra ID

.Étapes
. Connectez-vous au https://portal.azure.com["Portail Azure"^].
. Accédez à https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["ID de l'Entra"^].
. Sélectionnez https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["Les applications d'entreprise"^].




== Créez des applications d'entreprise et enregistrez la configuration SSO de StorageGRID

Pour enregistrer la configuration SSO pour l'ID d'entreprise dans StorageGRID, vous devez utiliser l'ID d'entreprise pour créer une application d'entreprise pour chaque nœud d'administration. Vous allez copier les URL des métadonnées de fédération depuis Entra ID et les coller dans les champs *Federation metadata URL* correspondants de la page Configure SSO.

.Étapes
. Répétez les étapes suivantes pour chaque nœud d'administration.
+
.. Dans le volet applications d'entreprise Entra ID, sélectionnez *Nouvelle application*.
.. Sélectionnez *Créez votre propre application*.
.. Pour ce nom, entrez le *nom de l'application Enterprise* que vous avez copié à partir du tableau de détails du noeud d'administration sur la page configurer SSO.
.. Laissez le bouton radio *intégrer toute autre application que vous ne trouvez pas dans la galerie (hors galerie)* sélectionné.
.. Sélectionnez *Créer*.
.. Sélectionnez le lien *Get Started* dans *2. Configurez la case Single Sign On* ou sélectionnez le lien *Single Sign-on* dans la marge de gauche.
.. Sélectionnez la case *SAML*.
.. Copiez l'URL *App Federation Metadata URL*, que vous trouverez sous *étape 3 SAML Signing Certificate*.
.. Accédez à la page configurer SSO et collez l'URL dans le champ *Federation metadata URL* qui correspond au nom *Enterprise application name* que vous avez utilisé.


. Après avoir collé une URL de métadonnées de fédération pour chaque nœud d'administration et effectué toutes les autres modifications nécessaires à la configuration SSO, sélectionnez *Enregistrer* sur la page configurer SSO.




== Téléchargez les métadonnées SAML pour chaque nœud d'administration

Une fois la configuration SSO enregistrée, vous pouvez télécharger un fichier de métadonnées SAML pour chaque nœud d'administration de votre système StorageGRID.

.Étapes
. Répétez ces étapes pour chaque nœud d'administration.
+
.. Connectez-vous à StorageGRID à partir du nœud d'administration.
.. Sélectionnez *CONFIGURATION* > *contrôle d'accès* > *connexion unique*.
.. Sélectionnez le bouton pour télécharger les métadonnées SAML de ce nœud d'administration.
.. Enregistrez le fichier que vous allez télécharger dans Entra ID.






== Téléchargez les métadonnées SAML sur chaque application d'entreprise

Après avoir téléchargé un fichier de métadonnées SAML pour chaque nœud d'administration StorageGRID, effectuez les opérations suivantes dans l'Entra ID :

.Étapes
. Revenez au portail Azure.
. Répétez cette procédure pour chaque application d'entreprise :
+

NOTE: Vous devrez peut-être actualiser la page applications d'entreprise pour voir les applications que vous avez précédemment ajoutées dans la liste.

+
.. Accédez à la page Propriétés de l'application d'entreprise.
.. Définissez *affectation requise* sur *non* (sauf si vous souhaitez configurer séparément les affectations).
.. Accédez à la page Single Sign-on.
.. Terminez la configuration SAML.
.. Sélectionnez le bouton *Télécharger le fichier de métadonnées* et sélectionnez le fichier de métadonnées SAML que vous avez téléchargé pour le nœud d'administration correspondant.
.. Une fois le fichier chargé, sélectionnez *Enregistrer*, puis *X* pour fermer le volet. Vous revenez à la page configurer un Single Sign-on avec SAML.


. link:../admin/configure-sso.html#test-sso["Testez chaque application"].

