---
permalink: admin/deleting-tenant-account.html 
sidebar: sidebar 
keywords: tenant, delete, remove tenant 
summary: 'Vous pouvez supprimer un compte de tenant si vous souhaitez supprimer définitivement l"accès du locataire au système.' 
---
= Supprimer un compte locataire StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un compte de tenant si vous souhaitez supprimer définitivement l'accès du tenant au système.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez link:admin-group-permissions.html["autorisations d'accès spécifiques"].
* Vous avez supprimé tous les compartiments S3 et tous les objets associés au compte de locataire.
* Si le locataire est autorisé à utiliser les connexions de fédération de grilles, vous avez pris connaissance des points à prendre en link:../admin/grid-federation-manage-tenants.html["Suppression d'un locataire avec l'autorisation utiliser la connexion de fédération de grille"] compte. Les suppressions sont synchronisées, donc si un locataire est supprimé sur une grille, il sera supprimé sur toutes les grilles sélectionnées.


.Étapes
. Sélectionnez *Locataires*.
. Recherchez le ou les comptes de tenant que vous souhaitez supprimer.
+
Utilisez la zone de recherche pour rechercher un locataire par nom ou ID locataire.

. Pour supprimer plusieurs locataires, cochez les cases et sélectionnez *actions* > *Supprimer*.
. Pour supprimer un seul locataire, effectuez l'une des opérations suivantes :
+
** Cochez la case et sélectionnez *actions* > *Supprimer*.
** Sélectionnez le nom du locataire pour afficher la page des détails, puis sélectionnez *actions* > *Supprimer*.


. Sélectionnez *Oui*.

