---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 'Un compte de locataire vous permet d"utiliser l"API REST simple Storage Service \(S3\) pour stocker et récupérer des objets dans un système StorageGRID.' 
---
= Qu'est-ce qu'un compte de locataire ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un compte de locataire vous permet d'utiliser l'API REST simple Storage Service (S3) pour stocker et récupérer des objets dans un système StorageGRID.


TIP: Les détails SWIFT ont été supprimés de cette version du site doc. Voir https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8 : gestion des locataires"^].

En tant qu'administrateur du grid, vous créez et gérez les comptes de locataire utilisés par les clients S3 pour stocker et récupérer des objets.

Chaque compte de locataire comprend des groupes, utilisateurs, compartiments S3 et objets fédérés ou locaux.

Les comptes de tenant peuvent être utilisés pour isoler les objets stockés par des entités différentes. Par exemple, vous pouvez utiliser plusieurs comptes locataires pour l'une de ces utilisations :

* *Cas d'utilisation entreprise :* si vous gérez un système StorageGRID dans une application d'entreprise, vous pourriez vouloir isoler le stockage objet de la grille par les différents départements de votre organisation. Dans ce cas, vous pouvez créer des comptes de tenant pour le département Marketing, le service Customer support, le service des ressources humaines, etc.
+

NOTE: Si vous utilisez le protocole client S3, vous pouvez utiliser des compartiments S3 et des règles de compartiments pour isoler les objets entre les services d'une entreprise. Vous n'avez pas besoin d'utiliser de comptes de locataire. Voir les instructions d'implémentation link:../s3/bucket-and-group-access-policies.html["Compartiments S3 et règles de compartiments"] pour plus d'informations.

* *Cas d'utilisation de fournisseur de services :* si vous gérez un système StorageGRID en tant que fournisseur de services, vous pouvez isoler le stockage objet de la grille par les différentes entités qui loueront le stockage sur votre grille. Dans ce cas, vous créeriez des comptes de tenant pour la société A, la société B, la société C, etc.


Pour plus d'informations, voir link:../tenant/index.html["Utilisez un compte de locataire"].



== Comment créer un compte de locataire ?

Utilisez le gestionnaire de grille pour créer un compte de locataire. Lorsque vous créez un compte de locataire, vous spécifiez les informations suivantes :

* Informations de base comprenant le nom du locataire, le type de client (S3) et le quota de stockage facultatif.
* Autorisations pour le compte de locataire, par exemple si le compte de locataire peut utiliser les services de la plateforme S3, configurer son propre référentiel d'identité, utiliser S3 Select ou utiliser une connexion de fédération grid.
* Accès racine initial pour le locataire, selon que le système StorageGRID utilise des groupes et utilisateurs locaux, la fédération des identités ou l'authentification unique (SSO).


En outre, vous pouvez activer le paramètre de verrouillage des objets S3 pour le système StorageGRID si les comptes de locataires S3 doivent se conformer aux exigences réglementaires. Lorsque le verrouillage des objets S3 est activé, tous les comptes de locataires S3 peuvent créer et gérer des compartiments conformes.



== À quoi sert le gestionnaire de locataires ?

Une fois le compte de tenant créé, les utilisateurs de tenant peuvent se connecter au gestionnaire de tenant pour effectuer les tâches suivantes :

* Configurer la fédération des identités (sauf si le référentiel d'identité est partagé avec la grille)
* Gestion des groupes et des utilisateurs
* Utilisez la fédération grid pour le clone de compte et la réplication inter-grid
* Gestion des clés d'accès S3
* Création et gestion de compartiments S3
* Utilisez les services de plateforme S3
* Utiliser S3 Select
* Contrôle de l'utilisation du stockage



TIP: Les locataires S3 peuvent créer et gérer des clés d'accès S3 et des compartiments avec le gestionnaire de locataires. Ils doivent utiliser une application client S3 pour ingérer et gérer les objets. Voir link:../s3/index.html["UTILISEZ L'API REST S3"] pour plus de détails.
