---
permalink: admin/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, how to send asup message 
summary: 'Pour aider le support technique à résoudre les problèmes liés à votre système StorageGRID, vous pouvez déclencher manuellement l"envoi d"un pack AutoSupport.' 
---
= Déclencher manuellement un package AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour aider le support technique à résoudre les problèmes liés à votre système StorageGRID, vous pouvez déclencher manuellement l'envoi d'un pack AutoSupport.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous disposez de l'accès root ou de l'autorisation de configuration d'une autre grille.


.Étapes
. Sélectionnez *Support* > *Outils* > * AutoSupport*.
. Dans l'onglet *actions*, sélectionnez *Envoyer AutoSupport déclenché par l'utilisateur*.
+
StorageGRID tente d'envoyer un package AutoSupport au site de support NetApp .  Si la tentative réussit, les valeurs *Résultat le plus récent* et *Dernière heure de réussite* dans l'onglet *Résultats* sont mises à jour.  En cas de problème, la valeur *Résultat le plus récent* est mise à jour sur « Échec » et StorageGRID n'essaie pas d'envoyer à nouveau le package AutoSupport .

. Après 1 minute, actualisez la page AutoSupport dans votre navigateur pour accéder aux résultats les plus récents.



TIP: De plus, vous pouvezlink:../monitor/collecting-log-files-and-system-data.html["collecter des fichiers journaux et des données système plus complets"] et envoyez-les au site de support NetApp .
