---
permalink: admin/signing-in-to-grid-manager.html 
sidebar: sidebar 
keywords: grid manager, sign in, log in 
summary: 'Vous accédez à la page de connexion de Grid Manager en entrant le nom de domaine complet \(FQDN\) ou l"adresse IP d"un noeud d"administration dans la barre d"adresse d"un navigateur Web pris en charge.' 
---
= Connectez-vous au Grid Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous accédez à la page de connexion de Grid Manager en entrant le nom de domaine complet (FQDN) ou l'adresse IP d'un noeud d'administration dans la barre d'adresse d'un navigateur Web pris en charge.

Chaque système StorageGRID comprend un nœud d'administration principal et un nombre quelconque de nœuds d'administration non primaires. Vous pouvez vous connecter au Gestionnaire de grille sur n'importe quel noeud d'administration pour gérer le système StorageGRID. Toutefois, certaines procédures de maintenance ne peuvent être effectuées qu'à partir du nœud d'administration principal.



=== Se connecter au groupe haute disponibilité

Si des nœuds admin sont inclus dans un groupe haute disponibilité (HA), vous vous connectez à l'aide de l'adresse IP virtuelle du groupe haute disponibilité ou d'un nom de domaine complet mappé sur l'adresse IP virtuelle. Le nœud d'administration principal doit être sélectionné comme interface principale du groupe, de sorte que lorsque vous accédez à Grid Manager, vous y accédez sur le nœud d'administration principal, sauf si le nœud d'administration principal n'est pas disponible. Voir link:managing-high-availability-groups.html["Gérez les groupes haute disponibilité"].



=== Utiliser SSO

Les étapes de connexion sont légèrement différentes si link:how-sso-works.html["L'authentification unique (SSO) a été configurée"].



== Connectez-vous à Grid Manager sur le premier nœud d'administration

.Avant de commencer
* Vous disposez de vos identifiants de connexion.
* Vous utilisez un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Les cookies sont activés dans votre navigateur Web.
* Vous appartenez à un groupe d'utilisateurs disposant d'au moins une autorisation.
* Vous avez l'URL du Gestionnaire de grille :
+
`https://_FQDN_or_Admin_Node_IP_/`

+
Vous pouvez utiliser le nom de domaine complet, l'adresse IP d'un nœud d'administration ou l'adresse IP virtuelle d'un groupe haute disponibilité de nœuds d'administration.

+
Pour accéder au Gestionnaire de grille sur un port autre que le port par défaut pour HTTPS (443), indiquez le numéro de port dans l'URL :

+
`https://_FQDN_or_Admin_Node_IP:port_/`

+

NOTE: SSO n'est pas disponible sur le port Grid Manager restreint. Vous devez utiliser le port 443.



.Étapes
. Lancez un navigateur Web pris en charge.
. Dans la barre d'adresse du navigateur, entrez l'URL du Gestionnaire de grille.
. Si vous êtes invité à recevoir une alerte de sécurité, installez le certificat à l'aide de l'assistant d'installation du navigateur. Voir link:using-storagegrid-security-certificates.html["Gérer les certificats de sécurité"].
. Connectez-vous au Grid Manager.
+
L'écran de connexion qui s'affiche dépend de la configuration de l'authentification unique (SSO) pour StorageGRID.

+
[role="tabbed-block"]
====
.Pas d'utilisation de SSO
--
.. Saisissez votre nom d'utilisateur et votre mot de passe pour le Grid Manager.
.. Sélectionnez *connexion*.


--
.Utilisation de SSO
--
** Si StorageGRID utilise SSO pour la première fois que vous accédez à l'URL de ce navigateur :
+
... Sélectionnez *connexion*. Vous pouvez laisser le 0 dans le champ compte.
... Saisissez vos identifiants SSO standard sur la page de connexion SSO de votre entreprise. Par exemple :


** Si StorageGRID utilise SSO et que vous avez déjà accédé au Gestionnaire de grille ou à un compte de locataire :
+
... Entrez *0* (l'ID de compte du gestionnaire de grille) ou sélectionnez *Grid Manager* s'il apparaît dans la liste des comptes récents.
... Sélectionnez *connexion*.
... Connectez-vous à l'aide de vos identifiants SSO standard sur la page de connexion SSO de votre entreprise.




--
====


Lorsque vous êtes connecté, la page d'accueil du Gestionnaire de grille s'affiche, qui inclut le tableau de bord. Pour savoir quelles informations sont fournies, reportez-vous link:../monitor/viewing-dashboard.html["Affichez et gérez le tableau de bord"]à la section .



== Connectez-vous à un autre nœud d'administration

Procédez comme suit pour vous connecter à un autre nœud d'administration.

[role="tabbed-block"]
====
.Pas d'utilisation de SSO
--
.Étapes
. Dans la barre d'adresse du navigateur, entrez le nom de domaine complet ou l'adresse IP de l'autre noeud d'administration. Indiquez le numéro de port requis.
. Saisissez votre nom d'utilisateur et votre mot de passe pour le Grid Manager.
. Sélectionnez *connexion*.


--
.Utilisation de SSO
--
Si StorageGRID utilise SSO et que vous vous êtes connecté à un nœud d'administration, vous pouvez accéder à d'autres nœuds d'administration sans avoir à vous reconnecter.

.Étapes
. Entrez le nom de domaine complet ou l'adresse IP de l'autre noeud d'administration dans la barre d'adresse du navigateur.
. Si votre session SSO a expiré, saisissez à nouveau vos informations d'identification.


--
====