---
permalink: s3/deprecated-get-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated GET compliance requests 
summary: La demande DE conformité DE GET Bucket est obsolète. Cependant, vous pouvez continuer à utiliser cette demande pour déterminer les paramètres de conformité actuellement en vigueur pour un compartiment compatible existant. 
---
= Obsolète : RÉCUPÉRER la demande de conformité du compartiment
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La demande DE conformité DE GET Bucket est obsolète. Cependant, vous pouvez continuer à utiliser cette demande pour déterminer les paramètres de conformité actuellement en vigueur pour un compartiment compatible existant.

[NOTE]
====
La fonctionnalité de conformité StorageGRID disponible dans les versions précédentes d'StorageGRID est obsolète et a été remplacée par le verrouillage d'objet S3. Pour plus d'informations, consultez les documents suivants :

* link:../s3/use-s3-api-for-s3-object-lock.html["Utilisez l'API REST S3 pour configurer le verrouillage objet S3"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Base de connaissances NetApp : comment gérer des compartiments conformes aux ancienne génération dans StorageGRID 11.5"^]


====
Pour effectuer cette opération, vous devez disposer de l'autorisation s3:GetBucketCompliance ou être root de compte.



== Exemple de demande

Cet exemple de demande vous permet de déterminer les paramètres de conformité du compartiment nommé `mybucket`.

[listing, subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Exemple de réponse

Dans le XML de réponse, `<SGCompliance>` répertorie les paramètres de conformité en vigueur pour le compartiment. Cet exemple de réponse montre les paramètres de conformité d'un compartiment dans lequel chaque objet sera conservé pendant un an (525,600 minutes), à partir de l'ingestion de l'objet dans la grille. Il n'y a actuellement aucune retenue légale sur ce godet. Chaque objet sera automatiquement supprimé après un an.

[listing, subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
[cols="1a,2a"]
|===
| Nom | Description 


 a| 
RetentionPeriodMinutes
 a| 
Durée de conservation des objets ajoutés à ce compartiment, en minutes. La période de conservation commence lorsque l'objet est ingéré dans la grille.



 a| 
LegalHold
 a| 
* Vrai : ce compartiment est actuellement en attente légale. Les objets de ce compartiment ne peuvent pas être supprimés tant que la conservation légale n'est pas levée, même si leur période de conservation a expiré.
* Faux : ce godet n'est pas actuellement en attente légale. Les objets de ce compartiment peuvent être supprimés à la fin de leur période de conservation.




 a| 
Suppression automatique
 a| 
* Vrai : les objets de ce compartiment sont automatiquement supprimés lors de leur expiration, à moins que le compartiment ne soit soumis à une obligation légale.
* FALSE : les objets de ce compartiment ne sont pas supprimés automatiquement lorsque la période de conservation expire. Vous devez supprimer ces objets manuellement si vous devez les supprimer.


|===


== Réponses d'erreur

Si le compartiment n'a pas été créé pour être conforme, le code d'état HTTP de la réponse est `404 Not Found`, avec un code d'erreur S3 de `XNoSuchBucketCompliance`.
