---
permalink: s3/get-bucket-consistency-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket consistency 
summary: La demande de cohérence GET Bucket vous permet de déterminer la cohérence appliquée à un compartiment spécifique. 
---
= OPTIMISEZ la cohérence des compartiments
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La demande de cohérence GET Bucket vous permet de déterminer la cohérence appliquée à un compartiment spécifique.

La cohérence par défaut est définie pour garantir la lecture après écriture des objets nouvellement créés.

Pour effectuer cette opération, vous devez disposer de l'autorisation s3:GetBucketConsistency, ou être root de compte.



== Exemple de demande

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-consistency HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Réponse

Dans le XML de réponse, `<Consistency>` renvoie l'une des valeurs suivantes :

[cols="1a,2a"]
|===
| La cohérence | Description 


 a| 
tous
 a| 
Tous les nœuds reçoivent les données immédiatement, sinon la requête échoue.



 a| 
forte croissance mondiale
 a| 
Garantit une cohérence de lecture après écriture pour toutes les demandes client sur tous les sites.



 a| 
site fort
 a| 
Garantit la cohérence de lecture après écriture pour toutes les demandes client dans un site.



 a| 
lecture-après-nouvelle-écriture
 a| 
(Valeur par défaut) assure la cohérence en lecture après écriture des nouveaux objets et la cohérence des mises à jour des objets. Offre une haute disponibilité et une protection des données garanties. Recommandé dans la plupart des cas.



 a| 
disponibilité
 a| 
Assure la cohérence pour les nouveaux objets et les mises à jour d'objets. Pour les compartiments S3, utilisez uniquement si nécessaire (par exemple, pour un compartiment qui contient des valeurs de journal rarement lues ou pour les opérations HEAD ou GET sur des clés qui n'existent pas). Non pris en charge pour les compartiments FabricPool S3.

|===


== Exemple de réponse

[listing]
----
HTTP/1.1 200 OK
Date: Fri, 18 Sep 2020 01:02:18 GMT
Connection: CLOSE
Server: StorageGRID/11.5.0
x-amz-request-id: 12345
Content-Length: 127
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<Consistency xmlns="http://s3.storagegrid.com/doc/2015-02-01/">read-after-new-write</Consistency>
----
.Informations associées
link:consistency-controls.html["Valeurs de cohérence"]
