---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: 'L"opération UploadPart télécharge une pièce dans un téléchargement partitionné pour un objet.' 
---
= En-têtes de requête pris en charge et non pris en charge pour les opérations S3 UploadPart dans StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'opération UploadPart télécharge une pièce dans un téléchargement partitionné pour un objet.



[[supported-request-headers]]
== En-têtes de demande pris en charge

Les en-têtes de requête suivants sont pris en charge :

* En-têtes de requête de somme de contrôle :
+
--
** `x-amz-checksum-crc32`
** `x-amz-checksum-crc32c`
** `x-amz-checksum-crc64nvme`
** `x-amz-checksum-sha256`


--
+
Si vous avez spécifié une somme de contrôle CRC-32, CRC-32C, CRC-64/NVME ou SHA-256 lors de la requête CreateMultipartUpload, vous devez également inclure l'en-tête de requête de somme de contrôle dans chaque requête UploadPart.

+

NOTE: Si une requête CreateMultipartUpload ne spécifie pas de somme de contrôle, StorageGRID ne calcule pas de somme de contrôle CRC-64/NVME par défaut pour un objet.

* `Content-Length`
* `Content-MD5`




[[request-headers-for-server-side-encryption]]
== Demander des en-têtes pour le cryptage côté serveur

Si vous avez spécifié le cryptage SSE-C pour la demande CreateMultipartUpload, vous devez également inclure les en-têtes de requête suivants dans chaque demande UploadPart :

* `x-amz-server-side-encryption-customer-algorithm`: Spécifiez `AES256`.
* `x-amz-server-side-encryption-customer-key`: Spécifiez la même clé de cryptage que celle que vous avez fournie dans la demande CreateMultipartUpload.
* `x-amz-server-side-encryption-customer-key-MD5`: Spécifiez le même résumé MD5 que celui que vous avez fourni dans la demande CreateMultipartUpload.



CAUTION: Les clés de chiffrement que vous fournissez ne sont jamais stockées. Si vous perdez une clé de chiffrement, vous perdez l'objet correspondant. Avant d'utiliser des clés fournies par le client pour sécuriser les données d'objet, consultez les considérations de la section link:using-server-side-encryption.html["Utilisez le cryptage côté serveur"].



[[unsupported-request-headers]]
== En-têtes de requête non pris en charge

Les en-têtes de demande suivants ne sont pas pris en charge :

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`
* `x-amz-checksum-md5`
* `x-amz-checksum-sha1`
* `x-amz-checksum-sha512`
* `x-amz-checksum-xxhash3`
* `x-amz-checksum-xxhash64`
* `x-amz-checksum-xxhash128`




[[versioning]]
== Gestion des versions

Le téléchargement partitionné est constitué de différentes opérations permettant de lancer le téléchargement, de répertorier les téléchargements, de télécharger des pièces, d'assembler les pièces téléchargées et de terminer le téléchargement. Les objets sont créés (et versionnés le cas échéant) lorsque l'opération CompleteMultipartUpload est exécutée.
