---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: Vous pouvez récupérer les fichiers journaux StorageGRID et les données système, y compris les données de configuration, et les envoyer au support technique. 
---
= Collecte de fichiers journaux et de données système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez récupérer les fichiers journaux StorageGRID et les données système, y compris les données de configuration, et les envoyer au support technique.

.Avant de commencer
* Vous êtes connecté au gestionnaire de grille sur n'importe quel nœud d'administration à l'aide d'unlink:../admin/web-browser-requirements.html["navigateur web pris en charge"] .
* Vous avez link:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"].
* Vous avez la phrase secrète pour le provisionnement.


.Description de la tâche
Utilisez le gestionnaire de grille pour collecterlink:logs-files-reference.html["fichiers journaux"] , les données système et les données de configuration de n’importe quel nœud de grille pour la période que vous sélectionnez.  Les données sont collectées et archivées dans un `.tar.gz` fichier que vous pouvez ensuite télécharger sur votre ordinateur local ou envoyer au support technique.

En option, vous pouvez modifier la destination des journaux d'audit et envoyer les informations d'audit à un serveur syslog externe.  Les journaux locaux des enregistrements d'audit continuent d'être générés et stockés lorsqu'un serveur syslog externe est configuré. Voir link:../monitor/configure-log-management.html["Configurer la gestion des journaux et le serveur syslog externe"] .

.Étapes
. Sélectionnez *Support* > *Outils* > *Collecte de journaux*.  Un tableau de nœuds s'affiche.
. Sélectionnez les nœuds de grille pour lesquels vous souhaitez collecter les fichiers journaux.
+
Vous pouvez trier par nom de nœud, site et type de nœud.  Les colonnes Type de site et Type de nœud contiennent des filtres permettant de sélectionner des sites et des types de nœuds individuels.

. Sélectionnez *Continuer*.
. Sélectionnez la plage de dates et d’heures des données à inclure dans les fichiers journaux.
+
Si vous sélectionnez une période très longue ou collectez les journaux de tous les nœuds d'une grande grille, l'archive des journaux peut devenir trop volumineuse pour être stockée sur un nœud ou trop volumineuse pour être collectée par un nœud d'administration pour téléchargement.  Si l’un ou l’autre scénario se produit, redémarrez la collecte des journaux avec un ensemble de données plus petit.

. Sélectionnez les types de journaux que vous souhaitez collecter.
+
** *Journaux d'application* : journaux spécifiques à l'application que le support technique utilise le plus fréquemment pour le dépannage.  Les journaux collectés sont un sous-ensemble des journaux d’application disponibles.
** *Journaux d'audit* : Journaux contenant les messages d'audit générés pendant le fonctionnement normal du système.
** *Trace réseau* : Journaux utilisés pour le débogage du réseau.
** *Base de données Prometheus* : métriques de séries chronologiques des services sur tous les nœuds.


. Vous pouvez également utiliser la zone de texte *Notes* pour saisir des notes sur les fichiers journaux que vous collectez.
+
Vous pouvez utiliser ces notes pour fournir des informations de support technique sur le problème qui vous a demandé de collecter les fichiers journaux. Vos notes sont ajoutées à un fichier appelé `info.txt`, ainsi qu'à d'autres informations sur la collection de fichiers journaux. Le `info.txt` fichier est enregistré dans le package d'archivage du fichier journal.

. Dans la zone de texte *Phrase secrète de provisionnement*, saisissez la phrase secrète de provisionnement de votre système StorageGRID .
. Sélectionnez *Collecter les journaux*.
+
Vous pouvez utiliser la page de collecte des journaux pour surveiller la progression de la collecte des fichiers journaux pour chaque nœud de grille.

+
Si vous recevez un message d'erreur sur la taille du journal, essayez de collecter les journaux pour une période plus courte ou pour moins de nœuds.

. Si la collecte des journaux échoue :
+
** Si un message « Échec de la collecte des journaux » s'affiche, vous pouvez réessayer la collecte des journaux ou terminer la session sans réessayer.
** Si un message « Échec partiel de la collecte des journaux » s'affiche, vous pouvez réessayer la collecte des journaux, terminer la session, télécharger le fichier journal partiel ou envoyer le fichier journal partiel à AutoSupport.


. Une fois la collecte du fichier journal terminée :
+
** Sélectionnez *Télécharger* pour télécharger le `.tar.gz` déposer.
** Sélectionnez *Envoyer à AutoSupport* pour envoyer le `.tar.gz` fichier au support technique.
+
Le `.tar.gz` le fichier contient tous les fichiers journaux de tous les nœuds de grille où la collecte des journaux a réussi.  Le combiné `.tar.gz` le fichier contient une archive de fichier journal pour chaque nœud de grille.

+
Le sujet du package AutoSupport est `USER_TRIGGERED_SUPPORT_BUNDLE` .



. Sélectionnez *Terminer*.
+

CAUTION: Le `.tar.gz` le fichier est supprimé lorsque vous sélectionnez *Terminer*.  Assurez-vous de télécharger ou d’envoyer le fichier en premier.


