---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: Vous pouvez récupérer les fichiers journaux StorageGRID et les données système, y compris les données de configuration, et les envoyer au support technique. 
---
= Collecte de fichiers journaux et de données système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez récupérer les fichiers journaux StorageGRID et les données système, y compris les données de configuration, et les envoyer au support technique.

.Avant de commencer
* Vous êtes connecté au gestionnaire de grille sur le nœud d'administration principal à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez link:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"].
* Vous avez la phrase secrète pour le provisionnement.


.Description de la tâche
Utilisez le gestionnaire de grille pour collecter link:logs-files-reference.html["fichiers journaux"], les données système et les données de configuration de n'importe quel nœud de grille pour la période que vous sélectionnez. Les données sont collectées et archivées dans un `.tar.gz` fichier que vous pouvez ensuite télécharger sur votre ordinateur local ou envoyer au support technique.

Vous pouvez également modifier la destination des journaux d'audit et envoyer des informations d'audit à un serveur syslog externe. Les journaux locaux des enregistrements d'audit continuent à être générés et stockés lorsqu'un serveur syslog externe est configuré. Voir link:../monitor/configure-audit-messages.html["Configurer les messages d'audit et le serveur syslog externe"].

.Étapes
. Sélectionnez *SUPPORT* > *Outils* > *journaux*. Un tableau de nœuds s'affiche.
. Sélectionnez les nœuds de grille pour lesquels vous souhaitez collecter les fichiers journaux.
+
Vous pouvez trier par nom de nœud, site et type de nœud. Les colonnes site et Type de nœud contiennent des filtres permettant de sélectionner des sites et des types de nœuds individuels.

. Sélectionnez *Continuer*.
. Sélectionnez la date et l'heure des données à inclure dans les fichiers journaux.
+
Si vous sélectionnez une période très longue ou que vous collectez des journaux de tous les nœuds d'un grand grid, l'archivage des journaux risque de devenir trop volumineux pour être stocké sur un nœud, ou trop volumineux pour être collecté sur le nœud d'administration principal pour le téléchargement. Si l'un ou l'autre scénario se produit, redémarrez la collecte des journaux avec un ensemble de données plus petit.

. Sélectionnez les types de journaux que vous souhaitez collecter.
+
** *Journaux d'application* : journaux spécifiques à l'application que le support technique utilise le plus fréquemment pour le dépannage. Les journaux collectés sont un sous-ensemble des journaux d'application disponibles.
** *Journaux d'audit* : journaux contenant les messages d'audit générés pendant le fonctionnement normal du système.
** *Trace réseau* : journaux utilisés pour le débogage réseau.
** *Base de données Prometheus* : métriques de séries chronologiques des services sur tous les nœuds.


. Vous pouvez également utiliser la zone de texte *Notes* pour saisir des notes sur les fichiers journaux que vous recueillez.
+
Vous pouvez utiliser ces notes pour fournir des informations de support technique sur le problème qui vous a demandé de collecter les fichiers journaux. Vos notes sont ajoutées à un fichier appelé `info.txt`, ainsi qu'à d'autres informations sur la collection de fichiers journaux. Le `info.txt` fichier est enregistré dans le package d'archivage du fichier journal.

. Dans la zone de texte *phrase de passe de provisionnement*, entrez la phrase de passe de provisionnement pour votre système StorageGRID.
. Sélectionnez *collecter les journaux*.
+
Vous pouvez utiliser la page journaux pour surveiller la progression de la collecte des fichiers journaux pour chaque nœud de la grille.

+
Si vous recevez un message d'erreur sur la taille du journal, essayez de collecter les journaux pour une période plus courte ou pour moins de nœuds.

. Si la collecte du journal échoue :
+
** Si un message « échec de la collecte du journal » s'affiche, vous pouvez réessayer la collecte du journal ou terminer la session sans réessayer.
** Si le message « échec partiel de la collecte des journaux » s'affiche, vous pouvez réessayer la collecte des journaux, terminer la session, télécharger le fichier journal partiel ou envoyer le fichier journal partiel à AutoSupport.


. Lorsque la collecte des fichiers journaux est terminée :
+
** Sélectionnez *Télécharger* pour télécharger le `.tar.gz` fichier.
** Sélectionnez *Envoyer à AutoSupport* pour envoyer le `.tar.gz` fichier au support technique.
+
Le `.tar.gz` fichier contient tous les fichiers journaux de tous les nœuds de grille où la collecte des journaux a réussi. Le fichier combiné `.tar.gz` contient une archive de fichier journal pour chaque nœud de grille.

+
Le sujet du paquet AutoSupport est `USER_TRIGGERED_SUPPORT_BUNDLE`.



. Sélectionnez *Terminer*.
+

CAUTION: Le `.tar.gz` fichier est supprimé lorsque vous sélectionnez *Terminer*. Assurez-vous d'abord de télécharger ou d'envoyer le fichier.


