---
permalink: monitor/configure-audit-messages.html 
sidebar: sidebar 
keywords: audit messages, audit level, external syslog server, log destinations 
summary: 'Vous pouvez configurer un certain nombre de paramètres liés aux messages d"audit. Vous pouvez ajuster le nombre de messages d"audit enregistrés, définir les en-têtes de requête HTTP que vous souhaitez inclure dans les messages d"audit de lecture et d"écriture des clients, configurer un serveur syslog externe et spécifier l"emplacement d"envoi des journaux d"audit, des journaux d"événements de sécurité et des journaux logiciels StorageGRID.' 
---
= Configurer les messages d'audit et le serveur syslog externe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer un certain nombre de paramètres liés aux messages d'audit. Vous pouvez ajuster le nombre de messages d'audit enregistrés, définir les en-têtes de requête HTTP que vous souhaitez inclure dans les messages d'audit de lecture et d'écriture des clients, configurer un serveur syslog externe et spécifier l'emplacement d'envoi des journaux d'audit, des journaux d'événements de sécurité et des journaux logiciels StorageGRID.

Les messages d'audit et les journaux enregistrent les activités du système et les événements de sécurité. Ils constituent les outils essentiels de surveillance et de dépannage. Tous les nœuds StorageGRID génèrent des messages d'audit et des journaux pour suivre l'activité et les événements du système.

Vous pouvez également configurer un serveur syslog externe pour enregistrer les informations d'audit à distance. L'utilisation d'un serveur externe réduit l'impact sur les performances de la journalisation des messages d'audit sans réduire l'exhaustivité des données d'audit. Un serveur syslog externe est particulièrement utile si vous disposez d'une grande grille, utilisez plusieurs types d'applications S3 ou souhaitez conserver toutes les données d'audit. Voir link:../monitor/considerations-for-external-syslog-server.html["Configurer les messages d'audit et le serveur syslog externe"] pour plus de détails.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez le link:../admin/admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Si vous prévoyez de configurer un serveur syslog externe, vous avez examiné le système  et vous link:../monitor/considerations-for-external-syslog-server.html["considérations relatives à l'utilisation d'un serveur syslog externe"]êtes assuré que le serveur dispose d'une capacité suffisante pour recevoir et stocker les fichiers journaux.
* Si vous prévoyez de configurer un serveur syslog externe à l'aide du protocole TLS ou RELP/TLS, vous disposez des certificats CA serveur et client requis et de la clé privée client.




== Modifier les niveaux des messages d'audit

Vous pouvez définir un niveau d'audit différent pour chacune des catégories de messages suivantes dans le journal d'audit :

[cols="1a,1a,1a"]
|===
| Catégorie de vérification | Paramètre par défaut | Plus d'informations 


 a| 
Système
 a| 
Normale
 a| 
link:../audit/system-audit-messages.html["Messages d'audit système"]



 a| 
Stockage
 a| 
Erreur
 a| 
link:../audit/object-storage-audit-messages.html["Messages d'audit du stockage objet"]



 a| 
Gestion
 a| 
Normale
 a| 
link:../audit/management-audit-message.html["Message d'audit de gestion"]



 a| 
Lectures du client
 a| 
Normale
 a| 
link:../audit/client-read-audit-messages.html["Messages d'audit de lecture du client"]



 a| 
Écritures des clients
 a| 
Normale
 a| 
link:../audit/client-write-audit-messages.html["Écrire des messages d'audit client"]



 a| 
ILM
 a| 
Normale
 a| 
link:../audit/ilm-audit-messages.html["Messages d'audit ILM"]



 a| 
Réplication entre plusieurs grilles
 a| 
Erreur
 a| 
link:../audit/cgrr-cross-grid-replication-request.html["CGRR : demande de réplication croisée"]

|===

NOTE: Ces valeurs par défaut s'appliquent si vous avez installé StorageGRID à l'origine à l'aide de la version 10.3 ou ultérieure. Si vous avez initialement utilisé une version antérieure de StorageGRID, la valeur par défaut pour toutes les catégories est Normal.


NOTE: Durant les mises à niveau, les configurations des niveaux d'audit ne seront pas effectives immédiatement.

.Étapes
. Sélectionnez *CONFIGURATION* > *surveillance* > *serveur d'audit et syslog*.
. Pour chaque catégorie de message d'audit, sélectionnez un niveau d'audit dans la liste déroulante :
+
[cols="1a,3a"]
|===
| Niveau d'audit | Description 


 a| 
Arrêt
 a| 
Aucun message d'audit de la catégorie n'est enregistré.



 a| 
Erreur
 a| 
Seuls les messages d'erreur sont consignés--les messages d'audit pour lesquels le code de résultat n'a pas été « réussi » (CMC).



 a| 
Normale
 a| 
Les messages transactionnels standard sont consignés--les messages répertoriés dans ces instructions pour la catégorie.



 a| 
Débogage
 a| 
Obsolète. Ce niveau se comporte de la même manière que le niveau d'audit normal.

|===
+
Les messages inclus pour tout niveau particulier incluent ceux qui seraient consignés aux niveaux supérieurs. Par exemple, le niveau Normal inclut tous les messages d'erreur.

+

NOTE: Si vous n'avez pas besoin d'un enregistrement détaillé des opérations de lecture du client pour vos applications S3, vous pouvez éventuellement définir le paramètre *lecture du client* sur *erreur* pour diminuer le nombre de messages d'audit enregistrés dans le journal d'audit.

. Sélectionnez *Enregistrer*.
+
Une bannière verte indique que votre configuration a été enregistrée.





== Définissez les en-têtes de requête HTTP

Vous pouvez éventuellement définir les en-têtes de requête HTTP que vous souhaitez inclure dans les messages d'audit de lecture et d'écriture du client. Ces en-têtes de protocole s'appliquent uniquement aux requêtes S3.

.Étapes
. Dans la section *en-têtes de protocole d'audit*, définissez les en-têtes de requête HTTP que vous souhaitez inclure dans les messages d'audit de lecture et d'écriture du client.
+
Utilisez un astérisque (\*) comme caractère générique pour qu'il corresponde à zéro ou à plusieurs caractères. Utilisez la séquence d'échappement (\*) pour faire correspondre un astérisque littéral.

. Sélectionnez *Ajouter un autre en-tête* pour créer des en-têtes supplémentaires, si nécessaire.
+
Lorsque des en-têtes HTTP sont trouvés dans une requête, ils sont inclus dans le message d'audit sous le champ HTRH.

+

NOTE: Les en-têtes de requête de protocole d'audit ne sont consignés que si le niveau d'audit pour *lecture client* ou *écriture client* n'est pas *off*.

. Sélectionnez *Enregistrer*
+
Une bannière verte indique que votre configuration a été enregistrée.





== [[use-external-syslog-Server]]utilisez un serveur syslog externe

Vous pouvez également configurer un serveur syslog externe pour enregistrer les journaux d'audit, les journaux d'application et les journaux d'événements de sécurité dans un emplacement en dehors de votre grille.


NOTE: Si vous ne souhaitez pas utiliser de serveur syslog externe, ignorez cette étape et passez à <<select-audit-information-destinations,Sélectionnez les destinations des informations d'audit>>l' .


TIP: Si les options de configuration disponibles dans cette procédure ne sont pas suffisamment flexibles pour répondre à vos besoins, des options de configuration supplémentaires peuvent être appliquées à l'aide des `audit-destinations` noeuds finaux, qui se trouvent dans la section API privée de la link:../admin/using-grid-management-api.html["API de gestion du grid"]. Par exemple, vous pouvez utiliser l'API si vous souhaitez utiliser différents serveurs syslog pour différents groupes de nœuds.



=== Entrez les informations syslog

Accédez à l'assistant configurer le serveur syslog externe et fournissez les informations dont StorageGRID a besoin pour accéder au serveur syslog externe.

.Étapes
. Sur la page Audit and syslog Server, sélectionnez *Configure External syslog Server*. Ou, si vous avez déjà configuré un serveur syslog externe, sélectionnez *Modifier le serveur syslog externe*.
+
L'assistant configurer le serveur syslog externe s'affiche.

. Pour l'étape *Entrez les informations syslog* de l'assistant, entrez un nom de domaine complet valide ou une adresse IPv4 ou IPv6 pour le serveur syslog externe dans le champ *Host*.
. Entrez le port de destination sur le serveur syslog externe (doit être un entier compris entre 1 et 65535). Le port par défaut est 514.
. Sélectionnez le protocole utilisé pour envoyer les informations d'audit au serveur syslog externe.
+
Il est recommandé d'utiliser *TLS* ou *RELP/TLS*. Vous devez télécharger un certificat de serveur pour utiliser l'une de ces options. L'utilisation de certificats permet de sécuriser les connexions entre votre grille et le serveur syslog externe. Pour plus d'informations, voir link:../admin/using-storagegrid-security-certificates.html["Gérer les certificats de sécurité"].

+
Toutes les options de protocole requièrent la prise en charge par le serveur syslog externe ainsi que sa configuration. Vous devez choisir une option compatible avec le serveur syslog externe.

+

NOTE: Le protocole RELP (fiable Event Logging Protocol) étend la fonctionnalité du protocole syslog afin de fournir des messages d'événement fiables. L'utilisation de RELP peut aider à éviter la perte d'informations d'audit si votre serveur syslog externe doit redémarrer.

. Sélectionnez *Continuer*.
. [[attach-certificate]]si vous avez sélectionné *TLS* ou *RELP/TLS*, téléchargez les certificats de l'autorité de certification du serveur, le certificat du client et la clé privée du client.
+
.. Sélectionnez *Parcourir* pour le certificat ou la clé que vous souhaitez utiliser.
.. Sélectionnez le certificat ou le fichier de clé.
.. Sélectionnez *Ouvrir* pour charger le fichier.
+
Une coche verte s'affiche en regard du nom du fichier de certificat ou de clé, vous informant qu'il a été téléchargé avec succès.



. Sélectionnez *Continuer*.




=== Gérer le contenu du journal système

Vous pouvez sélectionner les informations à envoyer au serveur syslog externe.

.Étapes
. Pour l'étape *gérer le contenu syslog* de l'assistant, sélectionnez chaque type d'informations d'audit que vous souhaitez envoyer au serveur syslog externe.
+
** *Envoyer les journaux d'audit* : envoie les événements StorageGRID et les activités système
** *Envoyer des événements de sécurité* : envoie des événements de sécurité tels qu'une tentative d'ouverture de session par un utilisateur non autorisé ou une ouverture de session par un utilisateur en tant que root
** *Envoyer les journaux d'application* : envoie des messages link:../monitor/storagegrid-software-logs.html["Fichiers journaux du logiciel StorageGRID"] utiles pour le dépannage, notamment :
+
*** `bycast-err.log`
*** `bycast.log`
*** `jaeger.log`
*** `nms.log` (Nœuds d'administration uniquement)
*** `prometheus.log`
*** `raft.log`
*** `hagroups.log`


** *Envoyer les journaux d'accès* : envoie les journaux d'accès HTTP pour les demandes externes à Grid Manager, tenant Manager, les noeuds finaux configurés de l'équilibreur de charge et les demandes de fédération de grille à partir de systèmes distants.


. Utilisez les menus déroulants pour sélectionner la gravité et l'établissement (type de message) pour chaque catégorie d'informations d'audit que vous souhaitez envoyer.
+
La définition de la gravité et des valeurs de l'établissement peut vous aider à regrouper les journaux de manière personnalisable pour une analyse plus facile.

+
.. Pour *gravité*, sélectionnez *passe-système* ou sélectionnez une valeur de gravité comprise entre 0 et 7.
+
Si vous sélectionnez une valeur, la valeur sélectionnée sera appliquée à tous les messages de ce type. Les informations sur les différentes gravité seront perdues si vous remplacez la gravité par une valeur fixe.

+
[cols="1a,3a"]
|===
| Gravité | Description 


 a| 
Passe-système
 a| 
Chaque message envoyé au syslog externe a la même valeur de gravité que lorsqu'il a été connecté localement au nœud :

*** Pour les journaux d'audit, la gravité est « info ».
*** Pour les événements de sécurité, les valeurs de gravité sont générées par la distribution Linux sur les nœuds.
*** Pour les journaux d'application, les niveaux de gravité varient entre « info » et « avis », selon le problème. Par exemple, l'ajout d'un serveur NTP et la configuration d'un groupe HA donnent la valeur « INFO », tandis que l'arrêt délibéré du service SSM ou RSM donne la valeur « notification ».
*** Pour les journaux d'accès, la gravité est « info ».




 a| 
0
 a| 
Urgence : le système est inutilisable



 a| 
1
 a| 
Alerte : une action doit être effectuée immédiatement



 a| 
2
 a| 
Critique : conditions critiques



 a| 
3
 a| 
Erreur : conditions d'erreur



 a| 
4
 a| 
Avertissement : conditions d'avertissement



 a| 
5
 a| 
Remarque : condition normale mais significative



 a| 
6
 a| 
Information : messages d'information



 a| 
7
 a| 
Débogage : messages de niveau débogage

|===
.. Pour *facilty*, sélectionnez *Passthrough* ou sélectionnez une valeur d'installation comprise entre 0 et 23.
+
Si vous sélectionnez une valeur, elle sera appliquée à tous les messages de ce type. Les informations concernant les différents sites seront perdues si vous remplacez l'établissement par une valeur fixe.

+
[cols="1a,3a"]
|===
| Installation | Description 


 a| 
Passe-système
 a| 
Chaque message envoyé au syslog externe a la même valeur d'installation que lorsqu'il a été connecté localement au nœud :

*** Pour les journaux d'audit, la fonction envoyée au serveur syslog externe est « local7 ».
*** Pour les événements de sécurité, les valeurs d'installation sont générées par la distribution linux sur les nœuds.
*** Pour les journaux d'application, les journaux d'application envoyés au serveur syslog externe ont les valeurs suivantes :
+
**** `bycast.log`: utilisateur ou démon
**** `bycast-err.log`: utilisateur, démon, local3 ou local4
**** `jaeger.log`: local2
**** `nms.log`: local3
**** `prometheus.log`: local4
**** `raft.log`: local5
**** `hagroups.log`: local6


*** Pour les journaux d'accès, la fonction envoyée au serveur syslog externe est "local0".




 a| 
0
 a| 
kern (messages du noyau)



 a| 
1
 a| 
utilisateur (messages de niveau utilisateur)



 a| 
2
 a| 
e-mail



 a| 
3
 a| 
démon (démons système)



 a| 
4
 a| 
auth (messages de sécurité/d'autorisation)



 a| 
5
 a| 
syslog (messages générés en interne par syslogd)



 a| 
6
 a| 
lpr (sous-système d'imprimante ligne)



 a| 
7
 a| 
news (sous-système d'informations réseau)



 a| 
8
 a| 
UCP



 a| 
9
 a| 
cron (démon d'horloge)



 a| 
10
 a| 
sécurité (messages de sécurité/d'autorisation)



 a| 
11
 a| 
FTP



 a| 
12
 a| 
NTP



 a| 
13
 a| 
audit journal (audit du journal)



 a| 
14
 a| 
alerte journal (alerte de journal)



 a| 
15
 a| 
horloge (démon d'horloge)



 a| 
16
 a| 
local0



 a| 
17
 a| 
local1



 a| 
18
 a| 
local2



 a| 
19
 a| 
local3



 a| 
20
 a| 
local4



 a| 
21
 a| 
local5



 a| 
22
 a| 
local6



 a| 
23
 a| 
local7

|===


. Sélectionnez *Continuer*.




=== Envoyer des messages de test

Avant de commencer à utiliser un serveur syslog externe, vous devez demander à tous les nœuds de votre grille d'envoyer des messages de test au serveur syslog externe. Ces messages de test vous aideront à valider l'intégralité de votre infrastructure de collecte de journaux avant de vous engager à envoyer des données au serveur syslog externe.


CAUTION: N'utilisez pas la configuration du serveur syslog externe tant que vous n'avez pas confirmé que le serveur syslog externe a reçu un message test de chaque nœud de votre grille et que le message a été traité comme prévu.

.Étapes
. Si vous ne souhaitez pas envoyer de messages de test parce que vous êtes certain que votre serveur syslog externe est correctement configuré et peut recevoir des informations d'audit de tous les nœuds de votre grille, sélectionnez *Ignorer et terminer*.
+
Une bannière verte indique que la configuration a été enregistrée.

. Sinon, sélectionnez *Envoyer les messages de test* (recommandé).
+
Les résultats de test apparaissent en permanence sur la page jusqu'à ce que vous arrêiez le test. Pendant que le test est en cours, vos messages d'audit continuent d'être envoyés à vos destinations précédemment configurées.

. Si vous recevez des erreurs, corrigez-les et sélectionnez à nouveau *Envoyer des messages de test*.
+
Reportez-vous link:../troubleshoot/troubleshooting-syslog-server.html["Dépanner un serveur syslog externe"] à pour résoudre les erreurs.

. Attendez qu'une bannière verte indique que tous les nœuds ont réussi le test.
. Vérifiez votre serveur syslog pour déterminer si les messages de test sont reçus et traités comme prévu.
+

NOTE: Si vous utilisez UDP, vérifiez l'ensemble de votre infrastructure de collecte de journaux. Le protocole UDP ne permet pas une détection d'erreur aussi rigoureuse que les autres protocoles.

. Sélectionnez *Arrêter et Terminer*.
+
Vous revenez à la page *Audit and syslog Server*. Une bannière verte indique que la configuration du serveur syslog a été enregistrée.

+

NOTE: Les informations d'audit StorageGRID ne sont pas envoyées au serveur syslog externe tant que vous ne sélectionnez pas une destination incluant le serveur syslog externe.





== Sélectionnez les destinations des informations d'audit

Vous pouvez spécifier l'emplacement d'envoi des journaux d'audit, des journaux d'événements de sécurité etlink:../monitor/storagegrid-software-logs.html["Journaux du logiciel StorageGRID"].

[NOTE]
====
StorageGRID utilise par défaut les destinations d'audit de nœud local et stocke les informations d'audit dans `/var/local/log/localaudit.log`.

Lors de l'utilisation de `/var/local/log/localaudit.log`, les entrées du journal d'audit Grid Manager et tenant Manager peuvent être envoyées à un nœud de stockage. Vous pouvez trouver le nœud qui contient les entrées les plus récentes à l'aide de la `run-each-node --parallel "zgrep MGAU /var/local/log/localaudit.log | tail"` commande.

Certaines destinations ne sont disponibles que si vous avez configuré un serveur syslog externe.

====
.Étapes
. Sur la page serveur d'audit et syslog, sélectionnez la destination des informations d'audit.
+

TIP: *Les nœuds locaux uniquement* et *le serveur syslog externe* fournissent généralement de meilleures performances.

+
[cols="1a,2a"]
|===
| Option | Description 


 a| 
Nœuds locaux uniquement (par défaut)
 a| 
Les messages d'audit, les journaux d'événements de sécurité et les journaux d'applications ne sont pas envoyés aux nœuds d'administration. Ils sont enregistrés uniquement sur les nœuds qui les ont générés (« le nœud local »). Les informations d'audit générées sur chaque nœud local sont stockées dans `/var/local/log/localaudit.log`.

*Remarque* : StorageGRID supprime périodiquement les journaux locaux dans une rotation pour libérer de l'espace. Lorsque le fichier journal d'un nœud atteint 1 Go, le fichier existant est enregistré et un nouveau fichier journal est démarré. La limite de rotation du journal est de 21 fichiers. Lorsque la 22e version du fichier journal est créée, le fichier journal le plus ancien est supprimé. En moyenne, environ 20 Go de données de journalisation sont stockés sur chaque nœud.



 a| 
Nœuds d'administration/nœuds locaux
 a| 
Les messages d'audit sont envoyés au journal d'audit sur les nœuds d'administration, et les journaux d'événements de sécurité et d'applications sont stockés sur les nœuds qui les ont générés. Les informations d'audit sont stockées dans les fichiers suivants :

** Nœuds d'administration (primaire et non primaire) : `/var/local/audit/export/audit.log`
** Tous les nœuds : le `/var/local/log/localaudit.log` fichier est généralement vide ou manquant. Il peut contenir des informations secondaires, telles qu'une copie supplémentaire de certains messages.




 a| 
Serveur syslog externe
 a| 
Les informations d'audit sont envoyées à un serveur syslog externe et enregistrées sur les nœuds locaux (`/var/local/log/localaudit.log`). Le type d'information envoyée dépend de la façon dont vous avez configuré le serveur syslog externe. Cette option n'est activée qu'après avoir configuré un serveur syslog externe.



 a| 
Nœud d'administration et serveur syslog externe
 a| 
Les messages d'audit sont envoyés au journal d'audit (`/var/local/audit/export/audit.log`) sur les nœuds d'administration, et les informations d'audit sont envoyées au serveur syslog externe et enregistrées sur le nœud local (`/var/local/log/localaudit.log`. Le type d'information envoyée dépend de la façon dont vous avez configuré le serveur syslog externe. Cette option n'est activée qu'après avoir configuré un serveur syslog externe.

|===
. Sélectionnez *Enregistrer*.
+
Un message d'avertissement s'affiche.

. Sélectionnez *OK* pour confirmer que vous souhaitez modifier la destination des informations d'audit.
+
Une bannière verte indique que la configuration d'audit a été enregistrée.

+
Les nouveaux journaux sont envoyés aux destinations que vous avez sélectionnées. Les journaux existants restent à leur emplacement actuel.


