---
permalink: monitor/managing-alerts.html 
sidebar: sidebar 
keywords: alert rules, managing alerts, alerts, alert notifications. edit alert rules 
summary: 'Le système d"alerte offre une interface facile à utiliser pour détecter, évaluer et résoudre les problèmes susceptibles de se produire lors du fonctionnement de StorageGRID.' 
---
= Gérer les alertes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le système d'alerte offre une interface facile à utiliser pour détecter, évaluer et résoudre les problèmes susceptibles de se produire lors du fonctionnement de StorageGRID.

Les alertes sont déclenchées à des niveaux de gravité spécifiques lorsque les conditions des règles d'alerte sont définies comme vrai. Lorsqu'une alerte est déclenchée, les actions suivantes se produisent :

* Une icône de gravité d'alerte s'affiche sur le tableau de bord dans le Gestionnaire de grille et le nombre d'alertes actuelles est incrémenté.
* L'alerte s'affiche sur la page de résumé *Nœuds* et sur l'onglet *Nœuds* > *_node_* > *Aperçu*.
* Une notification par e-mail est envoyée, en supposant que vous avez configuré un serveur SMTP et fourni des adresses e-mail aux destinataires.
* Une notification SNMP (simple Network Management Protocol) est envoyée, en supposant que vous avez configuré l'agent SNMP StorageGRID.


Vous pouvez créer des alertes personnalisées, modifier ou désactiver des alertes et gérer les notifications d'alerte.

Pour en savoir plus :

* Revoir les vidéos :
+
.Aperçu des alertes
video::2eea81c5-8323-417f-b0a0-b1ff008506c1[panopto]
+
.Alertes personnalisées
video::54af90c4-9a38-4136-9621-b1ff008604a3[panopto]
* Reportez-vous à lalink:alerts-reference.html["Référence des alertes"] .

