---
permalink: monitor/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, triggering autosupport, manually triggering autosupport, autosupport triggers 
summary: 'Pour aider le support technique à résoudre les problèmes liés à votre système StorageGRID, vous pouvez déclencher manuellement l"envoi d"un pack AutoSupport.' 
---
= Déclencher manuellement un package AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour aider le support technique à résoudre les problèmes liés à votre système StorageGRID, vous pouvez déclencher manuellement l'envoi d'un pack AutoSupport.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous disposez de l'autorisation d'accès racine ou d'une autre autorisation de configuration de grille.


.Étapes
. Sélectionnez *SUPPORT* > *Outils* > *AutoSupport*.
. Dans l'onglet *actions*, sélectionnez *Envoyer AutoSupport déclenché par l'utilisateur*.
+
StorageGRID tente d'envoyer un pack AutoSupport sur le site de support NetApp. Si la tentative réussit, les valeurs *résultat le plus récent* et *dernier temps* réussi dans l'onglet *Résultats* sont mises à jour. En cas de problème, la valeur *résultat le plus récent* est mise à jour sur « échec » et StorageGRID n'essaie pas d'envoyer à nouveau le paquet AutoSupport.

. Au bout d'une minute, actualisez la page AutoSupport de votre navigateur pour accéder aux résultats les plus récents.



TIP: Vous pouvez link:../monitor/collecting-log-files-and-system-data.html["collectez des fichiers journaux et des données système plus complets"] également les envoyer sur le site de support NetApp.
