---
permalink: monitor/using-task-tab.html 
sidebar: sidebar 
keywords: Tasks tab, rename node, reboot node, storage state, maintenance mode 
summary: 'L"onglet Tâches s"affiche pour tous les nœuds.  Vous pouvez utiliser cet onglet pour renommer ou redémarrer un nœud ou pour mettre un nœud d"appliance en mode maintenance.  Pour les nœuds de stockage, vous pouvez définir l’état de stockage.' 
---
= Utilisez l'onglet tâches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'onglet Tâches s'affiche pour tous les nœuds.  Vous pouvez utiliser cet onglet pour renommer ou redémarrer un nœud ou pour mettre un nœud d'appliance en mode maintenance.  Pour les nœuds de stockage, vous pouvez définir l’état de stockage.

Pour connaître l'ensemble des exigences et des instructions relatives à chaque option de cet onglet, reportez-vous aux sections suivantes :

* link:../maintain/rename-grid-site-node-overview.html["Renommez la grille, les sites et les nœuds"]
* link:../maintain/rebooting-grid-node-from-grid-manager.html["Redémarrez le nœud de la grille"]
* https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/placing-appliance-into-maintenance-mode.html["Mettez l'appareil en mode maintenance"^]
* Vous vérifiez ou définissez l'état de stockage d'un nœud de stockage après avoir ajouté des volumes à connexion directe ou SAN au nœud de stockage, ou après avoir récupéré un nœud de stockage.  Ces instructions sont disponibles dans les rubriques qui décrivent ces tâches.

