---
permalink: maintain/checking-storage-state-after-recovering-storage-node-system-drive.html 
sidebar: sidebar 
keywords: storagegrid, storage node recovery, system drive, storage state 
summary: 'Après avoir restauré le lecteur système d"un noeud de stockage, vous devez vérifier que l"état souhaité du noeud de stockage est défini sur en ligne et vous assurer que l"état est en ligne par défaut à chaque redémarrage du serveur de noeud de stockage.' 
---
= Vérifiez l'état du stockage après avoir restauré le lecteur système du nœud de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir restauré le lecteur système d'un noeud de stockage, vous devez vérifier que l'état souhaité du noeud de stockage est défini sur en ligne et vous assurer que l'état est en ligne par défaut à chaque redémarrage du serveur de noeud de stockage.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Le nœud de stockage a été restauré et la restauration des données est terminée.


.Étapes
. Sélectionnez *Nœuds* > *_Nœud de stockage_* > *Tâches*.
. Si la liste déroulante *État de stockage* est définie sur Lecture seule ou Hors ligne, sélectionnez *En ligne*.
. Sélectionnez *Enregistrer*.

