---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: 'Après avoir restauré un noeud de stockage d"appliance, vous devez vérifier que l"état souhaité du noeud de stockage de l"appliance est défini sur en ligne et vous assurer que l"état est en ligne par défaut à chaque redémarrage du serveur de noeud de stockage.' 
---
= Vérifiez l'état de stockage après la récupération du nœud de stockage de l'appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir restauré un noeud de stockage d'appliance, vous devez vérifier que l'état souhaité du noeud de stockage de l'appliance est défini sur en ligne et vous assurer que l'état est en ligne par défaut à chaque redémarrage du serveur de noeud de stockage.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Le nœud de stockage a été restauré et la restauration des données est terminée.


.Étapes
. Sélectionnez *Nœuds* > *_Nœud de stockage_* > *Tâches*.
. Si la liste déroulante *État de stockage* est définie sur Lecture seule ou Hors ligne, sélectionnez *En ligne*.
. Sélectionnez *Enregistrer*.

