---
permalink: maintain/checking-data-repair-jobs.html 
sidebar: sidebar 
keywords: storagegrid, data repair 
summary: 'Avant de mettre un nœud de grille hors service, vous devez confirmer qu"aucun travail de réparation de données n"est actif. Si des réparations ont échoué, vous devez les redémarrer et leur permettre d"effectuer la procédure de mise hors service.' 
---
= Consultez les tâches de réparation de données dans StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre hors service ou d’étendre un nœud de grille, vous devez confirmer qu’aucune tâche de réparation de données n’est active.  Si des réparations ont échoué, vous devez les redémarrer et les laisser se terminer avant d'effectuer la procédure de mise hors service.

* Se référer àlink:../expand/index.html["Types d'extension"] pour plus de détails sur la façon d'étendre un nœud de grille.
* Utilisez le Gestionnaire de grille pour suivre les processus de restauration en cours et afficher l'historique des restaurations. Consultez ces procédures :
+
** link:../maintain/restoring-object-data-to-storage-volume-for-appliance.html["Restaurez les données d'objet vers un volume de stockage pour l'appliance"]
** link:../maintain/restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Restaurez les données d'objet vers le volume de stockage sur lequel le disque système est intact"]
** link:../maintain/restoring-object-data-to-storage-volume.html["Restauration des données d'objet sur le volume de stockage (panne de disque système)"]



