---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: 'Après avoir restauré un noeud de stockage d"appliance, vous devez vérifier que l"état souhaité du noeud de stockage de l"appliance est défini sur en ligne et vous assurer que l"état est en ligne par défaut à chaque redémarrage du serveur de noeud de stockage.' 
---
= Vérifiez l'état de stockage après la récupération du nœud de stockage de l'appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir restauré un noeud de stockage d'appliance, vous devez vérifier que l'état souhaité du noeud de stockage de l'appliance est défini sur en ligne et vous assurer que l'état est en ligne par défaut à chaque redémarrage du serveur de noeud de stockage.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Le nœud de stockage a été restauré et la restauration des données est terminée.


.Étapes
. Sélectionnez *SUPPORT* > *Outils* > *topologie de grille*.
. Vérifiez les valeurs de *nœud de stockage récupéré* > *LDR* > *Storage* > *Storage State de stockage -- désiré* et *Storage State -- Current*.
+
La valeur des deux attributs doit être en ligne.

. Si l'état de stockage -- souhaité est défini sur lecture seule, procédez comme suit :
+
.. Cliquez sur l'onglet *Configuration*.
.. Dans la liste déroulante *État de stockage -- désiré*, sélectionnez *en ligne*.
.. Cliquez sur *appliquer les modifications*.
.. Cliquez sur l'onglet *Présentation* et confirmez que les valeurs de *État de stockage -- désiré* et *État de stockage -- actuel* sont mises à jour en ligne.



