---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: 'Vous pouvez ajouter, mettre à jour ou supprimer des serveurs NTP (Network Time Protocol) afin de vous assurer que les données sont synchronisées avec précision entre les nœuds de grille de votre système StorageGRID.' 
---
= Gérer les serveurs NTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter, mettre à jour ou supprimer des serveurs NTP (Network Time Protocol) pour vous assurer que les données sont synchronisées avec précision entre les nœuds de grid de votre système StorageGRID.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez le link:../admin/admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Vous avez la phrase secrète pour le provisionnement.
* Vous disposez des adresses IPv4 des serveurs NTP à configurer.




== Comment StorageGRID utilise-t-il le protocole NTP

Le système StorageGRID utilise le protocole NTP (Network Time Protocol) pour synchroniser l'heure entre tous les nœuds de la grille.

Le rôle NTP principal est attribué à chaque site au moins deux nœuds du système StorageGRID. Ils se synchronisent avec un minimum suggéré de quatre et un maximum de six sources de temps externes et entre elles. Chaque nœud du système StorageGRID qui n'est pas un nœud NTP principal agit comme un client NTP et se synchronise avec ces nœuds NTP primaires.

Les serveurs NTP externes se connectent aux nœuds auxquels vous avez précédemment attribué des rôles NTP principaux. C'est pourquoi il est recommandé de spécifier au moins deux nœuds avec des rôles NTP principaux.



== Instructions relatives au serveur NTP

Suivez ces directives pour vous protéger contre les problèmes de synchronisation :

* Les serveurs NTP externes se connectent aux nœuds auxquels vous avez précédemment attribué des rôles NTP principaux. C'est pourquoi il est recommandé de spécifier au moins deux nœuds avec des rôles NTP principaux.
* Assurez-vous qu'au moins deux nœuds sur chaque site peuvent accéder à au moins quatre sources NTP externes. Si un seul nœud d'un site peut atteindre les sources NTP, des problèmes de synchronisation surviennent en cas de panne de ce nœud. En outre, la désignation de deux nœuds par site en tant que sources NTP principales assure une synchronisation précise si un site est isolé du reste de la grille.
* Les serveurs NTP externes spécifiés doivent utiliser le protocole NTP. Vous devez spécifier les références de serveur NTP de Stratum 3 ou mieux pour éviter les problèmes de dérive du temps.



NOTE: Lorsque vous spécifiez la source NTP externe pour une installation StorageGRID de niveau production, n'utilisez pas le service heure Windows (W32Time) sur une version de Windows antérieure à Windows Server 2016. Le service de temps sur les versions antérieures de Windows n'est pas suffisamment précis et n'est pas pris en charge par Microsoft pour une utilisation dans des environnements de haute précision, y compris StorageGRID. Pour plus de détails, voir https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["Limite de prise en charge pour configurer le service de temps Windows pour des environnements de haute précision"^].



== Configuration des serveurs NTP

Procédez comme suit pour ajouter, mettre à jour ou supprimer des serveurs NTP.

.Étapes
. Sélectionnez *MAINTENANCE* > *réseau* > *serveurs NTP*.
. Dans la section serveurs, ajoutez, mettez à jour ou supprimez des entrées de serveur NTP, si nécessaire.
+
Vous devez inclure au moins quatre serveurs NTP et vous pouvez spécifier jusqu'à six serveurs.

. Entrez la phrase de passe de provisionnement pour votre système StorageGRID, puis sélectionnez *Enregistrer*.
+
La page est désactivée jusqu'à ce que les mises à jour de la configuration soient terminées.

+

NOTE: Si tous vos serveurs NTP échouent au test de connexion après l'enregistrement des nouveaux serveurs NTP, ne poursuivez pas. Contactez l'assistance technique.





== Résoudre les problèmes de serveur NTP

Si vous rencontrez des problèmes de stabilité ou de disponibilité des serveurs NTP initialement spécifiés lors de l'installation, vous pouvez mettre à jour la liste des sources NTP externes que le système StorageGRID utilise en ajoutant des serveurs supplémentaires ou en mettant à jour ou en supprimant des serveurs existants.
