---
permalink: maintain/convert-to-data-only-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: Pour améliorer les performances, vous pouvez convertir des nœuds de stockage non ADC plus lents en nœuds de stockage uniquement pour les données. 
---
= Convertir un nœud de stockage en nœud de données uniquement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour améliorer les performances, vous pouvez convertir des nœuds de stockage non ADC plus lents en nœuds de stockage uniquement pour les données.

Il est logique d'utiliser un nœud de stockage exclusivement pour les données si les performances de vos nœuds de stockage diffèrent. Par exemple, pour augmenter les performances, vous pouvez disposer de nœuds de stockage sur disque rotatif haute capacité uniquement en données et accompagnés de nœuds de stockage haute performance pour métadonnées uniquement.

En outre, vous pouvez augmenter la capacité des métadonnées en supprimant les nœuds à faible RAM de Cassandra, ce qui augmente la limite de capacité des métadonnées par nœud. Reportez-vous à la link:../admin/managing-object-metadata-storage.html["Gérer le stockage des métadonnées d'objet"].

Lors de l'installation de nœuds de données uniquement, la grille doit contenir les éléments suivants :

* Au moins deux nœuds de stockage combinés ou uniquement des données par grid
* Au moins un nœud de stockage combiné ou uniquement des données par site
* Au moins trois nœuds de stockage combinés ou métadonnées uniquement par site


.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez le link:admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Le nœud de stockage que vous souhaitez convertir ne contient pas le service ADC, ou vous devez link:../maintain/move-adc-service.html["Déplacé le service ADC"] utiliser un autre nœud.
* Le nœud de stockage n'est pas un nœud contenant uniquement des métadonnées ou des données uniquement.
* L'espace de métadonnées disponible sur les autres nœuds du site est suffisant pour prendre en charge les métadonnées qui vont migrer du nœud de stockage que vous convertissez.


.Description de la tâche
Utilisez cette procédure pour convertir un ou plusieurs nœuds de stockage combinés ou contenant uniquement des métadonnées qui ne contiennent pas le service ADC en nœuds uniquement des données. Les nœuds de stockage doivent être sur le même site.

Outre la conversion du nœud de stockage, cette procédure décompresse Cassandra du nœud. Toutes les métadonnées seront migrées vers des nœuds de stockage combinant ou uniquement des métadonnées. Selon la quantité de métadonnées à migrer, cette procédure peut prendre jusqu'à plusieurs jours par nœud.


TIP: En règle générale, vous pouvez convertir jusqu'à 10 nœuds à la fois si l'utilisation des métadonnées par nœud est inférieure à 1 To. Si l'utilisation des métadonnées par nœud est supérieure à 1 To, convertissez jusqu'à 5 nœuds par procédure.

.Étapes
. Enregistrez les ID de nœud des nœuds de stockage non ADC que vous souhaitez convertir.
. En haut du Gestionnaire de grille, sélectionnez l'icône d'aide et sélectionnez *documentation API*.
. Sélectionnez *aller à la documentation privée de l'API*.
. Sélectionnez `POST /private/convert-to-data-only-node/start` l'opération. Pour plus d'informations, reportez-vous à la section link:../admin/using-grid-management-api.html#issue-api-requests["Émettre des requêtes API"] .
+
Chaque nœud redémarre pendant la procédure.

. Vous pouvez utiliser `GET /private/convert-to-data-only-node` pour surveiller la procédure. Si des erreurs se produisent, sélectionnez `POST /private/convert-to-data-only-node/retry` pour réessayer la procédure.
. link:../maintain/downloading-recovery-package.html["Télécharger un package de récupération"] une fois cette procédure terminée.

