---
permalink: maintain/copying-audit-logs-from-failed-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, non-primary admin node, non primary admin node 
summary: 'Si vous pouvez copier les journaux d"audit à partir du noeud d"administration défaillant, conservez-les pour conserver l"enregistrement de l"activité et de l"utilisation du système dans la grille. Vous pouvez restaurer les journaux d"audit conservés sur le nœud d"administration non primaire restauré après son exécution.' 
---
= Copie des journaux d'audit à partir d'un nœud d'administration non primaire ayant échoué
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous pouvez copier les journaux d'audit depuis le nœud d'administration défaillant, conservez-les pour conserver l'enregistrement de l'activité et de l'utilisation du système dans la grille. Vous pouvez restaurer les journaux d'audit conservés sur le nœud d'administration non primaire restauré après son exécution.

Cette procédure copie les fichiers journaux d'audit du nœud d'administration défaillant vers un emplacement temporaire sur un nœud de grille distinct. Ces journaux conservés peuvent ensuite être copiés sur le nœud d'administration de remplacement. Les journaux d'audit ne sont pas automatiquement copiés sur le nouveau nœud d'administration.

Selon le type de défaillance, il se peut que vous ne puissiez pas copier les journaux d'audit à partir d'un nœud d'administration défaillant. Si le déploiement ne comporte qu'un seul nœud d'administration, le nœud d'administration restauré commence à enregistrer les événements dans le journal d'audit d'un nouveau fichier vide et les données précédemment enregistrées sont perdues. Si le déploiement inclut plusieurs nœuds d'administration, vous pouvez récupérer les journaux d'audit à partir d'un autre nœud d'administration.


NOTE: Si les journaux d'audit ne sont pas accessibles sur le nœud d'administration défaillant maintenant, vous pourrez peut-être y accéder ultérieurement, par exemple après la restauration de l'hôte.

. Si possible, connectez-vous au nœud d'administration défaillant. Sinon, connectez-vous au nœud d'administration principal ou à un autre nœud d'administration, le cas échéant.
+
.. Entrez la commande suivante : `ssh admin@grid_node_IP`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour basculer en root : `su -`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.


+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.

. Arrêtez le service AMS pour l'empêcher de créer un nouveau fichier journal :``service ams stop``
. Accédez au répertoire d'exportation d'audit :
+
`cd /var/local/log`

. Renommez le fichier source audit.log en un nom de fichier numéroté unique. Par exemple, renommez le fichier audit.log en `2023-10-25.txt.1`.
+
[listing]
----
ls -l
mv audit.log 2023-10-25.txt.1
----
. Redémarrez le service AMS : `service ams start`
. Créez le répertoire pour copier tous les fichiers journaux d'audit dans un emplacement temporaire sur un nœud de grille distinct : `ssh admin@grid_node_IP mkdir -p /var/local/tmp/saved-audit-logs`
+
Lorsque vous y êtes invité, entrez le mot de passe pour l'administrateur.

. Copiez tous les fichiers journaux d'audit à l'emplacement temporaire : `scp -p * admin@grid_node_IP:/var/local/tmp/saved-audit-logs`
+
Lorsque vous y êtes invité, entrez le mot de passe pour l'administrateur.

. Se déconnecter en tant que root : `exit`

