---
permalink: maintain/deploying-new-linux-hosts.html 
sidebar: sidebar 
keywords: storagegrid, deploy linux host, new host, new linux host 
summary: 'À quelques exceptions près, vous préparez les nouveaux hôtes comme vous l"avez fait lors du processus d"installation initiale.' 
---
= Déploiement de nouveaux hôtes Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À quelques exceptions près, vous préparez les nouveaux hôtes comme vous l'avez fait lors du processus d'installation initiale.

Pour déployer des hôtes Linux physiques ou virtuels nouveaux ou réinstallés, suivez la procédure de préparation des hôtes dans les instructions d'installation de StorageGRID pour votre système d'exploitation Linux. Voir link:../swnodes/installing-linux.html["Installez Linux"] .


NOTE: « Linux » fait référence à un déploiement RHEL, Ubuntu ou Debian.  Pour une liste des versions prises en charge, consultez le https://imt.netapp.com/matrix/#welcome["Matrice d'interopérabilité NetApp (IMT)"^] .

Cette procédure comprend les étapes permettant d'effectuer les tâches suivantes :

. Installez Linux.
. Configurez le réseau hôte.
. Configurer le stockage de l'hôte
. Installer le moteur de mise en conteneurs.
. Installez le service hôte StorageGRID.
+

CAUTION: Arrêtez-vous une fois que vous avez terminé la tâche « installer le service hôte StorageGRID » dans les instructions d'installation. Ne lancez pas la tâche « déploiement des nœuds grid ».



À mesure que vous effectuez ces étapes, prenez note des consignes importantes suivantes :

* Veillez à utiliser les mêmes noms d'interface hôte que ceux utilisés sur l'hôte d'origine.
* Si vous utilisez un stockage partagé pour prendre en charge vos nœuds StorageGRID, ou si vous avez déplacé tout ou partie des disques ou disques SSD de vers les nœuds de remplacement, vous devez rétablir les mêmes mappages du stockage que ceux présents sur l'hôte d'origine. Par exemple, si vous avez utilisé des WWID et des alias dans comme recommandé dans les `/etc/multipath.conf` instructions d'installation, veillez à utiliser les mêmes paires alias/WWID dans `/etc/multipath.conf` sur l'hôte de remplacement.
* Si le nœud StorageGRID utilise le stockage affecté à un système NetApp ONTAP, vérifiez que cette FabricPool règle n'est pas activée pour le volume. La désactivation du Tiering FabricPool pour les volumes utilisés avec des nœuds StorageGRID simplifie la résolution des problèmes et les opérations de stockage.
+

CAUTION: N'utilisez jamais FabricPool pour transférer automatiquement toutes les données liées à StorageGRID vers StorageGRID. Le Tiering des données StorageGRID vers StorageGRID augmente la complexité opérationnelle et la résolution des problèmes.


