---
permalink: maintain/downloading-recovery-package.html 
sidebar: sidebar 
keywords: storagegrid, recovery package 
summary: Le fichier de package de récupération vous permet de restaurer le système StorageGRID en cas de panne. 
---
= Télécharger le package de récupération
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le fichier de package de récupération vous permet de restaurer le système StorageGRID en cas de panne.

.Avant de commencer
* À partir de n’importe quel nœud d’administration, vous êtes connecté au gestionnaire de grille à l’aide d’unlink:../admin/web-browser-requirements.html["navigateur web pris en charge"] .
* Vous avez la phrase secrète pour le provisionnement.
* Vous avez link:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"].


Téléchargez le fichier du package de récupération actuel avant d'apporter des modifications à la topologie de grille du système StorageGRID ou avant de mettre à niveau le logiciel.  Ensuite, téléchargez une nouvelle copie du package de récupération après avoir apporté des modifications à la topologie de la grille ou après la mise à niveau du logiciel.

.Étapes
. Sélectionnez *Maintenance* > *Système* > *Package de récupération*.
. Entrez la phrase de passe de provisionnement et sélectionnez *Démarrer le téléchargement*.
+
Le téléchargement commence immédiatement.

. Une fois le téléchargement terminé, ouvrez `.zip` le fichier et confirmez que vous pouvez accéder au contenu, y compris au `Passwords.txt` fichier.
. Copiez le fichier du package de récupération téléchargé(`.zip` ) vers deux endroits sûrs, sécurisés et séparés.
+

CAUTION: Le fichier du package de récupération doit être sécurisé car il contient des clés de chiffrement et des mots de passe qui peuvent être utilisés pour obtenir des données du système StorageGRID .


