---
permalink: maintain/identifying-and-unmounting-failed-storage-volumes.html 
sidebar: sidebar 
keywords: storagegrid, storage volume, failed storage volume, unmount failed volume 
summary: 'Lors de la restauration d"un nœud de stockage dont les volumes de stockage sont en panne, vous devez identifier et démonter les volumes en panne. Vous devez vérifier que seuls les volumes de stockage défaillants sont reformatés dans le cadre de la procédure de restauration.' 
---
= Identifiez et démontez les volumes de stockage défectueux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la restauration d'un nœud de stockage dont les volumes de stockage sont en panne, vous devez identifier et démonter les volumes en panne. Vous devez vérifier que seuls les volumes de stockage défaillants sont reformatés dans le cadre de la procédure de restauration.

.Avant de commencer
Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].

.Description de la tâche
Vous devriez récupérer les volumes de stockage défaillants dès que possible.

La première étape du processus de restauration consiste à détecter les volumes qui se sont détachés, qui doivent être démontés ou qui présentent des erreurs d'E/S. Si les volumes défaillants sont toujours attachés mais qu'un système de fichiers est corrompu de façon aléatoire, le système risque de ne pas détecter de corruption dans les pièces non utilisées ou non attribuées du disque.


NOTE: Vous devez terminer cette procédure avant d'effectuer manuellement les étapes de restauration des volumes, telles que l'ajout ou la reconfiguration des disques, l'arrêt du nœud, le démarrage du nœud ou le redémarrage. Sinon, lorsque vous exécutez `reformat_storage_block_devices.rb` le script, vous risquez de rencontrer une erreur du système de fichiers qui provoque le blocage ou l'échec du script.


NOTE: Réparez le matériel et connectez correctement les disques avant d'exécuter `reboot` la commande.


CAUTION: Identifiez minutieusement les volumes de stockage défaillants. Ces informations vous permettront de vérifier quels volumes doivent être reformatés. Une fois qu'un volume a été reformaté, les données du volume ne peuvent pas être récupérées.

Pour récupérer les volumes de stockage défaillants, vous devez connaître à la fois les noms des périphériques des volumes de stockage défaillants et leurs ID de volume.

Lors de l'installation, chaque périphérique de stockage se voit attribuer un identifiant unique universel (UUID) du système de fichiers et est monté sur un répertoire rangedb sur le nœud de stockage à l'aide de cet UUID du système de fichiers attribué.  L'UUID du système de fichiers et le répertoire rangedb sont répertoriés dans le `/etc/fstab` déposer.  Le point de montage, le nom du périphérique et la taille du volume sont affichés dans le gestionnaire de grille.

.Étapes
. Procédez comme suit pour enregistrer les volumes de stockage défaillants et leurs noms de périphériques :
+
.. Sélectionnez *Nœuds* > *_site_* > *_nœud de stockage défaillant_* > *Stockage*.
.. Faites défiler vers le bas pour localiser la table Volumes et la table Magasins d'objets et enregistrez les informations suivantes pour chaque volume avec un statut Inconnu ou Hors ligne.
+
*** Dans la table Volumes, enregistrez le point de montage, le périphérique et la taille.
*** À partir de la table des magasins d'objets, enregistrez le `object_store_ID` .
+
Le `object_store_ID` correspond à l'ID du volume de stockage défaillant. Par exemple, spécifiez `0` dans la commande d'un magasin d'objets ayant l'ID 0000.





. Connectez-vous au noeud de stockage défaillant :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour basculer en root : `su -`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Exécutez le script suivant pour démonter un volume de stockage défaillant :
+
`sn-unmount-volume object_store_ID`

. Si vous y êtes invité, appuyez sur *y* pour arrêter le service Cassandra en fonction du volume de stockage 0.
+

NOTE: Si le service Cassandra est déjà arrêté, vous n'êtes pas invité à le faire. Le service Cassandra est arrêté uniquement pour le volume 0.

+
[listing]
----
root@Storage-180:~/var/local/tmp/storage~ # sn-unmount-volume 0
Services depending on storage volume 0 (cassandra) aren't down.
Services depending on storage volume 0 must be stopped before running this script.
Stop services that require storage volume 0 [y/N]? y
Shutting down services that require storage volume 0.
Services requiring storage volume 0 stopped.
Unmounting /var/local/rangedb/0
/var/local/rangedb/0 is unmounted.
----
+
Le volume est démonté en quelques secondes. Des messages s'affichent indiquant chaque étape du processus. Le dernier message indique que le volume est démonté.

. Si le démontage échoue parce que le volume est occupé, vous pouvez forcer le démontage à l'aide de l' `--use-umountof`option :
+

NOTE: Forcer un démontage à l'aide de l'option peut provoquer un comportement inattendu ou un `--use-umountof` blocage des processus ou services utilisant le volume.

+
[listing]
----
root@Storage-180:~ # sn-unmount-volume --use-umountof /var/local/rangedb/2
Unmounting /var/local/rangedb/2 using umountof
/var/local/rangedb/2 is unmounted.
Informing LDR service of changes to storage volumes
----

