---
permalink: maintain/linux-adding-interfaces-to-existing-node.html 
sidebar: sidebar 
keywords: add interfaces, add client network interface, add admin network interface 
summary: 'Procédez comme suit pour ajouter une interface sur le réseau Admin ou le réseau client à un nœud Linux après l"avoir installé.' 
---
= Linux : ajoutez des interfaces Admin ou client à un nœud existant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Procédez comme suit pour ajouter une interface sur le réseau Admin ou le réseau client à un nœud Linux après l'avoir installé.

Si vous n'avez pas configuré ADMIN_NETWORK_TARGET ni CLIENT_NETWORK_TARGET dans le fichier de configuration du nœud sur l'hôte Linux au cours de l'installation, utilisez cette procédure pour ajouter l'interface. Pour plus d'informations sur le fichier de configuration des nœuds, reportez-vous aux instructions de votre système d'exploitation Linux :

* link:../rhel/index.html["Installez StorageGRID sur Red Hat Enterprise Linux"]
* link:../ubuntu/index.html["Installez StorageGRID sur Ubuntu ou Debian"]


Cette procédure est effectuée sur le serveur Linux hébergeant le nœud nécessitant la nouvelle affectation de réseau, et non à l'intérieur du nœud. Cette procédure ajoute uniquement l'interface au nœud. Une erreur de validation se produit si vous tentez de spécifier d'autres paramètres réseau.

Pour fournir des informations d'adressage, vous devez utiliser l'outil Modifier IP. Voir link:changing-nodes-network-configuration.html["Modifier la configuration réseau du nœud"].

.Étapes
. Connectez-vous au serveur Linux hébergeant le nœud.
. Modifiez le fichier de configuration de nœud : `/etc/storagegrid/nodes/_node-name_.conf`.
+

NOTE: Ne spécifiez aucun autre paramètre réseau, sinon une erreur de validation se produit.

+
.. Ajouter une entrée pour la nouvelle cible réseau. Par exemple :
+
`CLIENT_NETWORK_TARGET = bond0.3206`

.. Facultatif : ajoutez une entrée pour l'adresse MAC. Par exemple :
+
`CLIENT_NETWORK_MAC = aa:57:61:07:ea:5c`



. Lancer la commande node validate :
+
`sudo storagegrid node validate _node-name_`

. Résoudre toutes les erreurs de validation.
. Lancer la commande node reload :
+
`sudo storagegrid node reload _node-name_`


