---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: Vous pouvez déplacer le service ADC vers un autre nœud de stockage sur le même site. 
---
= Déplacer le service ADC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déplacer le service ADC vers un autre nœud de stockage sur le même site.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez link:admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Le nœud source contient le service ADC.
* Le nœud cible ne contient pas le service ADC.
* Le nœud cible est un nœud de métadonnées uniquement ou combiné (métadonnées et données d'objet).
* Le nœud source et le nœud cible se trouvent sur le même site.


.Description de la tâche
Utilisez la procédure déplacer ADC lorsque vous souhaitez :

* Désaffecter un nœud de stockage qui contient le service ADC
* Convertir un nœud ADC en nœud de données uniquement
* Ajoutez un nœud pour exécuter des tâches ADC


Pour désaffecter un nœud de stockage ou link:../maintain/convert-to-data-only-node.html["Convertir un nœud de stockage en nœud de données uniquement"], vous devez d'abord utiliser la procédure déplacer ADC. Vous devez vous assurer que le link:../maintain/understanding-adc-service-quorum.html["Le quorum ADC est maintenu"].

Cette procédure déplace les services ADC, IDNT, ACCT et RSM d'un nœud de stockage vers un autre sur le même site. Les services RSM et ACCT dépendent du service ADC, de sorte qu'ils se déplacent automatiquement lorsque le service ADC se déplace.

.Étapes
. Enregistrez les ID de nœud des nœuds source et cible.
+
Dans l'API de gestion de grille, l'ID de nœud source est appelé `sourceNodeId`. L'ID de nœud cible est appelé `targetNodeId`.

. En haut du Gestionnaire de grille, sélectionnez l'icône d'aide et sélectionnez *documentation API*.
. Sélectionnez *aller à la documentation privée de l'API*.
. Sélectionnez `POST /private/move-adc/start` l'opération. Pour plus d'informations, reportez-vous à la section link:../admin/using-grid-management-api.html#issue-api-requests["Émettre des requêtes API"] .
+
Chaque nœud redémarre pendant la procédure.

. Vous pouvez utiliser `GET /private/move-adc` pour surveiller la procédure. Si des erreurs se produisent, sélectionnez `POST /private/move-adc/retry` pour réessayer la procédure.
. link:../maintain/downloading-recovery-package.html["Télécharger un package de récupération"] une fois cette procédure terminée.

