---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: Vous pouvez déplacer le service ADC vers un autre nœud de stockage sur le même site. 
---
= Déplacer le service ADC dans StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déplacer le service ADC vers un autre nœud de stockage sur le même site.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Tu aslink:../admin/admin-group-permissions.html["Maintenance ou autorisation d'accès racine"] .
* Le nœud source contient le service ADC.
* Le nœud cible ne contient pas le service ADC.
* Le nœud cible est soit un nœud contenant uniquement des métadonnées, soit un nœud combiné (métadonnées et données d'objet).
* Le nœud source et le nœud cible sont sur le même site.


.Description de la tâche
Utilisez la procédure Move ADC pour déplacer manuellement le service ADC entre les nœuds de stockage. Par exemple, vous pouvez redistribuer les services ADC entre les nœuds ou déplacer le service ADC vers un nœud plus performant.

Cette procédure déplace les services ADC, IDNT, ACCT et RSM d'un nœud de stockage vers un autre sur le même site.  Les services RSM, IDNT et ACCT dépendent du service ADC, ils se déplacent donc automatiquement lorsque le service ADC se déplace.

[NOTE]
====
* Il n'est pas nécessaire de déplacer manuellement le service ADC avant link:../maintain/convert-to-data-only-node.html["conversion d’un nœud de stockage en nœud de données uniquement"] ou de mettre hors service un nœud de stockage. Ces procédures déplacent automatiquement le service ADC lorsque cela est requis. Consultez link:../maintain/understanding-adc-service-quorum.html["Qu'est-ce que le quorum ADC ?"] pour plus de détails sur les exigences.
* StorageGRID déplace le service ADC vers les nœuds de stockage les plus récents qui répondent aux exigences d’hébergement du service.


====
.Étapes
. Enregistrez les ID de nœud des nœuds source et cible.
+
Dans l'API de gestion de grille, l'ID du nœud source est appelé `sourceNodeId` .  L'ID du nœud cible est appelé `targetNodeId` .

. En haut du Gestionnaire de grille, sélectionnez l'icône d'aide et sélectionnez *documentation API*.
. Sélectionnez *aller à la documentation privée de l'API*.
. Sélectionnez le `POST /private/move-adc/start` opération. Consultez link:../admin/using-grid-management-api.html#issue-api-requests["Émettre des requêtes API"] pour plus d'informations.
+
Pendant la procédure, les deux nœuds redémarreront en séquence.  Le nœud source redémarre en premier, suivi du nœud cible.

. Vous pouvez utiliser `GET /private/move-adc` pour surveiller la procédure.  Si des erreurs surviennent, sélectionnez `POST /private/move-adc/retry` pour réessayer la procédure.
. link:../maintain/downloading-recovery-package.html["Télécharger un package de récupération"]après avoir terminé cette procédure.

