---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: Vous pouvez déplacer le service ADC vers un autre nœud de stockage sur le même site. 
---
= Déplacer le service ADC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déplacer le service ADC vers un autre nœud de stockage sur le même site.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Tu aslink:../admin/admin-group-permissions.html["Maintenance ou autorisation d'accès racine"] .
* Le nœud source contient le service ADC.
* Le nœud cible ne contient pas le service ADC.
* Le nœud cible est soit un nœud contenant uniquement des métadonnées, soit un nœud combiné (métadonnées et données d'objet).
* Le nœud source et le nœud cible sont sur le même site.


.Description de la tâche
Utilisez la procédure Move ADC lorsque vous souhaitez :

* Désactiver un nœud de stockage qui héberge le service ADC
* Convertir un nœud de stockage hébergeant le service ADC en nœud de stockage de données uniquement


Lorsque vous souhaitez mettre hors service un nœud de stockage oulink:../maintain/convert-to-data-only-node.html["convertir un nœud de stockage en nœud de données uniquement"] , vous devrez peut-être d’abord utiliser la procédure Move ADC.  Vous devrez vous assurer que lelink:../maintain/understanding-adc-service-quorum.html["Le quorum de l'ADC est maintenu"] .

Cette procédure déplace les services ADC, IDNT, ACCT et RSM d'un nœud de stockage vers un autre sur le même site.  Les services RSM, IDNT et ACCT dépendent du service ADC, ils se déplacent donc automatiquement lorsque le service ADC se déplace.

.Étapes
. Enregistrez les ID de nœud des nœuds source et cible.
+
Dans l'API de gestion de grille, l'ID du nœud source est appelé `sourceNodeId` .  L'ID du nœud cible est appelé `targetNodeId` .

. En haut du Gestionnaire de grille, sélectionnez l'icône d'aide et sélectionnez *documentation API*.
. Sélectionnez *aller à la documentation privée de l'API*.
. Sélectionnez le `POST /private/move-adc/start` opération. Consultez link:../admin/using-grid-management-api.html#issue-api-requests["Émettre des requêtes API"] pour plus d'informations.
+
Pendant la procédure, les deux nœuds redémarreront en séquence.  Le nœud source redémarre en premier, suivi du nœud cible.

. Vous pouvez utiliser `GET /private/move-adc` pour surveiller la procédure.  Si des erreurs surviennent, sélectionnez `POST /private/move-adc/retry` pour réessayer la procédure.
. link:../maintain/downloading-recovery-package.html["Télécharger un package de récupération"]après avoir terminé cette procédure.

