---
permalink: maintain/obtaining-required-materials-for-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 'Avant d"appliquer un correctif, vous devez obtenir tous les matériaux requis.' 
---
= Procurez-vous le matériel requis pour le correctif
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'appliquer un correctif, vous devez obtenir tous les matériaux requis.

[cols="1a,2a"]
|===
| Élément | Remarques 


 a| 
Fichier de correctif StorageGRID
 a| 
Vous devez télécharger le fichier de correctif StorageGRID.



 a| 
* Port réseau
* link:../admin/web-browser-requirements.html["Navigateur Web pris en charge"]
* Client SSH (par exemple, PuTTY)

 a| 



 a| 
Package de récupération (`.zip`)
 a| 
Avant d'appliquer un correctif, link:downloading-recovery-package.html["Téléchargez le dernier fichier de progiciel de récupération"] en cas de problème pendant le correctif. Ensuite, une fois le correctif appliqué, téléchargez une nouvelle copie du fichier du progiciel de récupération et enregistrez-le dans un emplacement sûr. Le fichier du progiciel de récupération mis à jour vous permet de restaurer le système en cas de défaillance.



| Fichier Passwords.txt  a| 
Facultatif et utilisé uniquement si vous appliquez un correctif manuellement à l'aide du client SSH. Le `Passwords.txt` fichier fait partie du fichier du progiciel de récupération `.zip`.



 a| 
Phrase secrète pour le provisionnement
 a| 
La phrase de passe est créée et documentée lors de l'installation initiale du système StorageGRID. La phrase de passe de provisionnement n'est pas répertoriée dans le `Passwords.txt` fichier.



 a| 
Documentation associée
 a| 
`readme.txt` pour le correctif. Ce fichier est inclus sur la page de téléchargement du correctif. Vérifiez soigneusement le `readme` fichier avant d'appliquer le correctif.

|===