---
permalink: maintain/recovering-storagegrid-appliance-storage-node.html 
sidebar: sidebar 
keywords: recover, appliance storage node failure, workflow 
summary: 'La procédure de restauration d"un nœud de stockage de l"appliance StorageGRID défaillant est identique, que vous soyez en train de récupérer à partir de la perte du disque système ou de la perte de volumes de stockage uniquement.' 
---
= Avertissements relatifs à la récupération des nœuds de stockage de l'appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La procédure de restauration d'un nœud de stockage de l'appliance StorageGRID défaillant est identique, que vous soyez en train de récupérer à partir de la perte du disque système ou de la perte de volumes de stockage uniquement.


CAUTION: Si plusieurs nœuds de stockage ont échoué (ou sont hors ligne), contactez le support technique. Ne pas effectuer la procédure de récupération suivante. Des données peuvent être perdues. Pour plus d'informations, reportez-vous link:how-site-recovery-is-performed-by-technical-support.html["Comment le support technique récupère un site"]à .


CAUTION: Si les règles ILM sont configurées pour ne stocker qu'une seule copie répliquée, et si cette copie existe sur un volume de stockage défaillant, vous ne pourrez pas restaurer l'objet.


NOTE: Pour connaître les procédures de maintenance du matériel, telles que les instructions de remplacement d'un contrôleur ou de réinstallation de SANtricity OS, reportez-vous au https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/index.html["instructions d'entretien pour votre appareil de stockage"^] .
