---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: 'Si vous souhaitez configurer un noeud final pour le service Load Balancer et que vous souhaitez utiliser un port qui a déjà été configuré en tant que port mappé sur d"un remappage de port, vous devez d"abord supprimer le plan de plan de port existant, sinon le noeud final ne sera pas effectif. Vous devez exécuter un script sur chaque nœud d"administration et nœud de passerelle qui comporte des ports en conflit et remappés pour supprimer toutes les mappes de ports du nœud.' 
---
= Supprimer les remappages de ports sur les appliances StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez configurer un noeud final pour le service Load Balancer et que vous souhaitez utiliser un port qui a déjà été configuré en tant que port mappé sur d'un remappage de port, vous devez d'abord supprimer le plan de plan de port existant, sinon le noeud final ne sera pas effectif. Vous devez exécuter un script sur chaque nœud d'administration et nœud de passerelle qui comporte des ports en conflit avec des mappages afin de supprimer tous les mappages de ports du nœud.

.Description de la tâche
Cette procédure supprime tous les mappages de ports. Si vous devez conserver certains des plans, contactez le support technique.

Pour plus d'informations sur la configuration des noeuds finaux de l'équilibreur de charge, voir link:../admin/configuring-load-balancer-endpoints.html["Configuration des terminaux d'équilibrage de charge"].


NOTE: Si le remap de port fournit un accès client, reconfigurez le client pour qu'il utilise un autre port comme point final d'équilibrage de charge afin d'éviter toute perte de service. Dans le cas contraire, la suppression du mappage de port entraîne une perte de l'accès client et doit être planifiée de manière appropriée.


NOTE: Cette procédure ne fonctionne pas pour un système StorageGRID déployé en tant que conteneur sur les hôtes bare Metal. Voir les instructions pour link:removing-port-remaps-on-bare-metal-hosts.html["suppression de mappages de port sur les hôtes bare metal"].

.Étapes
. L'accès SSH externe est bloqué par défaut.  Si nécessaire,link:../admin/manage-external-ssh-access.html["autoriser temporairement l'accès"] .
. Connectez-vous au nœud.
+
.. Entrez la commande suivante : `ssh -p 8022 admin@node_IP`
+
Le port 8022 est le port SSH du système d'exploitation de base, tandis que le port 22 est le port SSH du moteur de mise en conteneurs exécutant StorageGRID.

.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour basculer en root : `su -`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Exécutez le script suivant : `remove-port-remap.sh`
. Redémarrez le nœud : `reboot`
. Déconnectez-vous du shell de commande : `exit`
. Répétez ces étapes sur chaque nœud d'administration et nœud de passerelle disposant de ports en conflit avec des ports remappés.
. Si vous avez autorisé l'accès SSH externe,link:../admin/manage-external-ssh-access.html["bloquer l'accès"] lorsque vous avez terminé de supprimer les remappages de ports.

