---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: Avant de récupérer des volumes de stockage défaillants pour un noeud de stockage, vous devez vérifier les avertissements suivants. 
---
= Avertissements pour la restauration du volume de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de restaurer des volumes de stockage défaillants pour un nœud de stockage, consultez les avertissements suivants.

Les volumes de stockage (ou rangedbs) d'un noeud de stockage sont identifiés par un nombre hexadécimal, appelé ID de volume. Par exemple, 0000 est le premier volume et 000F est le seizième volume. Le premier magasin d'objets (volume 0) sur chaque nœud de stockage utilise jusqu'à 4 To d'espace pour les métadonnées d'objet et les opérations des bases de données Cassandra, tout espace restant sur ce volume est utilisé pour les données d'objet. Tous les autres volumes de stockage sont utilisés exclusivement pour les données d'objet.

La base de données Cassandra peut être reconstruite dans le cadre de la procédure de récupération du volume si :

* Le volume 0 échoue et est récupéré.
* Le lecteur système et un ou plusieurs volumes de stockage sont défectueux et restaurés.


Lorsque Cassandra est reconstruit, le système utilise les informations provenant d’autres nœuds de stockage.  Si Cassandra a été reconstruit récemment, les données Cassandra peuvent ne pas encore être cohérentes sur l'ensemble de la grille.  Si trop de nœuds de stockage sont hors ligne :

* Certaines données Cassandra peuvent ne pas être disponibles.
* Une perte de données pourrait survenir.



CAUTION: Si plusieurs nœuds de stockage sont en panne (ou sont hors ligne), contactez le support technique.  N'exécutez pas la procédure de récupération suivante.  Une perte de données pourrait survenir. Pour plus d'informations, reportez-vous à link:how-site-recovery-is-performed-by-technical-support.html["Comment le support technique récupère un site"] .


CAUTION: Si les règles ILM sont configurées pour stocker une seule copie répliquée et que la copie existe sur un volume de stockage défaillant, vous ne pourrez pas récupérer l'objet.

.Informations associées
link:warnings-and-considerations-for-grid-node-recovery.html["Avertissements et considérations relatives à la restauration des nœuds de la grille"]
