---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: 'Avant de restaurer un disque système défaillant d"un nœud de stockage, consultez les avertissements généraux et les considérations concernant la restauration du nœud de grille et les avertissements spécifiques suivants.' 
---
= Avertissements concernant la restauration du disque système du nœud de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de restaurer un lecteur système défaillant d'un nœud de stockage, consultez les avertissements généraux link:warnings-and-considerations-for-grid-node-recovery.html["avertissements et remarques concernant la restauration d'un nœud grid"] et spécifiques suivants.

Les nœuds de stockage disposent d'une base de données Cassandra qui inclut des métadonnées d'objet.  La base de données Cassandra peut être reconstruite si :

* Un volume de stockage tombe en panne et est récupéré.
* Le lecteur système et un ou plusieurs volumes de stockage sont défectueux et restaurés.


Lorsque Cassandra est reconstruit, le système utilise les informations provenant d’autres nœuds de stockage.  Si Cassandra a été reconstruit récemment, les données Cassandra peuvent ne pas encore être cohérentes sur l'ensemble de la grille.  Si trop de nœuds de stockage sont hors ligne :

* Certaines données Cassandra peuvent ne pas être disponibles.
* Une perte de données pourrait survenir.



CAUTION: Si plusieurs nœuds de stockage sont en panne (ou sont hors ligne), contactez le support technique.  N'effectuez pas la procédure de récupération suivante.  Une perte de données pourrait survenir. Pour plus d'informations, reportez-vous à link:how-site-recovery-is-performed-by-technical-support.html["Comment le support technique récupère un site"] .


CAUTION: Si ce nœud de stockage est en mode de maintenance en lecture seule pour permettre la récupération d'objets par un autre nœud de stockage avec des volumes de stockage défaillants, récupérez les volumes du nœud de stockage avec des volumes de stockage défaillants avant de récupérer ce noeud de stockage défaillant. Voir les instructions à link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["effectuez des restaurations après une panne du volume de stockage, là où le disque système est intact"].


CAUTION: Si les règles ILM sont configurées pour ne stocker qu'une seule copie répliquée, et si cette copie existe sur un volume de stockage défaillant, vous ne pourrez pas restaurer l'objet.
