---
permalink: maintain/selecting-start-recovery-to-configure-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage node 
summary: Après avoir remplacé un noeud de stockage, vous devez sélectionner Démarrer la restauration dans Grid Manager pour configurer le nouveau noeud en remplacement du noeud défaillant. 
---
= Sélectionnez Démarrer la récupération pour configurer le nœud de stockage StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir remplacé un noeud de stockage, vous devez sélectionner Démarrer la restauration dans Grid Manager pour configurer le nouveau noeud en remplacement du noeud défaillant.

.Avant de commencer
* Vous êtes connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez le link:../admin/admin-group-permissions.html["Maintenance ou autorisation d'accès racine"].
* Vous avez la phrase secrète pour le provisionnement.
* Vous avez déployé et configuré le nœud de remplacement.
* Vous disposez de la date de début des travaux de réparation pour les données avec code d'effacement.


.Description de la tâche
Si le nœud de stockage est installé en tant que conteneur sur un hôte Linux, vous devez effectuer cette étape uniquement si l'un d'entre eux est vrai :

* Vous deviez utiliser l' `--force`indicateur pour importer le nœud, ou vous avez émis `storagegrid node force-recovery _node-name_`
* Vous deviez réinstaller un nœud complet ou restaurer /var/local.


.Étapes
. Connectez-vous au nœud d'administration principal. Si le nœud d'administration principal est indisponible, utilisez un nœud d'administration non principal, s'il en existe un.
. Dans le Grid Manager, sélectionnez *Maintenance* > *Tasks* > *Node recovery*.
. Sélectionnez le nœud de grille à récupérer dans la liste nœuds en attente.
+
Les nœuds apparaissent dans la liste après leur échec, mais vous ne pouvez pas sélectionner un nœud tant qu'il n'a pas été réinstallé et qu'il est prêt pour la restauration.

. Saisissez la *phrase secrète de provisionnement*.
. Cliquez sur *Démarrer la récupération*.
. Surveillez la progression de la récupération en sélectionnant *Maintenance* > *Tasks* > *Node recovery* et en consultant la progression de la récupération.
+
** Si le nœud de la grille atteint l'étape « En attente d'instructions manuelles », vous devez link:../maintain/remounting-and-reformatting-storage-volumes-manual-steps.html["Remontez et reformatez manuellement les volumes de stockage"]. Une fois les instructions manuelles terminées, passez à link:../maintain/restoring-object-data-to-storage-volume.html["restaurer les données d'objet sur les volumes"].
** Si la récupération du nœud de grid est passée de *En cours* à *Récupéré* sans passer par l’étape « Waiting for manual steps », aucune autre action n’est requise.
+
[NOTE]
====
À tout moment pendant la récupération, vous pouvez sélectionner *Réinitialiser* pour lancer une nouvelle récupération. Une boîte de dialogue s'affiche, indiquant que le nœud restera dans un état indéterminé si vous réinitialisez la procédure.

Si vous souhaitez réessayer la récupération après avoir réinitialisé la procédure, vous devez restaurer le nœud de l'appliance à son état préinstallé, comme suit :

*** *VMware* : supprimez le nœud de grille virtuelle déployé. Ensuite, lorsque vous êtes prêt à redémarrer la restauration, redéployez le nœud.
*** *Linux* : redémarrez le nœud en exécutant cette commande sur l'hôte Linux : `storagegrid node force-recovery _node-name_`


====



