---
permalink: maintain/selecting-node-recovery-procedure.html 
sidebar: sidebar 
keywords: storagegrid, recover, procedure 
summary: Sélectionnez la procédure de récupération appropriée au type de nœud qui a échoué. 
---
= Sélectionnez la procédure de récupération du nœud StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sélectionnez la procédure de récupération appropriée au type de nœud qui a échoué.

[cols="1a,2a"]
|===
| Nœud de grille | Procédure de reprise 


 a| 
Nœud de stockage
 a| 
La procédure de récupération du nœud de stockage dépend du type de panne.

link:recovering-from-storage-node-failures.html["Restaurez les données après une panne de nœud de stockage"]



 a| 
Nœud d'administration
 a| 
La procédure nœud d'administration varie selon que vous devez restaurer le nœud d'administration principal ou un nœud d'administration non primaire.

link:recovering-from-admin-node-failures.html["Restaurez vos données après une panne de nœud d'administration"]



 a| 
Nœud de passerelle
 a| 
link:replacing-gateway-node.html["Restaurez les données à partir d'une défaillance de nœud de passerelle"]



 a| 
Nœud d'archivage
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/recovering-from-archive-node-failures.html["Restauration suite aux défaillances de nœud d'archivage (site de documentation StorageGRID 11.8)"^]

|===

NOTE: Si un serveur hébergeant plusieurs nœuds de grille tombe en panne, vous pouvez restaurer les nœuds dans n'importe quel ordre. Cependant, si le serveur défaillant héberge le nœud d'administration principal et qu'aucun nœud d'administration non principal n'existe, vous devez d'abord restaurer le nœud d'administration principal. Restaurer d'abord le nœud d'administration principal empêche les autres restaurations de nœuds d'être bloquées lorsqu'elles tentent de contacter le nœud d'administration principal. Si un nœud d'administration non principal est disponible, vous pouvez également l'utiliser pour restaurer d'autres nœuds afin que ces restaurations puissent se poursuivre sans contacter le nœud d'administration principal.
