---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 'Le quorum ADC garantit qu"un nombre minimal de services de contrôleur de domaine administratif (ADC) reste disponible sur chaque site. StorageGRID déplace automatiquement le service ADC lors de la mise hors service, si nécessaire.' 
---
= Qu’est-ce que le quorum ADC de StorageGRID ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le quorum ADC garantit qu'un nombre minimal de services de contrôleur de domaine administratif (ADC) reste disponible sur chaque site. StorageGRID déplace automatiquement le service ADC lors de la mise hors service, si nécessaire.

Le service ADC, qui se trouve sur certains nœuds de stockage, conserve les informations de topologie de grille et fournit des services de configuration à la grille. Le système StorageGRID nécessite que le quorum des services ADC soit disponible sur chaque site et à tout moment.

Vous ne pouvez pas désaffecter un nœud de stockage si le retrait du nœud entraînerait la non-conformité du quorum ADC. Pour satisfaire au quorum ADC lors d'une mise hors service, au moins trois nœuds de stockage sur chaque site doivent disposer du service ADC. Si un site dispose de plus de trois nœuds de stockage avec le service ADC, une simple majorité de ces nœuds doit rester disponible après la mise hors service : `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: Soyez prudent lorsque vous désaffectez des nœuds de stockage dans un grid contenant des nœuds de métadonnées uniquement basés sur des logiciels. Si vous désaffectez tous les nœuds configurés pour stocker _les deux_ objets et les métadonnées, la capacité de stockage des objets est supprimée de la grille. Pour plus d'informations sur les nœuds de stockage des métadonnées uniquement, reportez-vous à la sectionlink:../primer/what-storage-node-is.html#types-of-storage-nodes["Types de nœuds de stockage"].

Supposons par exemple qu'un site comprend actuellement six nœuds de stockage avec des services ADC et que vous souhaitez désaffecter trois nœuds de stockage. En raison de l'exigence de quorum ADC, vous devez effectuer deux procédures de mise hors service, comme suit :

* Dans la première procédure de mise hors service, vous devez vous assurer que quatre nœuds de stockage avec services ADC restent disponibles : `((0.5 * 6) + 1)`. Cela signifie que vous ne pouvez désaffecter que deux nœuds de stockage au départ.
* Lors de la deuxième procédure de mise hors service, vous pouvez supprimer le troisième nœud de stockage, car le quorum ADC ne nécessite désormais que trois services ADC pour rester disponibles : `((0.5 * 4) + 1)` .


Lors de la mise hors service d'un nœud de stockage hébergeant le service ADC, StorageGRID transfère automatiquement ce service vers un autre nœud de stockage du même site si cette mise hors service ramène le nombre de nœuds ADC du site en dessous du quorum. Ce transfert automatique nécessite que tous les nœuds du grid soient connectés et que des nœuds de stockage non-ADC soient disponibles sur le même site pour recevoir le service. La procédure de mise hors service garantit un minimum de trois nœuds de stockage ADC par site. Par exemple, si vous mettez hors service quatre ou six nœuds ADC sur un site, trois nœuds de stockage ADC resteront après la procédure, à condition que des nœuds non-ADC soient disponibles sur le même site.

Si le service ADC ne peut pas être déplacé automatiquement, vous pouvez link:move-adc-service.html["déplacer manuellement le service ADC"] le déplacer vers un autre nœud de stockage du même site ou link:../expand/index.html["ajouter un nouveau nœud de stockage dans une extension"] spécifier qu'il doit héberger un service ADC. Vous pouvez ensuite mettre hors service le nœud de stockage existant sans affecter le quorum.
