---
permalink: primer/hybrid-clouds-with-storagegrid.html 
sidebar: sidebar 
keywords: hybrid cloud, cloud storage pool, platform services, fabricpool, ontap 
summary: Utilisez StorageGRID dans une configuration de cloud hybride en implémentant la gestion des données pilotée par des règles pour stocker les objets dans les pools de stockage cloud, en exploitant les services de plateforme StorageGRID et en transférant les données de ONTAP vers StorageGRID avec NetApp FabricPool. 
---
= Clouds hybrides avec StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilisez StorageGRID dans une configuration de cloud hybride en implémentant la gestion des données pilotée par des règles pour stocker les objets dans les pools de stockage cloud, en exploitant les services de plateforme StorageGRID et en transférant les données de ONTAP vers StorageGRID avec NetApp FabricPool.



== Pools de stockage cloud

Vous pouvez stocker des objets en dehors du système StorageGRID grâce aux pools de stockage cloud. Par exemple, vous pouvez déplacer les objets rarement consultés vers un stockage cloud moins coûteux, comme Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud ou le Tier d'accès Archive dans le stockage Microsoft Azure Blob. Vous pouvez également conserver une sauvegarde dans le cloud d'objets StorageGRID qui peuvent être utilisés pour restaurer des données perdues en raison d'un volume de stockage ou d'une défaillance du nœud de stockage.

Le stockage de partenaires tiers est également pris en charge, y compris le stockage sur disque et sur bande.


NOTE: L'utilisation de pools de stockage cloud avec FabricPool n'est pas prise en charge en raison de la latence ajoutée pour extraire un objet de la cible du pool de stockage cloud.



== Services de plateforme S3

Les services de plateforme S3 vous permettent d'utiliser des services distants comme terminaux pour la réplication d'objets, les notifications d'événements ou l'intégration de la recherche. Les services de plateforme fonctionnent indépendamment des règles ILM du grid et sont activés pour les compartiments S3 individuels. Les services suivants sont pris en charge :

* Le service de réplication CloudMirror met automatiquement en miroir les objets spécifiés dans un compartiment S3 cible, qui peut se trouver sur Amazon S3 ou sur un second système StorageGRID.
* Le service de notification d'événements envoie des messages concernant des actions spécifiées à un terminal externe qui prend en charge la réception d'événements Amazon SNS (simple notification Service).
* Le service d'intégration de recherche envoie les métadonnées d'objet à un service Elasticsearch externe, ce qui permet de rechercher, de visualiser et d'analyser les métadonnées à l'aide d'outils tiers.


Vous pouvez, par exemple, utiliser la réplication CloudMirror pour mettre en miroir des enregistrements client spécifiques dans Amazon S3, puis exploiter les services AWS pour analyser vos données.



== Tiering des données ONTAP avec FabricPool

Vous pouvez réduire le coût du stockage ONTAP grâce au Tiering des données vers StorageGRID à l'aide de FabricPool. FabricPool permet le Tiering automatisé des données vers des tiers de stockage objet à faible coût, sur site ou hors site.

Contrairement aux solutions de hiérarchisation manuelle, FabricPool réduit le TCO en automatisant la hiérarchisation des données pour réduire le coût de stockage. Et offre les avantages du modèle économique du cloud grâce à son Tiering dans les clouds publics et privés y compris StorageGRID.

.Informations associées
* link:../ilm/what-cloud-storage-pool-is.html["Qu'est-ce que le pool de stockage cloud ?"]
* link:../tenant/what-platform-services-are.html["Gestion des services de plateforme"]
* link:../fabricpool/index.html["Configuration de StorageGRID pour FabricPool"]

