---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 'Des nœuds d"administration qui assurent les services de gestion tels que la configuration du système, la surveillance et la journalisation. Les nœuds d"administration peuvent également être utilisés pour équilibrer la charge du trafic client S3. Chaque grid doit être connecté à un nœud d"administration principal et doit comporter un nombre quelconque de nœuds d"administration non primaires pour assurer la redondance.' 
---
= Qu'est-ce qu'un nœud d'administration ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Des nœuds d'administration qui assurent les services de gestion tels que la configuration du système, la surveillance et la journalisation. Les nœuds d'administration peuvent également être utilisés pour équilibrer la charge du trafic client S3. Chaque grid doit être connecté à un nœud d'administration principal et doit comporter un nombre quelconque de nœuds d'administration non primaires pour assurer la redondance.



== Différences entre les nœuds d'administration principaux et non principaux

Lorsque vous vous connectez à Grid Manager ou au Gestionnaire de locataires, vous vous connectez à un noeud d'administration. Vous pouvez vous connecter à n'importe quel nœud d'administration et chaque nœud d'administration affiche une vue similaire du système StorageGRID. Toutefois, le nœud d'administration principal offre davantage de fonctionnalités que les nœuds d'administration non primaires. Par exemple, la plupart des procédures de maintenance doivent être effectuées à partir des nœuds d'administration principaux.

Le tableau récapitule les fonctionnalités des nœuds d'administration primaires et non primaires.

[cols="2a,1a,1a"]
|===
| Capacités | Nœud d'administration principal | Nœud d'administration non primaire 


 a| 
Comprend le <<ams,AMS>>service
 a| 
Oui
 a| 
Oui



 a| 
Comprend le <<cmn,CMN>>service
 a| 
Oui
 a| 
Non



 a| 
Comprend le <<nms,NMS>>service
 a| 
Oui
 a| 
Oui



 a| 
Comprend le <<prometheus,Prometheus>>service
 a| 
Oui
 a| 
Oui



 a| 
Comprend le <<ssm,SSM>>service
 a| 
Oui
 a| 
Oui



 a| 
Inclut les <<load-balancer,Équilibreur de charge>>services et<<high-availability,Haute disponibilité>>
 a| 
Oui
 a| 
Oui



 a| 
Prend en charge le <<mgmt-api,Interface du programme d'application de gestion>> (api de gestion)
 a| 
Oui
 a| 
Oui



 a| 
Peut être utilisé pour toutes les tâches de maintenance réseau, par exemple la modification d'adresse IP et la mise à jour de serveurs NTP
 a| 
Oui
 a| 
Non



 a| 
Peut effectuer un rééquilibrage du code d'effacement après l'extension du nœud de stockage
 a| 
Oui
 a| 
Non



 a| 
Peut être utilisé pour la procédure de restauration de volume
 a| 
Oui
 a| 
Oui



 a| 
Peut collecter des fichiers journaux et des données système à partir d'un ou plusieurs nœuds
 a| 
Oui
 a| 
Non



 a| 
Envoie des notifications d'alerte, des packages AutoSupport, des traps et des notifications SNMP
 a| 
Oui. Agit comme le <<preferred-sender,expéditeur préféré>>.
 a| 
Oui. Sert d'émetteur de secours.

|===


== [[preferred-sender]]nœud d'administration de l'expéditeur préféré

Si votre déploiement StorageGRID inclut plusieurs nœuds d'administration, le nœud d'administration principal est l'expéditeur préféré pour les notifications d'alerte, les packages AutoSupport, les traps et les notifications SNMP.

Dans le cadre des opérations système normales, seul l'expéditeur préféré envoie des notifications. Cependant, tous les autres nœuds d'administration contrôlent l'expéditeur préféré. Si un problème est détecté, les autres nœuds d'administration agissent en tant que _expéditeurs de secours_.

Plusieurs notifications peuvent être envoyées dans les cas suivants :

* Si les nœuds d'administration sont « débarqués » les uns des autres, l'expéditeur préféré et les expéditeurs en veille essayeront d'envoyer des notifications et plusieurs copies de notifications peuvent être reçues.
* Si l'expéditeur en veille détecte des problèmes avec l'expéditeur préféré et commence à envoyer des notifications, l'expéditeur préféré peut retrouver sa capacité à envoyer des notifications. Dans ce cas, des notifications en double peuvent être envoyées. L'expéditeur en attente interrompt l'envoi des notifications lorsqu'il ne détecte plus d'erreurs sur l'expéditeur préféré.
+

NOTE: Lorsque vous testez les packages AutoSupport, tous les nœuds d'administration envoient le test. Lorsque vous testez les notifications d'alertes, vous devez vous connecter à chaque nœud d'administration pour vérifier la connectivité.





== Services primaires pour les nœuds d'administration

Le tableau ci-dessous présente les services principaux pour les nœuds d'administration, mais ce tableau ne répertorie pas tous les services de nœud.

[cols="1a,2a"]
|===
| Service | Fonction de touche 


 a| 
[[ams]]système de gestion de l'audit (AMS)
 a| 
Suit l'activité et les événements du système.



 a| 
[[cmn]]nœud de gestion de la configuration (CMN)
 a| 
Gestion de la configuration à l'échelle du système.



 a| 
[[haute disponibilité]]haute disponibilité
 a| 
Gère les adresses IP virtuelles haute disponibilité pour les groupes de nœuds d'administration et de nœuds de passerelle.

*Remarque :* ce service se trouve également sur les nœuds de passerelle.



 a| 
[[équilibreur de charge]]équilibreur de charge
 a| 
Équilibrage de la charge du trafic S3 des clients vers les nœuds de stockage

*Remarque :* ce service se trouve également sur les nœuds de passerelle.



 a| 
[[mgmt-api]]interface de programme d'application de gestion (mgmt-api)
 a| 
Traite les requêtes à partir de l'API de gestion Grid et de l'API de gestion des locataires.



 a| 
[[nms]]système de gestion de réseau (NMS)
 a| 
Fournit des fonctionnalités pour le gestionnaire de grille.



 a| 
[[prometheus]]Prometheus
 a| 
Collecte et stocke les mesures de séries chronologiques des services sur tous les nœuds.



 a| 
[[ssm]]moniteur d'état du serveur (SSM)
 a| 
Surveille le système d'exploitation et le matériel sous-jacent.

|===