---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines, StorageGRID 
summary: Vous pouvez étendre votre système StorageGRID en ajoutant un nouveau site. 
---
= Instructions pour l'ajout d'un nouveau site dans StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez étendre votre système StorageGRID en ajoutant un nouveau site.



[[guidelines-for-adding-a-site]]
== Instructions pour l'ajout d'un site

Avant d'ajouter un site, vérifiez les exigences et limites suivantes :

* Vous ne pouvez ajouter qu'un site par opération d'extension.
* Vous ne pouvez pas ajouter de nœuds grid à un site existant dans le cadre d'une même extension.
* Chaque site doit comporter au moins trois nœuds de stockage. Il peut s'agir de n'importe quelle combinaison de nœuds de stockage combinés et de nœuds de stockage de métadonnées uniquement. S'il y a plus de trois nœuds de stockage, il peut s'agir de n'importe quelle combinaison de nœuds de stockage combinés, de nœuds de stockage de métadonnées uniquement et de nœuds de stockage de données uniquement, à condition que trois services ADC soient disponibles. Pour plus d'informations, consultez link:../primer/what-storage-node-is.html#required-storage-nodes-per-grid-and-per-site["Nœuds de stockage requis par grille et par site"].
* L'ajout d'un nouveau site n'augmente pas automatiquement le nombre d'objets que vous pouvez stocker. La capacité totale d'objets d'une grille dépend de l'espace de stockage disponible, de la politique ILM et de la capacité de métadonnées de chaque site.
* Lors du dimensionnement d'un nouveau site, vous devez vous assurer qu'il inclut suffisamment de capacité de métadonnées.
+
StorageGRID conserve une copie de toutes les métadonnées des objets sur chaque site. Lorsque vous ajoutez un nouveau site, assurez-vous qu'il dispose d'une capacité de métadonnées suffisante pour les métadonnées des objets existants et pour la croissance future.

+
Pour plus d'informations, veuillez consulter les documents suivants :

+
** link:../admin/managing-object-metadata-storage.html["Gérer le stockage des métadonnées d'objet"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["Surveillez la capacité des métadonnées d'objet pour chaque nœud de stockage"]


* Vous devez tenir compte de la bande passante réseau disponible entre les sites et du niveau de latence du réseau. Les mises à jour des métadonnées sont continuellement répliquées entre les sites, même si tous les objets sont stockés uniquement sur le site où ils sont ingéré.
+
Pour éviter les mauvaises performances dues à la latence :

+
** Le codage par effacement n'est pas recommandé entre les sites présentant une latence supérieure à 100 ms.
** Les sites de votre système StorageGRID ne doivent pas s'étendre sur de grandes distances géographiques, par exemple, sur plusieurs continents.


* Votre système StorageGRID reste opérationnel pendant son développement. Vous devez donc revoir les règles ILM avant de démarrer la procédure d'extension. Vous devez vous assurer que les copies d'objet ne sont pas stockées sur le nouveau site tant que la procédure d'extension n'est pas terminée.
+
Par exemple, avant de commencer l'extension, vérifiez si des règles utilisent le pool de stockage par défaut (All Storage Nodes). Si c'est le cas, créez un nouveau pool de stockage avec les Storage Nodes existants et mettez à jour vos règles ILM pour utiliser le nouveau pool de stockage. Sinon, les objets sont copiés sur le nouveau site dès que le premier nœud de ce site devient actif.

+
Pour plus d'informations sur la modification d'une politique ILM lors de l'ajout d'un nouveau site, reportez-vous à la link:../ilm/example-6-changing-ilm-policy.html["Exemple de modification d'une règle ILM"].


