---
permalink: expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html 
sidebar: sidebar 
keywords: grid node, add node, add site, expand, expansion, StorageGRID 
summary: 'Suivez cette procédure pour ajouter des nœuds de grille à des sites existants ou pour ajouter un nouveau site. Vous ne pouvez effectuer qu"un seul type d"extension à la fois.' 
---
= Résumé du processus d'ajout de nœuds de grille ou de nouveaux sites à StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Suivez cette procédure pour ajouter des nœuds de grille à des sites existants ou pour ajouter un nouveau site. Vous ne pouvez effectuer qu'un seul type d'extension à la fois.

.Avant de commencer
* Vous avez le link:../admin/admin-group-permissions.html["Accès racine ou autorisation de maintenance"].
* Tous les nœuds existants de la grille sont opérationnels sur tous les sites.
* Toute procédure d'extension, de mise à niveau, de déclassement ou de restauration est terminée.
+

NOTE: Vous ne pouvez pas démarrer une extension pendant qu'une autre procédure d'extension, de mise à niveau, de récupération ou de mise hors service active est en cours. Toutefois, si nécessaire, vous pouvez interrompre une procédure de mise hors service pour démarrer une extension.



.Étapes
. link:updating-subnets-for-grid-network.html["Mise à jour des sous-réseaux pour le réseau Grid"].
. link:deploying-new-grid-nodes.html["Déployez les nouveaux nœuds de grille"].
. link:performing-expansion.html["Effectuer l'extension"].

