---
permalink: expand/copying-prometheus-metrics.html 
sidebar: sidebar 
keywords: prometheus, copy metrics, Admin Node expansion 
summary: 'Après avoir ajouté un nouveau nœud d"administration, vous pouvez éventuellement copier les metrics historiques gérés par Prometheus du nœud d"administration principal vers le nouveau nœud d"administration. La copie des metrics garantit la cohérence des mesures historiques entre les nœuds d"administration.' 
---
= Copie des metrics Prometheus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir ajouté un nouveau nœud d'administration, vous pouvez éventuellement copier les metrics historiques gérés par Prometheus du nœud d'administration principal vers le nouveau nœud d'administration. La copie des metrics garantit la cohérence des mesures historiques entre les nœuds d'administration.

.Avant de commencer
* Le nouveau nœud d'administration est installé et en cours d'exécution.
* Vous avez le `Passwords.txt` fichier.
* Vous avez la phrase secrète pour le provisionnement.


.Description de la tâche
Lorsque vous ajoutez un nœud d'administration, le processus d'installation logicielle crée une nouvelle base de données Prometheus. Vous pouvez conserver la cohérence des metrics historiques entre les nœuds en copiant la base de données Prometheus du nœud d'administration principal (_source Admin Node_) vers le nouveau nœud d'administration.


NOTE: La copie de la base de données Prometheus peut prendre une heure ou plus. Certaines fonctionnalités de Grid Manager ne seront pas disponibles lorsque les services sont arrêtés sur le nœud d'administration source.

.Étapes
. Connectez-vous au nœud d'administration source :
+
.. Entrez la commande suivante : `ssh admin@_grid_node_IP_`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour basculer en root : `su -`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.


. Depuis le nœud d'administration source, arrêtez le service Prometheus : `service prometheus stop`
. Suivez les étapes suivantes sur le nouveau nœud d'administration :
+
.. Connectez-vous au nouveau nœud d'administration :
+
... Entrez la commande suivante : `ssh admin@_grid_node_IP_`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour basculer en root : `su -`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.


.. Arrêtez le service Prometheus : `service prometheus stop`
.. Ajoutez la clé privée SSH à l'agent SSH. Entrer :``ssh-add``
.. Entrez le mot de passe d'accès SSH indiqué dans le `Passwords.txt` fichier.
.. Copiez la base de données Prometheus du nœud d'administration source vers le nouveau nœud d'administration : `/usr/local/prometheus/bin/prometheus-clone-db.sh _Source_Admin_Node_IP_`
.. Lorsque vous y êtes invité, appuyez sur *Enter* pour confirmer que vous souhaitez détruire la nouvelle base de données Prometheus sur le nouveau noeud d'administration.
+
La base de données Prometheus d'origine et ses données historiques sont copiées sur le nouveau nœud d'administration. Une fois l'opération de copie terminée, le script démarre le nouveau nœud d'administration. L'état suivant apparaît :

+
`Database cloned, starting services`

.. Lorsque vous n'avez plus besoin d'un accès sans mot de passe à d'autres serveurs, supprimez la clé privée de l'agent SSH. Entrez :
+
`ssh-add -D`



. Redémarrez le service Prometheus sur le nœud d'administration source.
+
`service prometheus start`


