---
sidebar: sidebar 
permalink: expand/copying-audit-logs.html 
keywords: copy audit log, Admin Node expansion, 
summary: 'Lorsque vous ajoutez un nouveau nœud d"administration via une procédure d"extension, son service AMS enregistre uniquement les événements et les actions qui se produisent après son adhésion au système.  Si nécessaire, vous pouvez copier les journaux d"audit d"un nœud d"administration précédemment installé vers le nouveau nœud d"administration d"extension afin qu"il soit synchronisé avec le reste du système StorageGRID .' 
---
= Copie des journaux d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous ajoutez un nouveau nœud d'administration via une procédure d'extension, son service AMS enregistre uniquement les événements et les actions qui se produisent après son adhésion au système.  Si nécessaire, vous pouvez copier les journaux d'audit d'un nœud d'administration précédemment installé vers le nouveau nœud d'administration d'extension afin qu'il soit synchronisé avec le reste du système StorageGRID .

.Avant de commencer
* Vous avez terminé les étapes d'extension requises pour ajouter un nœud d'administration.
* Vous avez le `Passwords.txt` fichier.


.Description de la tâche
Pour rendre disponibles les messages d'audit historiques sur un nouveau nœud d'administration, vous devez copier manuellement les fichiers journaux d'audit d'un nœud d'administration existant vers le nœud d'administration d'extension.

[NOTE]
====
Par défaut, les informations d’audit sont envoyées à l’ `localaudit` connectez-vous sur chaque nœud.  Pour utiliser cette procédure, vous devez avoir configuré les nœuds d’administration comme destination d’audit comme suit :

* Vous avez configuré *Nœuds d'administration/nœuds locaux* comme destination du journal.
* Vous avez configuré *Nœuds d'administration et serveur syslog externe* comme destination du journal.


Se référer àlink:../monitor/configure-audit-messages.html["Configurer les messages d'audit et le serveur syslog externe"] pour plus de détails.

====
.Étapes
. Connectez-vous au nœud d'administration principal :
+
.. Entrez la commande suivante : `ssh _admin@_primary_Admin_Node_IP_`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour basculer en root : `su -`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Arrêtez le service AMS pour l'empêcher de créer un nouveau fichier : `service ams stop`
. Accédez au répertoire d'exportation d'audit :
+
`cd /var/local/audit/export/`

. Renommer la source `audit.log` fichier pour garantir qu'il n'écrase pas le fichier sur le nœud d'administration d'extension sur lequel vous le copiez :
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. Copiez tous les fichiers journaux d'audit vers l'emplacement de destination du nœud d'administration d'extension :
+
`scp -p * _IP_address_:/var/local/audit/export/`

. Si vous êtes invité à saisir la phrase de passe pour `/root/.ssh/id_rsa`, entrez le mot de passe d'accès SSH du nœud d'administration principal répertorié dans `Passwords.txt` le fichier.
. Restaurez le fichier d'origine `audit.log` :
+
`mv _new_name_.txt audit.log`

. Démarrez le service AMS :
+
`service ams start`

. Déconnexion du serveur :
+
`exit`

. Connectez-vous au nœud d'administration d'extension :
+
.. Entrez la commande suivante : `ssh admin@_expansion_Admin_Node_IP_`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
.. Entrez la commande suivante pour basculer en root : `su -`
.. Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



. Mettez à jour les paramètres utilisateur et groupe des fichiers journaux d'audit :
+
`cd /var/local/audit/export/`

+
`chown ams-user:bycast *`

. Déconnexion du serveur :
+
`exit`


