---
permalink: expand/verifying-storage-node-is-active.html 
sidebar: sidebar 
keywords: expand, expansion, add storage nodes, verify node is active 
summary: 'Une fois une opération d"extension qui ajoute de nouveaux nœuds de stockage terminée, le système StorageGRID doit démarrer automatiquement à l"aide des nouveaux nœuds de stockage. Vous devez utiliser le système StorageGRID pour vérifier que le nouveau nœud de stockage est actif.' 
---
= Vérifiez que le nœud de stockage est actif
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois une opération d'extension qui ajoute de nouveaux nœuds de stockage terminée, le système StorageGRID doit démarrer automatiquement à l'aide des nouveaux nœuds de stockage. Vous devez utiliser le système StorageGRID pour vérifier que le nouveau nœud de stockage est actif.

.Étapes
. Connectez-vous au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
. Sélectionnez *NODES* > *_expansion Storage Node_* > *Storage*.
. Placez votre curseur sur le graphique *stockage utilisé - données d'objet* pour afficher la valeur de *utilisé*, qui est la quantité d'espace utilisable total utilisée pour les données d'objet.
. Vérifiez que la valeur de *utilisé* augmente au fur et à mesure que vous déplacez le curseur vers la droite du graphique.

