---
permalink: expand/vmware-adding-storage-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expand, expansion, storage node, add storage volumes, VMware 
summary: Si un nœud de stockage comprend moins de 16 volumes de stockage, vous pouvez augmenter sa capacité en utilisant VMware vSphere pour ajouter des volumes. 
---
= VMware : ajoutez des volumes de stockage au nœud de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si un nœud de stockage comprend moins de 16 volumes de stockage, vous pouvez augmenter sa capacité en utilisant VMware vSphere pour ajouter des volumes.

.Avant de commencer
* Vous avez accès aux instructions d'installation de StorageGRID pour les déploiements.
+
** link:../vmware/index.html["Installez StorageGRID sur VMware"]


* Vous avez le `Passwords.txt` fichier.
* Vous avez link:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"].



CAUTION: N'essayez pas d'ajouter des volumes de stockage à un nœud de stockage pendant qu'une mise à niveau logicielle, une procédure de restauration ou une autre procédure d'extension est active.

.Description de la tâche
Le nœud de stockage n'est pas disponible brièvement lorsque vous ajoutez des volumes de stockage. Cette procédure doit être effectuée sur un seul nœud de stockage à la fois pour éviter d'affecter les services de grid côté client.

.Étapes
. Si nécessaire, installez un nouveau matériel de stockage et créez de nouveaux datastores VMware.
. Ajoutez un ou plusieurs disques durs à la machine virtuelle pour l'utiliser comme stockage (magasins d'objets).
+
.. Ouvrez le client VMware vSphere.
.. Modifiez les paramètres de la machine virtuelle pour ajouter un ou plusieurs disques durs supplémentaires.


+
Les disques durs sont généralement configurés en tant que disques d'ordinateurs virtuels (VMDK, Virtual machine Disks). Les VMDK sont plus fréquemment utilisés et plus faciles à gérer, tandis que les RDM peuvent fournir de meilleures performances pour les charges de travail utilisant des objets de plus grande taille (par exemple, plus de 100 Mo). Pour plus d'informations sur l'ajout de disques durs aux machines virtuelles, consultez la documentation de VMware vSphere.

. Redémarrez la machine virtuelle à l'aide de l'option *redémarrer le système d'exploitation invité* du client VMware vSphere ou en entrant la commande suivante dans une session ssh sur la machine virtuelle :``sudo reboot``
+

NOTE: N'utilisez pas *Power Off* ou *Reset* pour redémarrer la machine virtuelle.

. Configurez le nouveau stockage pour qu'il soit utilisé par le nœud de stockage :
+
.. Connectez-vous au nœud grid :
+
... Entrez la commande suivante : `ssh admin@_grid_node_IP_`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour basculer en root : `su -`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier. Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.


.. Configurer les nouveaux volumes de stockage :
+
`sudo add_rangedbs.rb`

+
Ce script trouve tous les nouveaux volumes de stockage et vous invite à les formater.

.. Saisissez *y* pour accepter le formatage.
.. Si l'un des volumes a déjà été formaté, décidez si vous souhaitez les reformater.
+
*** Entrez *y* pour reformater.
*** Saisissez *n* pour ignorer le reformatage.




+
Le `setup_rangedbs.sh` script s'exécute automatiquement.

. Vérifier que les services démarrent correctement :
+
.. Afficher une liste de l'état de tous les services sur le serveur :
+
`sudo storagegrid-status`

+
L'état est mis à jour automatiquement.

.. Attendez que tous les services soient en cours d'exécution ou vérifiés.
.. Quitter l'écran d'état :
+
`Ctrl+C`



. Vérifiez que le nœud de stockage est en ligne :
+
.. Connectez-vous au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
.. Sélectionnez *SUPPORT* > *Outils* > *topologie de grille*.
.. Sélectionnez *_site_* > *_Storage Node_* > *LDR* > *Storage*.
.. Sélectionnez l'onglet *Configuration*, puis l'onglet *main*.
.. Si la liste déroulante État de stockage - souhaité* est définie sur lecture seule ou hors ligne, sélectionnez *en ligne*.
.. Sélectionnez *appliquer les modifications*.


. Pour afficher les nouveaux magasins d'objets :
+
.. Sélectionnez *NODES* > *_site_* > *_Storage Node_* > *Storage*.
.. Affichez les détails dans le tableau *magasins d'objets*.




.Résultat
Vous pouvez utiliser la capacité étendue des nœuds de stockage pour sauvegarder les données d'objet.
