---
permalink: troubleshoot/investigating-potentially-lost-objects.html 
sidebar: sidebar 
keywords: lost objects, investigating, objects 
summary: 'Lorsque l"alerte *Objets potentiellement perdus* est déclenchée, vous devez enquêter immédiatement.  Collectez des informations sur les objets concernés et contactez le support technique.' 
---
= Enquêter sur les objets potentiellement perdus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque l'alerte *Objets potentiellement perdus* est déclenchée, vous devez enquêter immédiatement.  Collectez des informations sur les objets concernés et contactez le support technique.

.Avant de commencer
* Vous devez être connecté au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
* Vous avez link:../admin/admin-group-permissions.html["autorisations d'accès spécifiques"].
* Vous devez avoir le `Passwords.txt` fichier.


.Description de la tâche
L'alerte *Objets potentiellement perdus* indique que, selon les informations disponibles dans StorageGRID, il n'existe aucune copie d'un objet dans la grille.  Les données ont peut-être été définitivement perdues.

Recherchez immédiatement les alertes relatives à la perte d'objet. Vous devrez peut-être prendre des mesures pour éviter d'autres pertes de données. Dans certains cas, vous pourrez peut-être restaurer un objet perdu si vous prenez une action d'invite.


CAUTION: Si plus de 10 objets sont signalés comme perdus, contactez le support technique.  Ne suivez pas cette procédure vous-même.

.Étapes
. Sélectionnez *Nœuds*.
. Sélectionnez *_Storage Node_* > *objets*.
. Vérifiez le nombre d'objets perdus affichés dans le tableau nombres d'objets.
+
Ce nombre indique le nombre total d'objets que ce nœud de grille détecte comme manquant dans l'ensemble du système StorageGRID. La valeur est la somme des compteurs d'objets perdus du composant de stockage de données dans les services LDR et DDS.

. À partir d'un nœud d'administration,link:../audit/accessing-audit-log-file.html["accédez au journal d'audit"] pour déterminer l'identifiant unique (UUID) de l'objet qui a déclenché l'alerte *Objets potentiellement perdus* :
+
.. Connectez-vous au nœud grid :
+
... Entrez la commande suivante : `ssh admin@grid_node_IP`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour basculer en root : `su -`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier. Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.


.. Accédez au répertoire dans lequel se trouvent les journaux d'audit.
+
--
Le répertoire du journal d'audit et les nœuds applicables dépendent de vos paramètres de destination d'audit.

[cols="1a,2a"]
|===
| Option | Destination 


 a| 
Nœuds locaux (par défaut)
 a| 
`/var/local/log/localaudit.log`



 a| 
Nœuds d'administration/nœuds locaux
 a| 
*** Nœuds d'administration (primaires et non principaux) : `/var/local/audit/export/audit.log`
*** Tous les nœuds : le `/var/local/log/localaudit.log` fichier est généralement vide ou manquant dans ce mode.




 a| 
Serveur syslog externe
 a| 
`/var/local/log/localaudit.log`

|===
En fonction de vos paramètres de destination d'audit, entrez : `cd /var/local/log` ou `/var/local/audit/export/`

Pour en savoir plus, consultezlink:../monitor/configure-log-management.html#select-log-location["Sélectionnez l'emplacement du journal"] .

--
.. Utilisez grep pour extraire les messages d'audit objet perdu (OLST). Entrer : `grep OLST audit_file_name`
.. Notez la valeur UUID incluse dans le message.
+
[listing]
----
Admin: # grep OLST audit.log
2020-02-12T19:18:54.780426 [AUDT:[CBID(UI64):0x38186FE53E3C49A5][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[PATH(CSTR):"source/cats"][NOID(UI32):12288733][VOLI(UI64):3222345986][RSLT(FC32):NONE][AVER(UI32):10]
[ATIM(UI64):1581535134780426][ATYP(FC32):OLST][ANID(UI32):12448208][AMID(FC32):ILMX][ATID(UI64):7729403978647354233]]
----


. Rechercher les métadonnées de l'objet perdu à l'aide de l'UUID :
+
.. Sélectionnez *ILM* > *Object metadata Lookup*.
.. Entrez l'UUID et sélectionnez *Rechercher*.
.. Vérifiez les emplacements dans les métadonnées et prenez les mesures appropriées :
+
[cols="2a,4a"]
|===
| Les métadonnées | Conclusion 


 a| 
<object_identifier> d'objet introuvable
 a| 
Si l'objet n'est pas trouvé, le message « ERROR":" » est renvoyé.

Si l'objet n'est pas trouvé,<<reset-lost-obj-count,réinitialiser le compteur d'objets potentiellement perdus>> pour effacer l'alerte.  L’absence d’un objet indique que l’objet a été intentionnellement supprimé.



 a| 
Emplacements > 0
 a| 
Si des emplacements sont répertoriés dans la sortie, l'alerte *Objets potentiellement perdus* peut être un faux positif.

Vérifiez que les objets existent. Utilisez l'ID de nœud et le chemin du fichier indiqués dans la sortie pour confirmer que le fichier objet se trouve à l'emplacement indiqué.

Si les objets existent,<<reset-lost-obj-count,réinitialiser le compteur d'objets potentiellement perdus>> pour effacer l'alerte.



 a| 
Emplacements = 0
 a| 
S'il n'y a aucun emplacement répertorié dans la sortie, l'objet est potentiellement manquant.  Contactez le support technique.

L'assistance technique peut vous demander si une procédure de restauration du stockage est en cours. Voir les informations sur link:../maintain/restoring-volume.html["Restauration des données d'objet à l'aide de Grid Manager"] et link:../maintain/restoring-object-data-to-storage-volume.html["restauration des données d'objet vers un volume de stockage"].

|===


. [[reset-lost-obj-count]]Après avoir résolu les problèmes d'objets perdus, réinitialisez le compteur Objets potentiellement perdus pour garantir que les alertes ne sont pas de faux positifs :
+
.. Sélectionnez *Nœuds*.
.. Sélectionnez *_Nœud de stockage_* > *Tâches*.
.. Dans la section Réinitialiser le compteur d'objets potentiellement perdus, sélectionnez *Réinitialiser*.



