---
permalink: troubleshoot/searching-for-and-restoring-potentially-lost-objects.html 
sidebar: sidebar 
keywords: how to search lost object, how to restore lost object, how to find lost object 
summary: 'Il est possible de trouver et de restaurer des objets qui ont déclenché une alerte *Object Lost* et une alarme héritée Lost Objects (LOST) et que vous avez identifié comme potentiellement perdus.' 
---
= Recherche et restauration d'objets potentiellement perdus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il est possible de trouver et de restaurer des objets qui ont déclenché une alerte *Object Lost* et une alarme héritée Lost Objects (LOST) et que vous avez identifié comme potentiellement perdus.

.Avant de commencer
* Vous disposez de l'UUID de tout objet perdu, tel qu'identifié dans link:../troubleshoot/investigating-lost-objects.html["Rechercher les objets perdus"].
* Vous avez le `Passwords.txt` fichier.


.Description de la tâche
Vous pouvez suivre cette procédure pour rechercher les copies répliquées de l'objet perdu ailleurs dans la grille. Dans la plupart des cas, l'objet perdu est introuvable. Toutefois, dans certains cas, vous pouvez trouver et restaurer un objet répliqué perdu si vous prenez une action rapide.


CAUTION: Pour obtenir de l'aide sur cette procédure, contactez le support technique.

.Étapes
. À partir d'un nœud d'administration, recherchez dans les journaux d'audit les emplacements d'objets possibles :
+
.. Connectez-vous au nœud grid :
+
... Entrez la commande suivante : `ssh admin@grid_node_IP`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour basculer en root : `su -`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier. Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.


.. Accédez au répertoire où se trouvent les journaux d'audit : `cd /var/local/log/`
+
[NOTE]
====
link:../monitor/configure-audit-messages.html#select-audit-information-destinations["Découvrez les destinations des informations d'audit"].

====
.. Utilisez grep pour extraire le link:../audit/object-ingest-transactions.html["messages d'audit associés à l'objet potentiellement perdu"] et les envoyer à un fichier de sortie. Entrer : `grep uuid-value audit_file_name > output_file_name`
+
Par exemple :

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > messages_about_lost_object.txt
----
.. Utilisez grep pour extraire les messages d'audit emplacement perdu (LLST) de ce fichier de sortie. Entrer : `grep LLST output_file_name`
+
Par exemple :

+
[listing]
----
Admin: # grep LLST messages_about_lost_objects.txt
----
+
Un message d'audit LLST ressemble à cet exemple de message.

+
[listing]
----
[AUDT:\[NOID\(UI32\):12448208\][CBIL(UI64):0x38186FE53E3C49A5]
[UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"][LTYP(FC32):CLDI]
[PCLD\(CSTR\):"/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%\#3tN6"\]
[TSRC(FC32):SYST][RSLT(FC32):NONE][AVER(UI32):10][ATIM(UI64):
1581535134379225][ATYP(FC32):LLST][ANID(UI32):12448208][AMID(FC32):CLSM]
[ATID(UI64):7086871083190743409]]
----
.. Recherchez le champ PCLD et LE champ NOID dans le message LLST.
+
Le cas échéant, la valeur de PCLD correspond au chemin complet du disque vers la copie de l'objet répliqué manquante. La valeur de NOID est l'ID de nœud du LDR dans lequel une copie de l'objet peut être trouvée.

+
Si vous trouvez un emplacement d'objet, vous pourrez peut-être restaurer l'objet.

.. Recherchez le nœud de stockage associé à cet ID de nœud LDR. Dans le Gestionnaire de grille, sélectionnez *SUPPORT* > *Outils* > *topologie de grille*. Sélectionnez ensuite *_Data Center_* > *_Storage Node_* > *LDR*.
+
L'ID de nœud du service LDR se trouve dans le tableau informations sur le nœud. Vérifiez les informations pour chaque nœud de stockage jusqu'à ce que vous trouviez celui qui héberge ce LDR.



. Déterminez si l'objet existe sur le nœud de stockage indiqué dans le message d'audit :
+
.. Connectez-vous au nœud grid :
+
... Entrez la commande suivante : `ssh admin@grid_node_IP`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour basculer en root : `su -`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
+
Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.



.. Déterminez si le chemin du fichier de l'objet existe.
+
Pour le chemin du fichier de l'objet, utilisez la valeur PCLD du message d'audit LLST.

+
Par exemple, entrez :

+
[listing]
----
ls '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+

NOTE: Placez toujours le chemin d'accès au fichier d'objet entre guillemets simples dans des commandes pour échapper à tout caractère spécial.

+
*** Si le chemin d'accès à l'objet est introuvable, l'objet est perdu et ne peut pas être restauré à l'aide de cette procédure. Contactez l'assistance technique.
*** Si le chemin d'accès à l'objet est trouvé, passez à l'étape suivante. Vous pouvez essayer de restaurer à nouveau l'objet trouvé dans StorageGRID.




. Si le chemin d'accès à l'objet a été trouvé, essayez de restaurer l'objet sur StorageGRID :
+
.. À partir du même nœud de stockage, modifiez la propriété du fichier objet afin qu'il puisse être géré par StorageGRID. Entrer : `chown ldr-user:bycast 'file_path_of_object'`
.. Telnet vers localhost 1402 pour accéder à la console LDR. Entrer : `telnet 0 1402`
.. Entrer : `cd /proc/STOR`
.. Entrer : `Object_Found 'file_path_of_object'`
+
Par exemple, entrez :

+
[listing]
----
Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+
L'exécution `Object_Found` de la commande avertit la grille de l'emplacement de l'objet. Elle déclenche également les règles ILM actives, qui ajoutent des copies supplémentaires comme spécifié dans chaque règle.

+

NOTE: Si le nœud de stockage sur lequel vous avez trouvé l'objet est hors ligne, vous pouvez le copier sur n'importe quel nœud de stockage en ligne. Placez l'objet dans un répertoire /var/local/rangedb du noeud de stockage en ligne. Ensuite, exécutez la `Object_Found` commande en utilisant ce chemin de fichier vers l'objet.

+
*** Si l'objet ne peut pas être restauré, la `Object_Found` commande échoue. Contactez l'assistance technique.
*** Si l'objet a été restauré avec succès dans StorageGRID, un message de réussite s'affiche. Par exemple :
+
[listing]
----
ade 12448208: /proc/STOR > Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'

ade 12448208: /proc/STOR > Object found succeeded.
First packet of file was valid. Extracted key: 38186FE53E3C49A5
Renamed '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6' to '/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila#3udu'
----
+
Passez à l'étape suivante.





. Si l'objet a été restauré dans StorageGRID, vérifiez que les nouveaux emplacements ont été créés :
+
.. Connectez-vous au Gestionnaire de grille à l'aide d'un link:../admin/web-browser-requirements.html["navigateur web pris en charge"].
.. Sélectionnez *ILM* > *Object metadata Lookup*.
.. Entrez l'UUID et sélectionnez *Rechercher*.
.. Examinez les métadonnées et vérifiez les nouveaux emplacements.


. À partir d'un nœud d'administration, recherchez dans les journaux d'audit le message d'audit ORLM correspondant à cet objet pour vous assurer que la gestion du cycle de vie des informations (ILM) a placé des copies, si nécessaire.
+
.. Connectez-vous au nœud grid :
+
... Entrez la commande suivante : `ssh admin@grid_node_IP`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier.
... Entrez la commande suivante pour basculer en root : `su -`
... Saisissez le mot de passe indiqué dans le `Passwords.txt` fichier. Lorsque vous êtes connecté en tant que root, l'invite passe de `$` à `#`.


.. Accédez au répertoire où se trouvent les journaux d'audit : `cd /var/local/log/`
.. Utilisez grep pour extraire les messages d'audit associés à l'objet dans un fichier de sortie. Entrer : `grep uuid-value audit_file_name > output_file_name`
+
Par exemple :

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > messages_about_restored_object.txt
----
.. Utilisez grep pour extraire les messages d'audit règles objet met (ORLM) de ce fichier de sortie. Entrer : `grep ORLM output_file_name`
+
Par exemple :

+
[listing]
----
Admin: # grep ORLM messages_about_restored_object.txt
----
+
Un message d'audit ORLM ressemble à cet exemple de message.

+
[listing]
----
[AUDT:[CBID(UI64):0x38186FE53E3C49A5][RULE(CSTR):"Make 2 Copies"]
[STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[LOCS(CSTR):"**CLDI 12828634 2148730112**, CLDI 12745543 2147552014"]
[RSLT(FC32):SUCS][AVER(UI32):10][ATYP(FC32):ORLM][ATIM(UI64):1563398230669]
[ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
.. Recherchez le champ EMPLACEMENTS dans le message d'audit.
+
Le cas échéant, la valeur de CLDI dans LES EMPLACEMENTS est l'ID de nœud et l'ID de volume sur lequel une copie d'objet a été créée. Ce message indique que la ILM a été appliquée et que deux copies d'objet ont été créées à deux emplacements dans la grille.



. link:resetting-lost-and-missing-object-counts.html["Réinitialise le nombre d'objets perdus et manquants"] Dans le Gestionnaire de grille.

