---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: 'Les objets peuvent être récupérés pour plusieurs raisons, y compris les demandes de lecture provenant d"une application client, les vérifications en arrière-plan des données d"objet répliquées, les réévaluations ILM et la restauration des données d"objet lors de la restauration d"un nœud de stockage.' 
---
= Dépanner les données d'objet perdues ou manquantes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les objets peuvent être récupérés pour plusieurs raisons, y compris les demandes de lecture provenant d'une application client, les vérifications en arrière-plan des données d'objet répliquées, les réévaluations ILM et la restauration des données d'objet lors de la restauration d'un nœud de stockage.

Le système StorageGRID utilise les informations de localisation dans les métadonnées d'un objet pour déterminer à partir de quel emplacement récupérer l'objet.  Si aucune copie de l'objet n'est trouvée à l'emplacement prévu, le système tente de récupérer une autre copie de l'objet ailleurs dans le système, en supposant que la politique ILM contient une règle permettant de créer deux ou plusieurs copies de l'objet.

Si cette récupération réussit, le système StorageGRID remplace la copie manquante de l'objet.  Dans le cas contraire, l'alerte *Objets potentiellement perdus* est déclenchée, comme suit :

* Pour les copies répliquées, si une autre copie ne peut pas être récupérée, l'objet est considéré comme perdu et l'alerte est déclenchée.
* Pour les copies avec code d'effacement, si une copie ne peut pas être récupérée à partir de l'emplacement attendu, l'attribut copies corrompues détectées (ECOR) est incrémenté d'une copie avant qu'une tentative de récupération d'une copie ne soit effectuée à partir d'un autre emplacement. Si aucune autre copie n'est trouvée, l'alerte est déclenchée.


Vous devez examiner immédiatement toutes les alertes *Objets potentiellement perdus* pour déterminer la cause première de la perte et déterminer si l'objet peut toujours exister dans un nœud de stockage hors ligne ou actuellement indisponible. Voir link:../troubleshoot/investigating-potentially-lost-objects.html["Enquêter sur les objets potentiellement perdus"] .  Les alertes d'objet perdu peuvent être déclenchées à tort par mesure de précaution.

Dans le cas où les données de l'objet sans copies sont perdues, il n'existe aucune solution de récupération.  Cependant, vous devezlink:../troubleshoot/investigating-potentially-lost-objects.html#reset-lost-obj-count["réinitialiser le compteur d'objets potentiellement perdus"] pour éviter que les objets perdus connus ne masquent les nouveaux objets perdus.
