---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: 'En tant qu"administrateur de la grille, vous pouvez activer la fonction de verrouillage des objets S3 pour votre système StorageGRID et mettre en œuvre une règle ILM conforme pour vous assurer que les objets des compartiments S3 spécifiques ne sont pas supprimés ou remplacés pour une durée spécifiée.' 
---
= Gestion des objets avec le verrouillage d'objets S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En tant qu'administrateur du grid, vous pouvez activer le verrouillage objet S3 sur votre système StorageGRID et mettre en œuvre une règle ILM conforme pour empêcher la suppression ou l'écrasement des objets de compartiments S3 spécifiques pendant une durée spécifiée.



== Qu'est-ce que le verrouillage objet S3 ?

La fonctionnalité de verrouillage objet StorageGRID S3 est une solution de protection des objets équivalente au verrouillage objet S3 dans Amazon simple Storage Service (Amazon S3).

Lorsque le paramètre de verrouillage objet S3 global est activé pour un système StorageGRID, un compte de locataire S3 peut créer des compartiments avec ou sans verrouillage objet S3 activé. Si le verrouillage objet S3 est activé pour un compartiment, la gestion des versions de compartiment est requise et elle est automatiquement activée.

*Un compartiment sans S3 Object Lock* ne peut contenir que des objets sans paramètres de rétention spécifiés. Aucun objet ingéré ne possède de paramètres de conservation.

*Un compartiment avec S3 Object Lock* peut contenir des objets avec et sans paramètres de conservation spécifiés par les applications client S3. Certains objets ingérés auront des paramètres de conservation.

*Un compartiment avec le verrouillage d'objet S3 et la rétention par défaut configurés* peut avoir téléchargé des objets avec des paramètres de rétention spécifiés et de nouveaux objets sans paramètres de rétention. Les nouveaux objets utilisent le paramètre par défaut, car le paramètre de rétention n'a pas été configuré au niveau de l'objet.

En effet, tous les objets nouvellement ingérés ont des paramètres de conservation lorsque la conservation par défaut est configurée. Les objets existants sans paramètres de conservation d'objet ne sont pas affectés.



=== Modes de rétention

La fonction de verrouillage d'objet StorageGRID S3 prend en charge deux modes de conservation pour appliquer différents niveaux de protection aux objets. Ces modes sont équivalents aux modes de conservation Amazon S3.

* En mode conformité :
+
** L'objet ne peut pas être supprimé tant que sa date de conservation jusqu'à n'est pas atteinte.
** La date de conservation de l'objet peut être augmentée, mais elle ne peut pas être réduite.
** La date de conservation de l'objet jusqu'à ne peut pas être supprimée tant que cette date n'est pas atteinte.


* En mode gouvernance :
+
** Les utilisateurs disposant d'une autorisation spéciale peuvent utiliser un en-tête de contournement dans les demandes pour modifier certains paramètres de conservation.
** Ces utilisateurs peuvent supprimer une version d'objet avant d'atteindre sa date de conservation jusqu'à.
** Ces utilisateurs peuvent augmenter, diminuer ou supprimer la date de conservation d'un objet.






=== Paramètres de conservation pour les versions d'objet

Si un compartiment est créé avec le verrouillage objet S3 activé, les utilisateurs peuvent utiliser l'application client S3 pour spécifier éventuellement les paramètres de conservation suivants pour chaque objet ajouté au compartiment :

* *Mode de conservation* : conformité ou gouvernance.
* *Conserver-jusqu'à-date*: Si la date de conservation d'une version d'objet est dans le futur, l'objet peut être récupéré, mais il ne peut pas être supprimé.
* *Mise en garde légale* : l'application d'une mise en garde légale à une version d'objet verrouille immédiatement cet objet. Par exemple, vous devrez peut-être mettre une obligation légale sur un objet lié à une enquête ou à un litige juridique. Une obligation légale n'a pas de date d'expiration, mais reste en place jusqu'à ce qu'elle soit explicitement supprimée. Les dispositions légales sont indépendantes de la date de conservation.
+

NOTE: Si un objet fait l'objet d'une conservation légale, personne ne peut le supprimer, quel que soit son mode de conservation.

+
Pour plus de détails sur les paramètres de l'objet, reportez-vous à la section link:../s3/use-s3-api-for-s3-object-lock.html["Utilisez l'API REST S3 pour configurer le verrouillage objet S3"].





=== Paramètre de rétention par défaut pour les compartiments

Si un compartiment est créé avec le verrouillage objet S3 activé, les utilisateurs peuvent spécifier les paramètres par défaut suivants pour le compartiment :

* *Mode de rétention par défaut* : conformité ou gouvernance.
* *Période de rétention par défaut* : durée pendant laquelle les nouvelles versions d'objets ajoutées à ce compartiment doivent être conservées, à partir du jour où elles sont ajoutées.


Les paramètres de compartiment par défaut s'appliquent uniquement aux nouveaux objets qui ne disposent pas de leurs propres paramètres de conservation. Les objets de compartiment existants ne sont pas affectés lorsque vous ajoutez ou modifiez ces paramètres par défaut.

Voir link:../tenant/creating-s3-bucket.html["Créer un compartiment S3"] et link:../tenant/update-default-retention-settings.html["Mettre à jour la conservation par défaut du verrouillage d'objet S3"].



== Comparaison du verrouillage d'objet S3 à la conformité existante

Le verrouillage d'objet S3 remplace la fonctionnalité de conformité disponible dans les versions précédentes de StorageGRID. Comme la fonctionnalité de verrouillage d'objet S3 est conforme aux exigences d'Amazon S3, elle délibère la fonctionnalité propriétaire StorageGRID Compliance, qui est maintenant appelée « conformité héritée ».


NOTE: Le paramètre conformité globale est obsolète. Si vous avez activé ce paramètre à l'aide d'une version précédente de StorageGRID, le paramètre verrouillage objet S3 est activé automatiquement. Vous pouvez continuer à utiliser StorageGRID pour gérer les paramètres des compartiments conformes existants ; cependant, vous ne pouvez pas créer de nouveaux compartiments conformes. Pour plus de détails, voir https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Base de connaissances NetApp : comment gérer des compartiments conformes aux ancienne génération dans StorageGRID 11.5"^].

Si vous avez utilisé la fonctionnalité de conformité héritée dans une version précédente de StorageGRID, reportez-vous au tableau suivant pour savoir comment la comparer à la fonctionnalité de verrouillage d'objet S3 dans StorageGRID.

[cols="1a,1a,1a"]
|===
|  | Verrouillage d'objet S3 | Conformité (existant) 


 a| 
Comment cette fonctionnalité est-elle activée dans le monde entier ?
 a| 
Dans Grid Manager, sélectionnez *CONFIGURATION* > *système* > *verrouillage objet S3*.
 a| 
N'est plus pris en charge.



 a| 
Comment la fonctionnalité est-elle activée pour un compartiment ?
 a| 
Les utilisateurs doivent activer le verrouillage objet S3 lors de la création d'un compartiment à l'aide du gestionnaire de locataires, de l'API de gestion des locataires ou de l'API REST S3.
 a| 
N'est plus pris en charge.



 a| 
Le contrôle de version des compartiments est-il pris en
 a| 
Oui. Le contrôle de version des compartiments est requis et activé automatiquement lorsque le verrouillage des objets S3 est activé pour le compartiment.
 a| 
Non



 a| 
Comment la conservation d'objets est-elle définie ?
 a| 
Les utilisateurs peuvent définir une date de conservation jusqu'à pour chaque version d'objet ou définir une période de conservation par défaut pour chaque compartiment.
 a| 
Les utilisateurs doivent définir une période de conservation pour l'intégralité du compartiment. La période de conservation s'applique à tous les objets du compartiment.



 a| 
La période de conservation peut-elle être modifiée ?
 a| 
* En mode conformité, la date de conservation jusqu'à la date d'un objet peut être augmentée, mais jamais réduite.
* En mode gouvernance, les utilisateurs disposant d'autorisations spéciales peuvent diminuer, voire supprimer les paramètres de conservation d'un objet.

 a| 
La période de rétention d'un godet peut être augmentée, mais jamais réduite.



 a| 
Où est contrôlé la suspension légale ?
 a| 
Les utilisateurs peuvent placer une conservation légale ou lever une conservation légale pour toute version d'objet dans le compartiment.
 a| 
Une retenue légale est placée sur le godet et affecte tous les objets du godet.



 a| 
Quand les objets peuvent-ils être supprimés ?
 a| 
* En mode de conformité, une version d'objet peut être supprimée une fois la date de conservation jusqu'à atteinte, en supposant que l'objet n'est pas en attente légale.
* En mode gouvernance, les utilisateurs disposant d'autorisations spéciales peuvent supprimer un objet avant que sa date de conservation jusqu'à soit atteinte, en supposant que l'objet ne soit pas en attente légale.

 a| 
Un objet peut être supprimé après l'expiration de la période de conservation, en supposant que le compartiment n'est pas en conservation légale. Les objets peuvent être supprimés automatiquement ou manuellement.



 a| 
La configuration du cycle de vie des compartiments est-elle prise en
 a| 
Oui
 a| 
Non

|===