---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: 'Un pool de stockage cloud vous permet d"utiliser ILM pour déplacer les données d"objets en dehors de votre système StorageGRID. Par exemple, vous pourriez vouloir déplacer des objets rarement consultés vers un stockage cloud à moindre coût, comme Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud ou le niveau d"accès Archive dans Microsoft Azure Blob Storage. Ou, vous pourriez vouloir maintenir une sauvegarde cloud des objets StorageGRID afin d"améliorer la reprise après sinistre.' 
---
= Découvrez les Cloud Storage Pools dans StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un pool de stockage cloud vous permet d'utiliser ILM pour déplacer les données d'objets en dehors de votre système StorageGRID. Par exemple, vous pourriez vouloir déplacer des objets rarement consultés vers un stockage cloud à moindre coût, comme Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud ou le niveau d'accès Archive dans Microsoft Azure Blob Storage. Ou, vous pourriez vouloir maintenir une sauvegarde cloud des objets StorageGRID afin d'améliorer la reprise après sinistre.

Du point de vue de la gestion du cycle de vie des informations (ILM), un pool de stockage cloud est similaire à un pool de stockage. Pour stocker des objets à l’un ou l’autre emplacement, vous sélectionnez le pool lors de la création des instructions de placement d’une règle ILM. Cependant, alors que les pools de stockage sont constitués de nœuds de stockage au sein du système StorageGRID, un pool de stockage cloud est constitué d’un compartiment externe (S3) ou d’un conteneur (Azure Blob Storage).

Le tableau compare les pools de stockage aux pools de stockage cloud et montre les similarités et les différences de haut niveau.

[cols="1a,2a,5a"]
|===
|  | Pool de stockage | Pool de stockage cloud 


 a| 
Comment est-elle créée ?
 a| 
Utilisation de l'option *ILM* > *Storage pools* dans Grid Manager.
 a| 
Utilisation de l'option *ILM* > *Storage pools* > *Cloud Storage pools* dans Grid Manager.

Vous devez configurer le compartiment ou le conteneur externe avant de pouvoir créer le pool de stockage cloud.



 a| 
Combien de pools pouvez-vous créer ?
 a| 
Illimitée.
 a| 
Jusqu'à 10.



 a| 
Où sont stockés les objets ?
 a| 
Sur un ou plusieurs nœuds de stockage dans StorageGRID.
 a| 
Dans un compartiment Amazon S3, un conteneur Azure Blob Storage ou un Google Cloud externe au système StorageGRID.

Si le pool de stockage cloud est un compartiment Amazon S3 :

* Vous pouvez configurer un cycle de vie de compartiment pour la transition des objets vers un stockage à long terme à faible coût, comme Amazon S3 Glacier ou S3 Glacier Deep Archive. Le système de stockage externe doit prendre en charge la classe de stockage Glacier et l'API RestoreObject S3.
* Vous pouvez créer des pools de stockage cloud à utiliser avec AWS commercial Cloud Services (C2S), qui prend en charge la région secrète AWS.


Si le pool de stockage cloud est un conteneur Azure Blob Storage, StorageGRID transfère l'objet vers le niveau Archive.

*Remarque :* En général, ne configurez pas la gestion du cycle de vie d’Azure Blob Storage pour le conteneur utilisé pour un pool de stockage cloud. RestoreObject opérations sur les objets dans le pool de stockage cloud peuvent être affectées par le cycle de vie configuré.



 a| 
Quels sont les contrôles du placement des objets ?
 a| 
Règle ILM dans les politiques ILM actives.
 a| 
Règle ILM dans les politiques ILM actives.



 a| 
Quelle est la méthode de protection des données utilisée ?
 a| 
La réplication ou le code d'effacement.
 a| 
La réplication.



 a| 
Combien de copies de chaque objet sont autorisées ?
 a| 
Plusieurs.
 a| 
Une copie dans le pool de stockage cloud et, éventuellement, une ou plusieurs copies dans StorageGRID.

*Remarque :* vous ne pouvez pas stocker un objet dans plusieurs pools de stockage cloud à un moment donné.



 a| 
Quels sont les avantages ?
 a| 
Les objets sont rapidement accessibles à tout moment.
 a| 
Stockage à moindre coût

*Remarque* : les données FabricPool ne peuvent pas être hiérarchisées vers des pools de stockage cloud.

|===