---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Un pool de stockage est un regroupement logique de nœuds de stockage. 
---
= Qu'est-ce qu'un pool de stockage ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un pool de stockage est un regroupement logique de nœuds de stockage.

Lorsque vous installez StorageGRID, un pool de stockage par site est automatiquement créé. Vous pouvez configurer des pools de stockage supplémentaires selon vos besoins en stockage.


NOTE: Les nœuds de stockage peuvent être configurés au cours de l'installation pour contenir les données d'objet et les métadonnées d'objet, ou uniquement les métadonnées d'objet. Les nœuds de stockage de métadonnées uniquement ne peuvent pas être utilisés dans les pools de stockage. Pour plus d'informations, voir link:../primer/what-storage-node-is.html#types-of-storage-nodes["Types de nœuds de stockage"].

Les pools de stockage ont deux attributs :

* *Stockage* : pour les nœuds de stockage, les performances relatives du stockage de support.
* *Site* : le centre de données où les objets seront stockés.


Les pools de stockage sont utilisés dans les règles ILM pour déterminer l'emplacement du stockage des données en mode objet et le type de stockage utilisé. Lorsque vous configurez les règles ILM pour la réplication, vous sélectionnez un ou plusieurs pools de stockage.
