---
permalink: release-notes/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: 'StorageGRID 12.1 utilise la version 4 de l"API de gestion des locataires. La version 4 remplace la version 3. Cependant, les versions 1, 2 et 3 restent prises en charge.' 
---
= Modifications apportées à l'API de gestion des locataires dans StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 utilise la version 4 de l'API de gestion des locataires. La version 4 remplace la version 3 ; toutefois, les versions 1, 2 et 3 restent prises en charge.


NOTE: Vous pouvez continuer à utiliser les versions obsolètes de l'API de gestion des locataires avec StorageGRID ; toutefois, la prise en charge de ces versions de l'API sera supprimée dans une prochaine version de StorageGRID. Après la mise à niveau vers StorageGRID 12.0 ou une version ultérieure, vous pouvez désactiver les API obsolètes à l'aide de l' `PUT /grid/config/management` API.

Pour en savoir plus, rendez-vous sur link:../tenant/understanding-tenant-management-api.html["Découvrez l'API de gestion des locataires"].



[[new-api-for-object-replication]]
== Nouvelle API pour la réplication d'objets

Vous pouvez utiliser le `/org/cross-grid-replication/{versionId}/replicate` API pour répliquer manuellement des objets sur un bucket existant dont la réplication inter-grille est nouvellement configurée.
