---
permalink: release-notes/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 12.1 utilise la version 4 de l"API de gestion de la grille. La version 4 remplace la version 3. Cependant, les versions 1, 2 et 3 restent prises en charge.' 
---
= Modifications apportées à l'API de gestion de la grille dans StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 utilise la version 4 de l'API de gestion de la grille. La version 4 remplace la version 3 ; toutefois, les versions 1, 2 et 3 restent prises en charge.


NOTE: Vous pouvez continuer à utiliser les versions obsolètes de l'API de gestion avec StorageGRID ; cependant, la prise en charge de ces versions de l'API sera supprimée dans une future version de StorageGRID. Après la mise à niveau vers StorageGRID 12.0 ou une version ultérieure, vous pouvez désactiver les API obsolètes en utilisant l' `PUT /grid/config/management`API.

Pour en savoir plus, rendez-vous sur link:../admin/using-grid-management-api.html["Utilisez l'API de gestion du grid"].



[[new-endpoints-for-changing-the-bmc-password-and-lan-ip-settings]]
== Nouveaux points de terminaison pour la modification du mot de passe BMC et des paramètres IP LAN

Le point de terminaison suivant a été ajouté pour vous permettre de link:../harden/hardening-guidelines-for-storagegrid-nodes.html#change-appliance-bmc-password["modifier le mot de passe BMC d'un appareil"].

`PUT /bmc-configuration/root-password`

Les points de terminaison suivants ont été ajoutés pour vous permettre de link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["modifier ou afficher les paramètres IP LAN du BMC"].

`PUT /grid/bmc/{node-id}/lan-ip-config`

`GET /grid/bmc/{node-id}/lan-ip-config`
