---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.1 
summary: Cette version de StorageGRID introduit les fonctionnalités et modifications fonctionnelles suivantes. 
---
= Nouveautés de StorageGRID 12.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 introduit les fonctionnalités et modifications fonctionnelles suivantes.

Pour plus de détails sur les problèmes résolus et les problèmes connus dans les versions récentes de StorageGRID 12.1, consultez  https://library.netapp.com/ecm/ecm_download_file/ECMLP3373065["Notes de version de StorageGRID 12.1"^]. Vous devez vous connecter avec votre compte NetApp ou en créer un pour accéder aux notes de version.



[[capacity]]
== Capacité



[[ec-rebalance-now-uses-free-space]]
=== Le rééquilibrage EC utilise désormais l'espace libre

Le rééquilibrage EC utilise désormais l'espace libre au lieu de l'espace utilisé. Voir link:../expand/considerations-for-rebalancing-erasure-coded-data.html#what-is-ec-rebalancing["Découvrez le rééquilibrage EC après l'extension de StorageGRID."].



[[metadata-allowed-space]]
=== Espace autorisé pour les métadonnées

Vous pouvez désormais augmenter la valeur maximale autorisée des métadonnées de 3,96 To à 7,92 To. Reportez-vous à link:../admin/managing-object-metadata-storage.html#allowed-metadata-space["Espace de métadonnées autorisé"].



[[control-access]]
== Contrôle d'accès



[[sso-using-oidc]]
=== SSO utilisant OIDC

Vous pouvez maintenant link:../admin/learn-about-setting-up-sso-oidc.html["Configurer l'authentification unique (SSO) dans StorageGRID à l'aide d'OpenID Connect (OIDC)"].



[[federation]]
== Fédération



[[global-namespace]]
=== Espace de noms global

Vous pouvez désormais configurer un espace de noms global pour permettre aux locataires d'accéder aux compartiments sur plusieurs systèmes StorageGRID. Consultez link:../admin/learn-about-global-namespace.html["Découvrez l'espace de noms global"].



[[manageability]]
== Facilité de gestion



[[auto-move-adc-service]]
=== Service ADC à déplacement automatique

link:../maintain/understanding-adc-service-quorum.html["Lorsque cela est nécessaire pour atteindre le quorum de l'ADC"], le service ADC sera désormais déplacé automatiquement lorsque vous link:../maintain/convert-to-data-only-node.html["conversion d’un nœud de stockage en nœud de données uniquement"] ou link:../maintain/considerations-for-decommissioning-storage-nodes.html["mise hors service d'un nœud de stockage"].



[[primary-admin-node-recovery]]
=== Récupération du nœud d'administration principal

Vous pouvez désormais récupérer n'importe quel nœud à partir d'un nœud d'administration non principal. Consultez link:../maintain/recovering-from-primary-admin-node-failures.html["Récupération après des défaillances du nœud d'administration principal"].



[[s3]]
== S3



[[enable-s3-object-lock-on-existing-buckets]]
=== Activer le verrouillage d'objets S3 sur les compartiments existants

Lorsque l'option « Autoriser le verrouillage d'objets S3 pour les compartiments existants » est activée, un compte locataire S3 peut désormais activer le verrouillage d'objets S3 pour un compartiment existant. Après qu'un compte locataire S3 a activé le verrouillage d'objets S3 pour un compartiment existant, il ne peut plus être désactivé.



[[replication-allowed-for-s3-object-lock-enabled-buckets]]
=== Réplication autorisée pour les compartiments S3 avec Object Lock activé

Vous pouvez désormais utiliser CloudMirror pour répliquer des objets dans des compartiments S3 avec Object Lock activé. Reportez-vous à link:../tenant/considerations-for-platform-services.html["Découvrez les services de plateforme"].



[[enable-cross-grid-replication-for-non-empty-buckets]]
=== Activer la réplication inter-grilles pour les compartiments non vides

Vous pouvez désormais activer la réplication inter-grilles pour les compartiments non vides. Consultez link:../admin/grid-federation-what-is-cross-grid-replication.html#requirements-for-cross-grid-replication["Conditions requises pour la réplication entre les grilles"].



[[s3-batch-operations-fpvr-only]]
=== Opérations par lots S3 (FPVR uniquement)

Vous pouvez utiliser les opérations par lots S3 pour répliquer des objets existants dans un compartiment avec le versionnage activé que vous prévoyez de configurer pour la réplication inter-grilles.

Cette fonctionnalité nécessite l'approbation de FPVR pour StorageGRID 12.1. Pour utiliser cette fonctionnalité, contactez votre représentant commercial.



[[non-functional-s3-rest-api-headers]]
=== En-têtes S3 REST API non fonctionnels

Les  `If-Match` et  `If-None-Match` en-têtes sont acceptés mais non fonctionnels pour l’API REST S3 link:../s3/put-object.html["PutObject"], link:../s3/complete-multipart-upload.html["CompleteMultipartUpload"], link:../s3/put-object-copy.html["Objet de copie"] et link:../s3/operations-on-objects.html["DeleteObject"].

Pour plus d'informations, veuillez consulter link:../release-notes/changes-to-s3-rest-api.html["Modifications apportées à la prise en charge de l'API REST S3 de StorageGRID"].



[[support-for-pre-calculated-checksum-values]]
=== Prise en charge des valeurs de somme de contrôle précalculées

L'interface SPI REST S3 prend désormais en charge les valeurs de somme de contrôle précalculées et l' `x-amz-checksum-type`en-tête de requête. Reportez-vous à link:../s3/index.html#updates-to-rest-api-support["Mises à jour de la prise en charge de l'API REST"].



[[security]]
== Sécurité



[[multi-admin-verification]]
=== Vérification multi-administrateurs

La vérification multi-administrateurs (MAV) contribue à prévenir les modifications accidentelles ou non autorisées de votre système StorageGRID. Consultez link:../admin/about-multi-admin-verify.html["Découvrez la vérification multi-administrateur de StorageGRID"].



[[security-policy-updates-for-fips]]
=== Mises à jour de la politique de sécurité pour FIPS

Les critères stricts de la politique FIPS ont été mis à jour. Voir link:../admin/manage-tls-ssh-policy.html#select-a-security-policy["Sélectionnez une stratégie de sécurité dans Gérer la stratégie TLS et SSH"].



[[tenants]]
== Locataires



[[account-sync]]
=== Synchronisation des comptes

La fonctionnalité _account clone_ fait désormais référence à un clonage unique des informations d'un compte locataire spécifique.

_La synchronisation des comptes_ est une nouvelle fonctionnalité qui vous permet de répliquer automatiquement et en continu les comptes de locataires, les groupes de locataires, les utilisateurs de locataires et les clés d'accès S3 entre les systèmes StorageGRID dans une ou plusieurs connexions de fédération de grilles. Reportez-vous à link:../admin/grid-federation-what-is-account-sync.html["Découvrez la synchronisation des comptes dans StorageGRID"].



[[kafka-endpoints-and-mtls-authentication]]
=== Points de terminaison Kafka et authentification mTLS

Le protocole Mutual Transport Layer Security (mTLS) est désormais pris en charge pour les points de terminaison Kafka. Consultez link:../tenant/configuring-platform-services-endpoints.html["Configurer les terminaux des services de plateforme"].



[[maximum-number-of-buckets]]
=== Nombre maximal de compartiments

Un système StorageGRID prend désormais en charge un maximum de 20 000 compartiments pour chaque compte locataire S3.



[[upgrade]]
== Mise à niveau



[[time-to-enable-features-is-increased]]
=== Le délai d'activation des fonctionnalités est augmenté

Lors de la mise à niveau de StorageGRID vers la version 12.1, le temps d’activation des fonctionnalités est passé de moins de cinq minutes à une heure. Reportez-vous à link:../upgrade/estimating-time-to-complete-upgrade.html#estimate-time-to-upgrade["Estimez le temps nécessaire pour effectuer une mise à niveau de StorageGRID"].



[[user-interface]]
== Interface utilisateur



[[bmc-settings-page]]
=== Page des paramètres BMC

Un nouvel onglet « Paramètres BMC » a été ajouté à la page « Nœuds » dans Grid Manager pour permettre la réinitialisation du mot de passe BMC et la modification des paramètres IP LAN du BMC. Consultez link:../harden/hardening-guidelines-for-storagegrid-nodes.html["Modifier le mot de passe BMC de l'appliance"] et link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["Modifier les paramètres IP LAN du BMC du nœud de l'appliance"]. De nouveaux points de terminaison API ont également été ajoutés pour prendre en charge ces fonctions. Consultez link:../release-notes/changes-to-grid-management-api.html["Nouveaux points de terminaison pour la modification du mot de passe BMC et des paramètres IP LAN"].



[[email-notifications]]
=== Notifications par e-mail

Le Gestionnaire de grille dispose désormais d'une page de messagerie commune permettant de configurer et de gérer les notifications par e-mail pour les alertes, AutoSupport et la vérification multi-administrateurs (MAV). Reportez-vous à link:../monitor/configure-email-server.html["Configurer le serveur de messagerie"].



[[link-cost-page-update]]
=== Mise à jour de la page du coût des liens

StorageGRID 12.1 fournit des informations et des paramètres plus détaillés sur les coûts des liens. Consultez link:../admin/manage-link-costs.html["Gérer les coûts de liaison"].



[[usb-port-control]]
=== Contrôle du port USB

Vous pouvez désormais activer ou désactiver les ports USB via Grid Manager. Consultez link:../harden/hardening-guidelines-for-storagegrid-nodes.html#control-remote-access-through-usb-ports["Contrôlez l'accès à distance via les ports USB"].
