---
permalink: fabricpool/use-fabricpool-setup-wizard.html 
sidebar: sidebar 
keywords: fabricPool, FabricPool setup wizard, ontap system manager 
summary: 'Vous pouvez utiliser l"assistant d"installation de FabricPool pour configurer StorageGRID en tant que système de stockage objet pour un Tier cloud FabricPool. Une fois l"assistant d"installation terminé, vous pouvez entrer les informations requises dans ONTAP System Manager.' 
---
= Utilisez l'assistant de configuration FabricPool : considérations et configuration requise
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser l'assistant d'installation de FabricPool pour configurer StorageGRID en tant que système de stockage objet pour un Tier cloud FabricPool. Une fois l'assistant d'installation terminé, vous pouvez entrer les informations requises dans ONTAP System Manager.



== Quand utiliser l'assistant de configuration FabricPool

L'assistant d'installation FabricPool vous guide à chaque étape de la configuration de StorageGRID pour une utilisation avec FabricPool et configure automatiquement certaines entités pour vous, telles que les règles ILM et de classification du trafic. Dans le cadre de l'assistant, vous téléchargez un fichier que vous pouvez utiliser pour saisir des valeurs dans ONTAP System Manager. Utilisez l'assistant pour configurer votre système plus rapidement et pour vous assurer que vos paramètres sont conformes aux meilleures pratiques StorageGRID et FabricPool.

En supposant que vous disposez de l'autorisation d'accès racine, vous pouvez exécuter l'assistant de configuration FabricPool lorsque vous commencez à utiliser le Gestionnaire de grille StorageGRID, ou vous pouvez accéder à l'assistant et l'exécuter ultérieurement. En fonction de vos besoins, vous pouvez également configurer manuellement une partie ou la totalité des éléments requis, puis utiliser l'assistant pour assembler les valeurs dont ONTAP a besoin dans un seul fichier.


TIP: Utilisez l'assistant d'installation de FabricPool, sauf si vous savez que vous avez des exigences spéciales, sinon votre implémentation nécessitera une personnalisation importante.



== Avant d'utiliser l'assistant

Confirmez que vous avez effectué ces étapes préalables.



=== Passez en revue les bonnes pratiques

* Vous avez une compréhension générale de la link:information-needed-to-attach-storagegrid-as-cloud-tier.html["Informations requises pour associer StorageGRID en tant que Tier cloud"].
* Vous avez examiné les bonnes pratiques de FabricPool pour :
+
** link:best-practices-for-high-availability-groups.html["Groupes haute disponibilité (HA)"]
** link:best-practices-for-load-balancing.html["Équilibrage de la charge"]
** link:best-practices-ilm.html["Règles et règles ILM"]






=== Obtenir des adresses IP et configurer des interfaces VLAN

Si vous configurez un groupe haute disponibilité, vous savez à quels nœuds ONTAP se connectera et à quel réseau StorageGRID sera utilisé. Vous savez également quelles valeurs entrer pour le CIDR de sous-réseau, l'adresse IP de la passerelle et les adresses IP virtuelles (VIP).

Si vous prévoyez d'utiliser un réseau local virtuel pour isoler le trafic FabricPool, vous avez déjà configuré l'interface VLAN. Voir link:../admin/configure-vlan-interfaces.html["Configurez les interfaces VLAN"].



=== Configurer la fédération des identités et SSO

Si vous prévoyez d'utiliser la fédération des identités ou l'authentification unique (SSO) pour votre système StorageGRID, vous avez activé ces fonctionnalités. Vous savez également quel groupe fédéré doit disposer d'un accès racine pour le compte de locataire que ONTAP utilisera. Voir link:../admin/using-identity-federation.html["Utiliser la fédération des identités"] et link:../admin/configuring-sso.html["Configurer l'authentification unique"].



=== Obtenir et configurer des noms de domaine

* Vous savez quel nom de domaine complet (FQDN) utiliser pour StorageGRID. Les entrées de serveur de noms de domaine (DNS) mapperont ce FQDN aux adresses IP virtuelles (VIP) du groupe haute disponibilité que vous créez à l'aide de l'assistant. Voir link:../fabricpool/configure-dns-server.html["Configurer le serveur DNS"].
* Si vous prévoyez d'utiliser les requêtes de type hébergement virtuel S3, vous avez link:../admin/configuring-s3-api-endpoint-domain-names.html["Noms de domaine de terminaux S3 configurés"]. ONTAP utilise par défaut des URL de type chemin d'accès, mais il est recommandé d'utiliser des requêtes de type hébergement virtuel.




=== Examinez les exigences en matière d'équilibreur de charge et de certificat de sécurité

Si vous prévoyez d'utiliser l'équilibreur de charge StorageGRID, vous avez examiné le document général link:../admin/managing-load-balancing.html["considérations relatives à l'équilibrage de charge"]. Vous disposez des certificats que vous allez télécharger ou des valeurs dont vous avez besoin pour générer un certificat.

Si vous prévoyez d'utiliser un noeud final externe (tiers) d'équilibreur de charge, vous disposez du nom de domaine complet (FQDN), du port et du certificat pour cet équilibreur de charge.



=== Confirmation de la configuration du pool de stockage ILM

Si vous avez installé StorageGRID 11.6 ou une version antérieure, vous avez configuré le pool de stockage que vous utiliserez. En général, vous devez créer un pool de stockage pour chaque site StorageGRID que vous utiliserez pour stocker des données ONTAP.


NOTE: Cette condition préalable ne s'applique pas si vous avez installé StorageGRID 11.7 ou 11.8. Lors de l'installation initiale de l'une de ces versions, les pools de stockage sont automatiquement créés pour chaque site.



== Relation entre ONTAP et le niveau cloud StorageGRID

L'assistant FabricPool vous guide tout au long du processus de création d'un niveau cloud StorageGRID unique, qui inclut un locataire StorageGRID, un ensemble de clés d'accès et un compartiment StorageGRID. Vous pouvez associer ce niveau cloud StorageGRID à un ou plusieurs niveaux locaux ONTAP.

L'association d'un seul niveau de cloud à plusieurs niveaux locaux dans un cluster est la meilleure pratique générale. Cependant, selon vos besoins, vous pouvez utiliser plusieurs compartiments, voire plus d'un locataire StorageGRID pour les niveaux locaux dans un seul cluster. L'utilisation de différents compartiments et locataires vous permet d'isoler les données et l'accès aux données entre les tiers locaux ONTAP, mais sa configuration et sa gestion sont un peu plus complexes.

NetApp déconseille d'associer un seul Tier cloud à des tiers locaux dans plusieurs clusters.


NOTE: Pour connaître les meilleures pratiques d'utilisation de StorageGRID avec NetApp MetroCluster™ et FabricPool Mirror, voir https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["Tr-4598 : meilleures pratiques FabricPool dans ONTAP"^].



=== Facultatif : utilisez un compartiment différent pour chaque niveau local

Pour utiliser plusieurs compartiments pour les tiers locaux d'un cluster ONTAP, ajoutez plusieurs niveaux cloud StorageGRID dans ONTAP. Chaque Tier cloud partage le même groupe haute disponibilité, mais il utilise un conteneur différent (compartiment StorageGRID) pour le terminal de l'équilibreur de charge, le locataire et les clés d'accès. Procédez comme suit :

. Dans StorageGRID Grid Manager, suivez les instructions de l'assistant d'installation FabricPool pour le premier niveau cloud.
. Dans ONTAP System Manager, ajoutez un Tier cloud et utilisez le fichier téléchargé depuis StorageGRID pour fournir les valeurs requises.
. Dans le gestionnaire de locataires StorageGRID, connectez-vous au locataire créé par l'assistant, puis créez un second compartiment.
. Terminez à nouveau l'assistant FabricPool. Sélectionnez le groupe haute disponibilité, le terminal de l'équilibreur de charge et le locataire existants. Sélectionnez ensuite le nouveau compartiment que vous avez créé manuellement. Créez une règle ILM pour le nouveau compartiment et activez une règle ILM pour inclure cette règle.
. Depuis ONTAP, ajoutez un second Tier cloud, mais indiquez le nouveau nom de compartiment.




=== Facultatif : utilisez un locataire et un compartiment différents pour chaque niveau local

Pour utiliser plusieurs locataires et jeux de clés d'accès différents pour les tiers locaux d'un cluster ONTAP, ajoutez plusieurs niveaux cloud StorageGRID dans ONTAP. Chaque Tier cloud partage le même groupe haute disponibilité et le même terminal d'équilibrage de la charge, mais utilise un locataire, des clés d'accès et un conteneur différents (compartiment StorageGRID). Procédez comme suit :

. Dans StorageGRID Grid Manager, suivez les instructions de l'assistant d'installation FabricPool pour le premier niveau cloud.
. Dans ONTAP System Manager, ajoutez un Tier cloud et utilisez le fichier téléchargé depuis StorageGRID pour fournir les valeurs requises.
. Terminez à nouveau l'assistant FabricPool. Sélectionnez le groupe haute disponibilité et le terminal d'équilibrage de la charge existants. Créez un locataire et un compartiment. Créez une règle ILM pour le nouveau compartiment et activez une règle ILM pour inclure cette règle.
. Depuis ONTAP, ajoutez un second Tier cloud, mais fournissez la nouvelle clé d'accès, la clé secrète et le nom du compartiment.

